### ISSUE TITLE
We should have a "how to do a restart case" page in the docs

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1000]
Occasionally I am asked how to run a restart case. As far as I know, a page describing this process does not exist in our docs.

I think we should have a simple page in the docs that describes the various settings and options that one has when performing a restart.

**Comment by ntouran** [comment]
There's a doc page on that in the internal tparmi docs that should be migrated out to the framework.

**Comment by keckler** [comment]
Working on this now.

**Comment by keckler** [comment]
Whoops, the PR that I put up had some bad formatting, so it didn't render correctly in the published docs. Reopening.

**Comment by john-science** [comment]
> Whoops, the PR that I put up had some bad formatting, so it didn't render correctly in the published docs. Reopening.

Whoops!

But, whatever, RST takes a minute to get used to.  No worries.
