### ISSUE TITLE
Misleading docstring for component.setDimension()

### ISSUE THREAD

**Issue by jasonbmeng** [terrapower/armi#1011]
Misleading docstring on `setDimension` method caused some minor confusion.

Testing the method indicates the `cold` flag sets the dimension of the component at cold temperature to `val`.
It does not set the dimension of the component at cold temperature such that the thermally expanded hot dimension matches `val`

https://github.com/terrapower/armi/blob/b1658e4a733751213c452b22661830e5ce2f9d9a/armi/reactor/components/component.py#L794-L796

**Comment by john-science** [comment]
So not so much misleading as wrong?

**Comment by john-science** [comment]
So, the only use of the `cold` flag on `Component.setDimension()` is this one line:

https://github.com/terrapower/armi/blob/b1658e4a733751213c452b22661830e5ce2f9d9a/armi/reactor/components/component.py#L809

So, the docstring doesn't _sound_ too far off. 

What do you think it _should_ say?

**Comment by jasonbmeng** [comment]
The docstring for the `cold` flag should just say `If True sets the component cold dimension to the specified value.`

Currently, the flag description implies that `c.setDimension("op", 30.0, cold=True)` will set the cold dimension to a _thermally contracted_ value such that the hot dimension is 30.0 which is completely different behavior from what it actually does. It sets the component cold dimension to be 30.0 which is correct behavior imo. So no changes requested in the method, just the docstring.

**Comment by john-science** [comment]
@jasonbmeng PR opened over [here](https://github.com/terrapower/armi/pull/1019).
