### ISSUE TITLE
Operator reference

### ISSUE THREAD

**Issue by mcastillo10** [terrapower/armi#1012]
@john-science @onufer This line has reactor referencing operator

https://github.com/terrapower/armi/blob/b1658e4a733751213c452b22661830e5ce2f9d9a/armi/reactor/converters/geometryConverters.py#L579

**Comment by john-science** [comment]
@mcastillo10  @onufer  The PR to fix this is up over [here](https://github.com/terrapower/armi/pull/1014).

**Comment by john-science** [comment]
@mcastillo10 @onufer Bug fixed.
