### ISSUE TITLE
Our coverage checking config with coveralls.io is broken

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1017]
On Friday, our `coveralls.io` CI, which displays and reports our code coverage, broke.

The only clue as to _why_ it broke is it is [complaining we need a auth token in our GH Actions env](https://github.com/terrapower/armi/actions/runs/3661375615/jobs/6196178031#step:8:771).   

Well, fine. But I don't have permissions to log into the ARMI coveralls.io account and find such a token.  And the last 15 months we certainly haven't used one.  So.  Unless @youngmit  or @ntouran have access to that coveralls.io account, that is dead in the water.   BUT... honestly, coveralls has always been flaky (see [this ticket](#552 ).

> Our build will be broke until we ditch `coveralls.io`.

**Comment by ntouran** [comment]
Yeah I'm like 99% sure I have that login. We can configure the auth there as needed, shouldn't be too hard. maybe our original token expired.

**Comment by john-science** [comment]
Holler when you find it!

**Comment by ntouran** [comment]
Ok I have it. The error you linked above says: 

> coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.

So I guess we can just set the `COVERALLS_REPO_TOKEN` to the token I see in our GH Actions config somewhere, eh?

**Comment by ntouran** [comment]
I am looking for more explicit docs explaining this though. Right now when you go to https://docs.coveralls.io/ and click on the github actions thing it takes you to their [nicely-packaged coveralls GH action](https://github.com/marketplace/actions/coveralls-github-action) which I don't think we're using. We only mention coveralls in the tox.ini file. Maybe we should adjust our config to be up-to-date with the services docs?

**Comment by ntouran** [comment]
Anyway, my PR did ok but not all the way. commenting in there as we work though it.
