### ISSUE TITLE
reactor indexing is not same order as iteration

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#1018]
```python
for i,a in enumerate(o.r.core):
    if someFunctionAssemblyMatches:
        break
assert o.r.core[i] == a  # this is false
```

I would expect the index order to be the same as iteration order but it is not.

another desciption if the top is not clear

```python
for a in o.r.core:
    print(a)
    break
assert o.r.core[0] == a  # this is false
```

**Comment by john-science** [comment]
Well, let's see. The reason _how_ it is that was is easy to understand.  For instance, when you do `core[i]`, you call this code:

https://github.com/terrapower/armi/blob/23bb1c3cd2b1322dafc4f025d7f9c5dbf11b3665/armi/reactor/composites.py#L2656-L2657

That retrieves the `Assembly` from the `Reactor` by the order it was added to the `Reactor`.  We have a _lot_ of downstream code that people seem to love that depends on ARMI physical objects having an order determined by the order they were added to the `Reactor`. For better or worse, people seem to demand that as a feature.  

But when you did `for i, a in enumerate(core)`, you called this method on `class Core`:

https://github.com/terrapower/armi/blob/23bb1c3cd2b1322dafc4f025d7f9c5dbf11b3665/armi/reactor/reactors.py#L243-L251

Now, from the comment we can clearly see this was meant to always iterate over the highest-level objects in a `Core` (in this case probably Aseemblies) in the same order.  Without this method, we would iterate through the children in random order every time:

https://github.com/terrapower/armi/blob/23bb1c3cd2b1322dafc4f025d7f9c5dbf11b3665/armi/reactor/composites.py#L2662-L2663

Now, perhaps @ntouran can shed light on why we end up where we are.  But I can definitely say a couple of things:

1. We are here on purpose. (Take that for what it's worth.)
2. Changing this would cause a lot of rewrites and bug fixes downstream.e

IF we are to go about changing this situation, I would say that `Core.__iter__()` returning things in a sorted order is definitely the way to go, and we should change `Composite.__iter__()` to do the same.  In this solution, I would also want to change `Composite.__getitem__()` to get an item by it's position in the SORTER order, not that arbitrary order the `Core` was built in.

Having said _all_ that, I don't think we should close this ticket just yet, I think it would have pretty broad impact on ARMI and the ARMI ecosystem; this isn't just a small PR I can make without breaking people's plugins.

Thoughts? Opinions?

**Comment by onufer** [comment]
> We have a lot of downstream code that people seem to love that depends on ARMI physical objects having an order determined by the order they were added to the Reactor

I was not at all aware of any downstream code that relies on assemblies being in a specific order. if we think we need that though and need to retain, that's fine. My request is that the order be the same no matter how you access it.

folks think of a reactor as a list of assemblies so i would hope the furst element of `for a in core` would be the same as `core[0]`.

**Comment by ntouran** [comment]
We have a big thread in our previous issue system describing this. I'll migrate some of the discussion over here.

**Comment by jakehader** [comment]
> We have a big thread in our previous issue system describing this. I'll migrate some of the discussion over here.

Still waiting 👀

**Comment by onufer** [comment]
This has come up multiple times in training new armi users. they expect if its a list they can just index it and assume the right order, but you cant.

@ntouran  can you migrate when you can?

**Comment by john-science** [comment]
@onufer  @jakehader @mgjarrett 

First, please read my above comment for a description of the situation.

I appreciate the original _idea_ that `Component.__iter__()` return `Component`s in a sorted order.  The goal there was wise. But, as Mark found, it means that depending on HOW you access components in your reactor/assembly/block, they can be returned in different order.

Now, as I said in (2) above, I could go through an ever-increasing number of methods in `Reactor` and `Component`, and make sure they return everything in order.  But if someone adds a new method, we will need to stay ON TOP of things, to make sure that new method complies with our desired ordering.

> I have a new suggestion.

1. I think we should take the one instance of `sorted()` out of the system. The one that Mark/Nick identified above in `Component.__iter__()`.  (In this way, Components will always be returned in the same order.
2. But I will add a NEW method to Reactor/Component, that will go through and `sort()` the children of the Reactor. (This way, if the order of the components matters to you, you can easily fix it).

This solution has the benefits:

1. It is a small change, and will be faster to implement.
2. Nick's original goal of sorted components can still easily be met.
3. It ensure that ALL of our iteration methods will always return the entire Reactor in the same order.

I believe this solution is efficient and meets everybody's needs.  As such, I will implement it unless one of you speaks up. :)
