### ISSUE TITLE
TH Param Spring Cleaning: remove THdeltaPNoGrav

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#1021]
`THdeltaPNoGrav` appears to only be an implementation detail used to compute `THdilationPressure` and isn't used anywhere else. It also does not seem to be significant for analysis. It should be possible to remove that parameter so as to keep the parameter list minimal.

Parent Issue https://github.com/terrapower/armi/issues/970

**Comment by andfranklin** [comment]
@dlangewisch do you think it would be okay to remove this?

**Comment by john-science** [comment]
This ticket was opened 1.5 years ago, so I am going to close it.

Though, if people find this to be interesting again, I would happily do the work.

**Comment by andfranklin** [comment]
Thanks @john-science
