### ISSUE TITLE
Snapshots have no unit tests

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1028]
PRs #1024 and #1025 highlighted the need for unit tests for the snapshots operator.

**Comment by john-science** [comment]
Good idea!

I recently created our first [unit test file for snapshots](https://github.com/terrapower/armi/pull/1029/files#diff-719fddca3f6e57c1f18e86d32de69d9b373aed62e36912af00198c2a77c4bbad), and increased our code coverage on `snapshots.py` from 23% to 71%.

I think a couple quick unit tests should be able to get that code coverage up to ~90%.

**Comment by opotowsky** [comment]
I didn't realize you added that much coverage! I think 71% is a worthy enough value to consider this issue closed.
