### ISSUE TITLE
Can we remove `refType` setting from our test case setting files?

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1034]
We have these sample case setting files that contain the setting `refType`:
https://github.com/terrapower/armi/blob/e47abd2690e3833bf8e3ed02225df2ddea6bc017/armi/tests/armiRun.yaml#L55
https://github.com/terrapower/armi/blob/e47abd2690e3833bf8e3ed02225df2ddea6bc017/armi/tests/refTestCartesian.yaml#L30

When I use those files, my ARMI complains that it doesn't know what that setting means.

Grepping around the code, I can't find a definition for the setting anywhere. I also have never used it, and I don't see it in the [settings report](https://terrapower.github.io/armi/user/inputs/settings_report.html). This leads me to think that it is an old setting that was removed at some point.

Perhaps we just forgot to remove it from these two case settings files.

Is it possible for us to remove those lines?

**Comment by ntouran** [comment]
Yeah it was the reference assembly that we'd duplicate when creating a new assembly way back in the day. This has been superceded by the concept of blueprints.
