### ISSUE TITLE
NumPy Jagged Array Deprecation on 1.24.0 Release

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#1036]
The latest release of NumPy has deprecated the jagged array treatment that we are using in the database when writing parameter data - https://github.com/numpy/numpy/releases/tag/v1.24.0. The specific failure is observed in the `numpy.array(temp)` call in:

https://github.com/terrapower/armi/blob/36fe1bced3b817d6d76e66cf99dd355219993e63/armi/bookkeeping/db/database3.py#L841-L887

**Comment by john-science** [comment]
Oh, I just found we already had a ticket for this:

#246 

So, I will close this ticket as duplicate.
