### ISSUE TITLE
Request for improved parameter lookup speed

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#1039]
https://github.com/terrapower/armi/blob/59b0cad5da848f8dfd1fa65e6cb858f42f964061/armi/reactor/parameters/parameterDefinitions.py#L399-L422

This implementation is painfully slow. In my experience experimenting with this, the "short circuit" option is not ever realized; there are always dozens of represented types. Instead, we look through _all_ of the parameters in the `ParameterDefinitionCollection` (644 of them in my test case) and perform a string comparison (`pd.name == name`) for all 644 of them, just to ensure that `pd.name == name` for exactly one case.

This should be replaced by a hashed lookup. Can we just use a combination of parameter name and represented type as the dictionary key? Looking up a value from a `dict` with `len(dict) == 644` should be orders of magnitude faster than performing `pd.name == name` 644 times.

These string operations cause the uniform mesh conversion to be very slow: it uses `__getitem__` to get parameters from the `sourceBlock` and set them on the `destBlock`. https://github.com/terrapower/armi/blob/59b0cad5da848f8dfd1fa65e6cb858f42f964061/armi/reactor/converters/uniformMesh.py#L994-L1034

If it is a problem to have a given parameter multiply defined on a collection, this is something that we should check for one time, when the `ParameterDefinitionCollection` is initialized, or when a new parameter is added. We shouldn't be re-performing this error check every single time we're trying to get a value for a parameter.

**Comment by mgjarrett** [comment]
Related to #991

**Comment by mgjarrett** [comment]
Okay I was slightly off target on the first assessment. It seems like it is not calls to `b.p[paramName]` that are expensive, but rather `b.p.pDefs[paramName]`.

It's looking like maybe we can get a big performance boost by just pulling out any of these `ParameterDefinitionCollection.__getitem__()` lookups out of nested loops. Right now, it's being performed ~2-3 million times for a single call to the uniform mesh converter on a reactor with 155 assemblies and ~40 blocks per assembly. If we can cut that down to about ~10,000 or fewer that's going to provide a ton of speedup without needing to refactor the `ParameterDefinitionCollection` itself.

**Comment by jakehader** [comment]
@mgjarrett - I think this is important enough to do in the short term. Let's brainstorm tomorrow on how this can be done or I can help. This is probably some of my doing with the uniform mesh refactoring? Not sure how long this was like this though.

**Comment by mgjarrett** [comment]
> @mgjarrett - I think this is important enough to do in the short term. Let's brainstorm tomorrow on how this can be done or I can help. This is probably some of my doing with the uniform mesh refactoring? Not sure how long this was like this though.

The problematic lookup has been there since the big move in 2019, so I don't think this is directly related to the refactoring. The refactor maybe added some lookups to `b.p.pDefs[paramName]` inside of nested loops, but I think that was a pattern that already existed. It's deceptive because `b.p.pDefs[paramName]` looks like it's just doing a normal dictionary lookup, but the implementation of `ParameterDefinitionCollection.__getitem__()` is heavier than a normal dictionary lookup.

**Comment by mgjarrett** [comment]
I wrote a short script to initialize an operator, perform a uniform mesh conversion using `GammaUniformMeshConverter`, and then de-convert the reactor. I profiled this script to identify bottlenecks and then attempted to speed things up by improving the bottlenecks.

Before improvements:
```
Operator initialization took 45.03395962715149 seconds
Uniform mesh conversion took 105.62633275985718 seconds
Uniform mesh deconversion took 10.05649995803833 seconds
```

With improvements:
```
Operator initialization took 28.541070222854614 seconds
Uniform mesh conversion took 20.932044744491577 seconds
Uniform mesh deconversion took 0.01096200942993164 seconds
```

I'll make a PR for this. There's still some features that I think need to be added to the new uniform mesh conversion, so it's not quite done yet, but the speedup looks pretty good so far.

**Comment by jakehader** [comment]
Ooo nice! This is just with moving the param lookups around and making a lighter weight block copying. Do you there there is much more to gain by updating `__getitem__` as well?

**Comment by john-science** [comment]
Also, note that we NEVER need to find all the matches on this line:

> matches = [pd for pd in self if pd.name == name] 

Because as soon as we find a second match, we can terminate the loop:

> if len(matches) != 1:
