### ISSUE TITLE
API Breaking Update needed: Rename setAllBlockLFPs

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1050]
@keckler's comment about `setAllBlockLFPs`:

> I know that it would be an API-breaking change, but the name of this method no longer appears to represent well what the method does. It is no longer focused solely on LFPs.
> 
> Looking around our codebase, it appears that a few of our plugins call to it... :-/

@jhader's reponse:

        I would prefer to keep this the same for now so I don't have to update more stuff that is dependent on it and possibly risk downstream impacts on others. I can make an issue.

_Originally posted by @jakehader in https://github.com/terrapower/armi/pull/1022#discussion_r1055032783_

**Comment by john-science** [comment]
If this needs to happen, cool.  There are 4 downstream repositories that I see will need to be updated.   But they are one-line updates.

I would prefer if this change were it's own ARMI PR though, and not mixed into one of our current, larger PRs.

**Comment by jakehader** [comment]
I'm not sure this needs to happen unless someone gets a couple minutes of down time in the future. The name change is just for semantics.

**Comment by jakehader** [comment]
This isn't needed because #1067 refactored this code.
