### ISSUE TITLE
Unused arguments in `getMassFrac()`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1052]
We have a method on the `Material` class that gets the mass fraction of an isotope/element:
https://github.com/terrapower/armi/blob/main/armi/materials/material.py#L479-L522

Looking at that method, you can see that it accepts a bunch of arguments that are never used. I've noticed that we actually do "use" some of those phantom arguments in our internal plugins. 

I can't see any place where there is a subclassed method that might use those arguments, so I'm wondering if this signature is just out of date or completely in error?

**Comment by john-science** [comment]
Downstream, I see the `normalize` input is used once in one repo. And `expandFissionProducts` is also used once in one repo.

But, as far as I can tell, these two are totally unused:

https://github.com/terrapower/armi/blob/fdce87ba60ee64412225f863f2a9d499ae74d67b/armi/materials/material.py#L482-L483

So, those two are out-of-date.

And, frankly, I think the two subclasses that use these method arguments break the [rule](https://peps.python.org/pep-0020/):

> Special cases aren't special enough to break the rules.
