### ISSUE TITLE
Something in `coverage` seems to be broken.

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#1058]
There are a couple PRs open right now (#1057 and #1056) that seem to have a broken coverage report when running `coveragepy-lcov`. It looks like there was a few recent releases of `coverage` (currently `7.0.3` - https://github.com/nedbat/coveragepy/tags) and there might be some incompatibilities here. The `coverage` that is obtained during `Convert Coverage Results` is `6.5.0` but the `Run Coverage Part 1` seems to be using the latest `7.0.3`. The `6.5.0` seems to be constrained by `click` in the `Run Coverage Part 1` but this is not constrained in the previous job.

I tried to debug this and look through the changes of the `coverage` package but didn't get too far. Attempting to fix in https://github.com/terrapower/armi/pull/1059 by holding the version constant.

**Comment by john-science** [comment]
Fixed with #1059
