### ISSUE TITLE
Broken link to mpi4py in developer docs

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#1075]
The link for mpi4py on [this](https://terrapower.github.io/armi/developer/parallel_coding.html#) page appears to be broken. Perhaps it needs to be updated to point to [this](https://mpi4py.readthedocs.io/en/stable/) page or to the relevant version of mpi4py.

**Comment by john-science** [comment]
That red text isn't really meant to be a link.  It means someone is trying to format the text to stand out from the rest of the paragraph.  It's a way to format code, `like this`.

There a million of those in our docs.

BUT, that's an easy link to add, sure. I can do that. :)

**Comment by john-science** [comment]
@andfranklin Sorry, I clicked the wrong link on the page when you first opened this ticket. 

But you're totally right; I opened a PR [here](https://github.com/terrapower/armi/pull/1105).
