### ISSUE TITLE
Resolve mix of lower and upper case file extensions

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1078]
The following file extensions are defined as upper case:

https://github.com/terrapower/armi/blob/42726110a72606b9a45e64238582a2841e889f2e/armi/physics/neutronics/__init__.py#L138-L142

But there are [test files that are lower case](https://github.com/terrapower/armi/tree/main/armi/nuclearDataIO/tests/fixtures). This mix causes issues on Linux (but not on Windows, where file paths are not case sensitive). One standard should be chosen and implemented to avoid failure/confusion on linux unit testing. 

If we were to edit these defaults to be lower case, would any linux users be affected? @jakehader @john-science

**Comment by john-science** [comment]
Ah, some old-school, niche file extensions were saved as upper case.

By preference, file extensions should be lowercase.  

@jakehader Thoughts?

**Comment by mgjarrett** [comment]
Note that these constants are not necessarily always used as extensions. DIF3D generates files with these exact names, upper case, without an extension. So maybe we need to split into two constants: one for a filename, and one for a file extension? That's kind of complicated but I think we'll find other problems if we change these constants to be lower case.

**Comment by jakehader** [comment]
File extensions as lower case make sense to me, but the files themselves like ISOTXS, COMPXS, PMATRX, etc are always upper case coming from ANL software.

**Comment by opotowsky** [comment]
Oh, yikes. That is complicated then. Hm, I'm leaning towards following Mike's suggestion in that case.

**Comment by john-science** [comment]
Well, Jake throws the monkey wrench into the easy fix, Arrielle.  BUT it's still fixable.  And we just love any problem that has a solution.

**Comment by opotowsky** [comment]
I'll be on this ~soon... It's a medium term priority

**Comment by opotowsky** [comment]
> I'll be on this ~soon... It's a medium term priority

I'll be on this today, it's a today priority 😄
