### ISSUE TITLE
Possibly incorrect calculation of `densityTimesHeatCapacity()`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1092]
We have a method on the base `Material` class called `densityTimesHeatCapacity()`:
https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/material.py#L598-L618

I noticed in that code that we use the `density()` method to do that calculation (i.e. 2D-expanded density). 

Shouldn't `density3()` be used here? This kind of method is presumably meant to be used for TH calculations to get thermal inertia. It doesn't interact with the isotopics or the block height (which might have been already expanded if `inputHeightsConsideredHot=True`), so I don't think 2D density makes sense here. 

Is my thinking correct? The whole 2D/3D thing seems to get more confusing the more I think about it... So other opinions would be helpful here!

Are there any situations in which we would want only the 2D-expanded density to be used in this method?

@albeanth @jakehader @ntouran

**Comment by john-science** [comment]
I found this bug as part of a large slew of changes that need to be make in `Material`.  I am collecting an umbrella ticket today.

Thanks though!  Good eye!

**Comment by albeanth** [comment]
I think the concept of 2D vs 3D density arose due to different treatments between radial and axial expansion/contraction.

This might be getting off topic, but is there any interest in developing a more formal/rigorous treatment for radial expansion? Something akin to the axial expansion changer where we physically change the geometry and update number densities as necessary. The component-linking already exists... Though there are undoubtedly lots of complications to consider.

**Comment by jakehader** [comment]
We could but it's not always clear when there are two solids that interface which component would expand further than the other and then push the other components out. We can handle this with and radian expansion driving component but that would similarly be up to engineering judgement compared to solving for the mechanical contacts. I do like the idea of putting the bones in place and allowing for application based interpretations and implantations.

**Comment by john-science** [comment]
I have opened the above-mentioned umbrella ticket for 2D/3D density issues in our materials [here](https://github.com/terrapower/armi/issues/1097).

**Comment by keckler** [comment]
Closing as this is now superseded by #1097 .
