### ISSUE TITLE
Issues found with 2D Density

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1097]
## Background

In the past, ARMI has had two methods:

* [Material.density()](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/material.py#L357) - a 2D "pseudo" density (necessary for linear expansion)
* [Material.density3()](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/material.py#L403) -  the usual physical density

This unfortunate naming convention lead to confusion.

## Potential Errors

While working on improving the naming convention, I found the following potential bugs:

* [x] `Material.densityTimesHeatCapacity()` [calls pseudo density](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/material.py#L616), but I think it should call physical density.
* [x] `Component.density()` [calls pseudo density](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/reactor/components/component.py#L1162-L1170), but I think it should call physical density.
* [X] ~`Fluid(Material)` [calls pseudo density](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/material.py#L651-L664)~ We define density and pseudodensity as the same for Fluids.
* Several materials only have pseudo density and not physical density, which suggests an error:
    * [x] [air](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/air.py#L62) - Fluid (document it)
    * [x] [concrete.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/concrete.py#L42-L43) - Broken ref, I can't tell if this is wrong.
    * [x] [copper.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/copper.py#L32) - No reference, so I can't tell.
    * [x] [cs.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/cs.py#L30) - Fluid (document it)
    * [x] [custom.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/custom.py#L45) - Correct. density = density3, like for Fluids
    * [x] [~lead.py~](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/lead.py#L45) - probably correct, as is
    * [x] [~leadBismuth.py~](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/leadBismuth.py#L43) - possibly correct, as is
    * [x] [lithium.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/lithium.py#L53) - Fluid (document it)
    * [x] [magnesium.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/magnesium.py#L28) - Does not perfectly match reference.
    * [x] [potassium.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/potassium.py) - Does not perfectly match reference.
    * [x] [~sodium.py~](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/sodium.py#L50) - probably correct, as is
    * [x] [sulfur.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/sulfur.py#L61) - Fluid (document it)
    * [x] [~uThZr.py~](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/uThZr.py#L52) - probably correct, as is
    * [x] [water.py](https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/water.py#L334) - Fluid (document it)

In the course of investigating the above, I expect to find that some of these are _not_ errors, but correct by design. In those cases, I will add some explanatory comments for future generations.

**Comment by dpham-materials** [comment]
The magnesium density is formatted differently and provides a different constant than the reference source. McGonigal's paper provides the linear relationship of liquid magnesium to be D(g/cm3) = 1.834 - 2.647E-4 T(K) with an error of ±0.0014g/cm3. If someone else developed the current correlation, the materials team is happy to chat.

**Comment by john-science** [comment]
> The magnesium density is formatted differently and provides a different constant than the reference source. McGonigal's paper provides the linear relationship of liquid magnesium to be D(g/cm3) = 1.834 - 2.647E-4 T(K) with an error of ±0.0014g/cm3. If someone else developed the current correlation, the materials team is happy to chat.

I will open a PR for this (because of internal deadlines and releases, it may be up to a week).

How do you feel about the Potassium curve in ARMI matching its reference?

https://github.com/terrapower/armi/blob/b5235f0872dafc1428c6209e20ec1365b1c35c92/armi/materials/potassium.py#L31-L40

**Comment by dpham-materials** [comment]
> 


> How do you feel about the Potassium curve in ARMI matching its reference?

The Liquid Potassium curve well matches its reference. I'm not sure if the temperature range is suitable for all ARMI related calculations, but the data source indicates that it should be valid "from the melting point to about 1250°C" if that needs to be extended on the higher end.

**Comment by opotowsky** [comment]
John, do you envision us needing to break API to resolve this problem (as in, this mistake could continue to be mase if we have both `density` and `density3` in ARMI materials), or do we just replace `density3` with pseudo-`density` where necessary and document them better?

**Comment by john-science** [comment]
> John, do you envision us needing to break API to resolve this problem...?

I have changed this ticket to have 17 possible tasks.

My current feeling is that fixing the bugs is more important. So let's do that first.

And, when we have some breathing room, I will go through and open the big PR to fix the `pseudodensity()`/`density3(0` name change. While I _do_ think that is important for better understanding in our userbase, you have me convinced that the bugs take priority (and won't lead to dozens of PRs in downstream projects).

**Comment by jakehader** [comment]
I think that we need to also look at how the linear expansion is being used with setting component temperatures and maybe see if we need a volumetric expansion. I'm not smart enough to know what is right here since the density vs density3 always confused me and still does.

**Comment by opotowsky** [comment]
I spent a good solid chunk of time trying to understand this exact thing on Friday and eventually threw my hands up. I'm hoping that working with @john-science we can figure it out.

**Comment by sombrereau** [comment]
FYI Fluid materials by design are set up so pseudo density IS real density.

**Comment by john-science** [comment]
> I think that we need to also look at how the linear expansion is being used with setting component temperatures and maybe see if we need a volumetric expansion.

Arrielle and I are looking into it.

> the density vs density3 always confused me

**When the workload around here slows down, I will fix this.**  The current `density3()` will be renamed what it really is: `density()`, and the current `density()` will be renamed `pseudodensity()`. And I will update the comments so it is clear that `pseudodensity()` is only to be used for linear expansion, because it is a 2D density.

**Comment by john-science** [comment]
So, we worked through all the items on the list except custom material `density()` method:

https://github.com/terrapower/armi/blob/2a9cd5c0c0f656259d1e3dd48f160c58e3ff5961/armi/materials/custom.py#L45-L53

**Comment by keckler** [comment]
> So, we worked through all the items on the list except custom material `density()` method:
> 
> https://github.com/terrapower/armi/blob/2a9cd5c0c0f656259d1e3dd48f160c58e3ff5961/armi/materials/custom.py#L45-L53
> 
> It's honestly hard to tell what is going on here, since it's "custom". I _think_ this one is wrong in spirit, but I can't think of any way to prove it.

The custom material does not thermally expand. Therefore `density()` and `density3()` should both return the same thing, equal to `self.customDensity`.

Does that make sense?

**Comment by john-science** [comment]
> The custom material does not thermally expand. 

Thanks, @keckler !

Okay, in that case, we finally worked through all 17 items on this list and I am closing this ticket.

Boom!

**Comment by opotowsky** [comment]
Holy wow, good work @john-science !!
