### ISSUE TITLE
Make plugin for MIT's OpenMC

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#11]
We could benefit from a plugin connecting ARMI to MIT's OpenMC code. 

The [pincell example shows ](https://docs.openmc.org/en/stable/examples/pincell.html) that the whole case can be defined and run from the Python API so as long as we can get OpenMC and ARMI running on the same python environment it should be easy to get started.

**Comment by theJollySin** [comment]
This might be an interesting problem for me to solve, to help me learn my way around our tooling.

**Comment by john-science** [comment]
Please note, that we have a skeleton code up for this already: https://github.com/terrapower/armicontrib-openmc

**Comment by john-science** [comment]
There has been a lot of work done to this ticket, over in the other repo:  https://github.com/terrapower/armicontrib-openmc

I am closing this ticket, as there are many tickets open on this work, in the other repo.
