### ISSUE TITLE
Settings should be referenced via their `CONF_XXX` name

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1103]
When we define settings, we almost always go through the trouble of defining its name with a special module-level variable of a particular convention. See, for instance:
https://github.com/terrapower/armi/blob/53ae82e6fb57e1f5698a03ac2b736a494fcdaef4/armi/settings/fwSettings/globalSettings.py#L34-L121

In theory this should make it easy for us to change the variable name and have that permeated throughout the whole repo automatically. However, all around the codebase people seem to grab settings from the `cs` via the setting's _actual_ name. Just a random example:
https://github.com/terrapower/armi/blob/53ae82e6fb57e1f5698a03ac2b736a494fcdaef4/armi/operators/settingsValidation.py#L274-L279

We should instead always be pulling from the `cs` using the `CONF_XXX` variables. This means extra imports, yes, but not doing this has caused bugs in the past and is sure to do so again in the future.

**Comment by john-science** [comment]
My thoughts:

1. This is a good idea.
2. The only reason this problem exists is because someone got lazy each time.
3. This is low priority.
4. This is not API-breaking, and can be done very safely.
5. This can be done piecemeal, and broken into non-heart-breaking chunks.
6. I have seen this before, but was just daunted at HOW OFTEN this problem occurs in ARMI. Chris is 100% right to raise the issue.
7. Thanks, Chris!

**Comment by john-science** [comment]
A quick look at the size and scope of this problem:

* There are 168 module-level `CONF_` variables defined in ARMI, for settings.
* They take place in 10 files:
  * [ ] `armi/physics/fuelCycle/settings.py`
  * [ ] `armi/physics/fuelPerformance/settings.py`
  * [ ] `armi/physics/neutronics/const.py`
  * [ ] `armi/physics/neutronics/crossSectionSettings.py`
  * [ ] `armi/physics/neutronics/fissionProductModel/fissionProductModelSettings.py`
  * [ ] `armi/physics/neutronics/settings.py`
  * [ ] `armi/physics/thermalHydraulics/settings.py`
  * [ ] `armi/settings/fwSettings/databaseSettings.py`
  * [ ] `armi/settings/fwSettings/globalSettings.py`
  * [ ] `armi/settings/fwSettings/reportSettings.py`

**Comment by john-science** [comment]
@bherlethtwo This ticket would be a good place to start at, as the work is maybe a little monotonous, but would be a quick intro to our tool chain and workflows.

**Comment by Till223** [comment]
Hello, I would like to contribute to armi. This seems like a pretty straight forward issue that I could get started on. Would that be alright?

**Comment by jakehader** [comment]
> Hello, I would like to contribute to armi. This seems like a pretty straight forward issue that I could get started on. Would that be alright?

Hi @Till223, thank you! I think that we would definitely appreciate the support on this ticket / issue and it would help clean up the code and move away from using strings for setting accessing within the code base. 

@john-science, any notes to add here? Is there any good way to "test" for this or enforce this that we could add or is just a style guide in the developer notes?

**Comment by john-science** [comment]
> I would like to contribute to armi. This seems like a pretty straight forward issue that I could get started on. Would that be alright?

This would be a great place to start!

Just take one of the bullet points [here](https://github.com/terrapower/armi/issues/1103#issuecomment-1396260153) and go to the file. Find all the `CONF_` at the top, and then look for all instances of that string in ARMI, and replace it with the `CONF_` variable. This will probably mean adding imports to other files, etc...

I will be your point-of-contact on this.  Probably, since it is your first time contributing to ARMI, most of the work will be getting your [environment setup and installed](https://terrapower.github.io/armi/installation.html), and learning our [GitHub workflows](https://terrapower.github.io/armi/developer/standards_and_practices.html) (opening a PR, etc).  Don't worry if your PR has a lot of back-and-forth chatter and requested updates, it happens to EVERYONE. People are just trying to be careful and thorough.

Thanks!

**Comment by john-science** [comment]
> Is there any good way to "test" for this or enforce this that we could add or is just a style guide in the developer notes?

There isn't any standard practice for ensure tight use of string constants, no.  But once we get the items in this [bullet list](https://github.com/terrapower/armi/issues/1103#issuecomment-1396260153) solved, we will probably add a note in the PR docs or the Dev docs.

**Comment by Till223** [comment]
Alright, I will start working on this then, thanks for all the pointers! If I have any trouble with the setup I'll message you directly @john-science 

> Is there any good way to "test" for this or enforce this that we could add or is just a style guide in the developer notes?
Couldn't you use a github action to check for this?

**Comment by jakehader** [comment]
Maybe a regex check could be used in the code base as a high level unit test within an ARMI application? Thanks @john-science and @Till223!

**Comment by mgjarrett** [comment]
I fully acknowledge that it is more appropriate to use the defined constants than the literal strings throughout the codebase. I've been bitten by bugs from typos in the setting name. And of course, it's possible to miss some instances of the string when the name of a setting is updated. So there are plenty of benefits, as stated above. So, yes, we should absolutely do this.

But I do want to give voice to the other side for a minute, just to put it out there. Many ARMI developers are also ARMI users. ARMI users usually know the string names of all the settings that they need to use in whatever code they're developing. Nobody knows off the top of their head the `CONF_XXX` constant name for each setting. So whenever you're developing code, you'd have to constantly cross-reference the files where the `CONF_XXX` are defined to make sure you're using the one you intend. And if you're working with a lot of settings concurrently, there is potential for mixing up which setting is which. This could lead to a bug, and once it's in there it would be arguably harder to identify than a typo in a string. You would have to infer that the person who wrote the code intended to use a different setting.

Again, I still think it's the right direction, but I would contend that it's not a clear, no-brainer decision.

**Comment by keckler** [comment]
@mgjarrett I definitely know what you're referring to with your comment. I think that issue typically might arise when there is a discrepancy between the string name and the CONF name. 

Like a setting `nCycles` should be directly translated to `CONF_N_CYCLES`. But sometimes people make the CONF name something other than the direct translation, for instance they might do `CONF_CYCLES`.

I think if we were rigorous about translating the setting string names into those CONF variables, there would be no (or less) confusion.

**Comment by john-science** [comment]
@mgjarrett I mean, you might not know the `CONF_` variable name off the top of your head.  But the codebase is a decade old, we have had the time to go back and do some search/replace to make things easier.

I think the only real concern I have about implementing the above is we might accidentally create some import loops, by adding so many `from armi.whatever import CONF_X` at the top of a ton of files.  We'll see how that goes, I think I already spy one I will have to disentangle.

**Comment by albeanth** [comment]
@mgjarrett quick shameless plug for vscode here. If you use the `CONF_XYZ` approach, you can hover you cursor over the name and vscode will tell you the string it correlates to. While its displayed, you can even copy-paste the string as you need. And you can alt-click to jump straight to the definition in the right settings file. It's pretty nifty.
![image](https://user-images.githubusercontent.com/18561046/218205119-0c41d129-4fc8-486f-ab04-828c965e1c2d.png)

**Comment by onufer** [comment]
now that these are more widely used we need to update our internal repos to use confs also. Before it was 95+% of the time you would grep for the string and it would find all instances. . now its 50/50 depending on if its in the framework or not

**Comment by john-science** [comment]
Thanks @Till223
