### ISSUE TITLE
Issue Installing armi[grids]

### ISSUE THREAD

**Issue by bherlethtwo** [terrapower/armi#1110]
While attempting to install `armi[grids]`, the install failed in `msvc9compiler.py` with an error indicating that it could not find `vcvarsall.bat`.

I am using VS 2022 Community Edition and Python version 3.10.9. `Vcvarsall.bat` is in the directory `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build`. I looked on the web and found a different version of `msvc9compiler.py` (it comes with the python installed), and the install failed with a different warning. I noticed the install failed to install `wxpython` version 4.1.0 but version 4.2.0 installs correctly. I updated setup.py(s) to allow the use of version 4.2.0 and the install worked.  However, I don't know how to test it.

**Comment by jakehader** [comment]
You may run unit tests in the root ARMI directory by running `pytest -n 4 .` which will discover all unit tests recursively and then run with 4 processes. 

It's not clear to me why visual studio is a dependency of ARMI. Do you have the `wheel` package installed before running the installation process? It could be that without this it is trying to compile some dependency rather that just installing the wheel directly. Try to see if you can `pip install wheel` on a separate virtual environment and then go through the ARMI setup. If that doesn't work then we can try to see what is going on. 

@john-science might have better intuition on this issue though.

**Comment by bherlethtwo** [comment]
The issue is wxpython version 4.1.0. If you type 'pip install wxypthon==4.1.0', it fails, but version 4.2.0 installs correctly.   See https://www.wxpython.org/ version 4.2.0 release notes.

**Comment by jakehader** [comment]
Okay thanks we will take a look!

**Comment by john-science** [comment]
Some thoughts, in no particular order:

* I don't use Visual Studio; have you tried running ARMI from the command line, without it?
* Have you tried with Python 3.9?  It's just a thought, ARMI should work with 3.10, but most of us are using 3.9 still.  (This may be a red herring.)
* We have [fixed our version of `wxpython` to be less than 4.2](https://github.com/terrapower/armi/pull/953) on purpose.  Newer versions of that library break some of our other dependencies.

If I had to guess, this is a Visual Studio problem.  That's where all your errors are coming from.

**Comment by bherlethtwo** [comment]
1. ARMI runs from the command line. It is the pip install armi[grids] that fails.
2. I tried Python 3.11 (which didn't work) and then 3.10. I haven't tried 3.9  I can install it.

**Comment by bherlethtwo** [comment]
I've installed python version 3.9.13. If someone could give me a one paragraph description of your setup; I'd appreciate it. What IDE do you use? What shell? Do you always use pip as the install manager (or something else)? Did you install python globally or per user? What environment variables (if any), do you use? Any other install related tricks up you sleeve? 
Thanks

**Comment by keckler** [comment]
Are you doing this installation from within a python virtual environment?

**Comment by bherlethtwo** [comment]
I am trying to execute the steps described in the installation document, but with python 3.9.13 installed instead of 3.10.16.
$ python -m venv armi-venv
$ armi-venv\Scripts\activate.bat
$ source armi-venv/bin/activate
(armi-venv) $ git clone https://github.com/terrapower/armi
etc.

**Comment by john-science** [comment]
My process (which I have probably done 1,000 times on dozens of different machines):

* I do the same setup on Windows as on Linux, so that shouldn't matter.
* I typically use Python 3.9.x, though our unit tests on GitHub all run in 3.7 to 3.10.  Still, I'd say 3.9 is the best tested.
* I do the same `python -m venv venv` command you do.
* `git clone armi` 
* `cd armi`
* `pip install -e .`

Now, I haven't tried to `pip install -e .[grids]` lately, I can try that. For sure.

But, just to understand the issue, can you get ARMI installed without the `[grids]`?

**Comment by bherlethtwo** [comment]
The command ‘pip install armi[grids]’ worked on python version 3.9.13.

**Comment by john-science** [comment]
> The command ‘pip install armi[grids]’ worked on python version 3.9.13.

Oh! Then our codebase might have a whole for Python 3.10 that no one else has found before!

Okay, THAT is small and bite-sized enough I can take that.

**Comment by jakehader** [comment]
@john-science is this fixed now?

**Comment by john-science** [comment]
Well, since this ticket came out we moved to `wxpython==4.2.1`, and then I forgot to close this ticket.

I was able to successfully run `pip install -e .[grids]` on Python 3.9 on Windows and Linux with the updated version of `wxpython`.  So I'm closing this ticket.
