### ISSUE TITLE
`TD_frac` for `UraniumOxide` and `MOX` doesn't do anything

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1112]
The `TD_frac` material modification doesn't do anything for `MOX` or `UraniumOxide`. To confirm this, try running the following:

```python
"""
Tests for Uranium Oxide.
"""

import unittest

from armi.materials.uraniumOxide import UO2
from armi.materials.tests.test_materials import _Material_Test


class UraniumOxide_TestCase(_Material_Test, unittest.TestCase):
    MAT_CLASS = UO2

    def setUp(self):
        _Material_Test.setUp(self)

    def test_applyInputParams(self):
        self.UO2_TD = UO2()
        original = self.UO2_TD.density(500)
        self.UO2_TD.applyInputParams(TD_frac=0.1)
        new = self.UO2_TD.density(500)
        ratio = new / original
        self.assertEqual(0.1, self.UO2_TD.getTD())
        self.assertEqual(ratio, 0.1)


if __name__ == "__main__":
    unittest.main()
```

You'll see that the test fails. This is a big problem!

This could be a problem for other material classes as well. The only other one I've looked at is B4C, which appears to be fine.

**Comment by keckler** [comment]
I am working on a fix.

**Comment by john-science** [comment]
Tests for `MOX`:

https://github.com/terrapower/armi/blob/e5aa9d2e37a3cd99abeccac46f22946676cda496/armi/materials/tests/test_materials.py#L194-L213

Tests for `UraniumOxide`:

https://github.com/terrapower/armi/blob/e5aa9d2e37a3cd99abeccac46f22946676cda496/armi/materials/tests/test_materials.py#L432

**Comment by john-science** [comment]
The `UraniumOxide` module has [86% code coverage](https://coveralls.io/builds/56165008/source?filename=armi%2Fmaterials%2FuraniumOxide.py).

The `MOX` modules has [63% code coverage](https://coveralls.io/builds/56165008/source?filename=armi%2Fmaterials%2Fmox.py), though that could be better.

**Comment by keckler** [comment]
Ah, okay, that is right, I completely forgot those tests are hidden in there. Thanks for pointing that out!

I do believe, though, that the problem with `TD_frac` that I point out is still an issue. Are you able to confirm/deny this?

**Comment by john-science** [comment]
To the best of my knowledge `theoreticalDensityFrac` is entirely unused in ARMI, except for one use case, in `B4C`:

https://github.com/terrapower/armi/blob/e5aa9d2e37a3cd99abeccac46f22946676cda496/armi/materials/b4c.py#L168-L178

I think it's also possible this is entirely unused downstream plugins/repos.
