### ISSUE TITLE
Switch to PEP8 naming conventions (snake_case vs. camelCase)?

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#112]
I'm wondering if at this point it would be valuable to switch to [PEP8 naming conventions](https://www.python.org/dev/peps/pep-0008/). When the project started in 2009 PEP8 was a thing but we just didn't start with it for some reason. Then we stuck with the "consistency is more important than PEP8 recommendations" thing for a long time. We use the `black` code formatter for whitespace issues, but still have a big variance from PEP8 with the `camelCase` methods and variables. Now as we are trying to integrate with more projects, maybe it's an appropriate time to make the big switch. 

Perhaps we could fire up a tool like https://github.com/abarker/camel-snake-pep8 to see how hard it would be.

**Comment by youngmit** [comment]
snake_case is definitely better, but the conversion is going to cost us! It would be a pretty big breaking change, especially from code that uses ARMI. So if we do choose to do this, sooner rather than later would be important. We should probably tool this as much as possible. We should still be pretty careful here, as we still have some weird `CONF_` variable names from when we did the Setting migration. I'm thinking we make something that walks the AST, renames things, maintaining a set of renames as it goes, then regurgitates those and their locations as a report that a human can go back through to make sure that acronyms and such didnt get miss-handled

**Comment by onufer** [comment]
I agree with Mitch. I defiantly prefer snake_case in general, but there are concerns about breaking code dependent on ARMI.

I am also a little concerned that variables will take more characters of text. Even right now, i feel a tension between makingDescriptiveVariableNames, and thoseVariableNamesCanSometimesGetTooLong and once black does formatting it is less readable..

**Comment by ntouran** [comment]
Part of the benefit of snake_case is that it will dissuade of from making ridiculously long names, preferring instead refactors that make such crazy names less likely. 

@youngmit  the tool I linked above uses the [Rope](https://github.com/python-rope/rope) refactoring library, probably similar to what you're suggesting.

**Comment by jakehader** [comment]
@ntouran, to be clear - are you talking about just converting variable names to `snake_case` or would you like to see functions/methods also be converted too? It seems like the convection in PEP8 refers using `snake_case` for functions, methods, and variables.

Example:
```
def instantiate_my_class():
    return MyClass()

class MyClass(self):

     def __init__(self):
          self.var_1 = 1
          self._var_2 = 2
    
     def print_var1(self):
         print(self.var_1)

     def print_var2(self):
         print(self._var_2)
```

**Comment by ntouran** [comment]
I'm talking about attribute, variable, function, and method names (as recommended in PEP8).

**Comment by ntouran** [comment]
So upon further discussion we have decided at this time that changing everything to `snake_case` is probably not worth the trouble. 

* The Python standard library is quite mixed and no one revolts over it
* Our potential users are specialized enough that this convention is unlikely to make or break the choice to use ARMI
* Plugin devs are welcome to use whatever style they want, of course
* PEP8 explicitly says to *not* switch things over simply to comply with PEP8. 

So we'll just not do it for now. Feel free to add additional thoughts and complaints below, at least for now.
