### ISSUE TITLE
Are all of our unit tests running?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1133]
It is possible that a unit test exits half way through, and the second half of the test never gets run.

For instance, this test was exiting early, and so we weren't actually running the next 20 lines of hypothetical test code:

https://github.com/terrapower/armi/blob/8b6ea1abcfe6ea4587ab0a2622f4d7c03e214e83/armi/reactor/tests/test_components.py#L302-L306

So, how can we test if our unit tests are actually doing anything?  Easy!

We should run code coverage against ARMI, and change the coverage so it COVERS THE UNIT TESTS.  Then just hand-check any test file that isn't 100%, to see what unit tests are exiting earlier than we thought.

Just change this one line:

https://github.com/terrapower/armi/blob/8b6ea1abcfe6ea4587ab0a2622f4d7c03e214e83/.coveragerc#L16-L20

~**MAYBE** we could even have a GitHub Action Jenkins job that ensure if we do this that each test file has 100% code coverage. Though that could get a bit iffy.~

**Comment by ntouran** [comment]
I think we should manually run coverage on the unit tests occasionally to see if this is a big issue, and make issues to update tests when we see problematic ones. 

But I think that we should continue to exclude tests in our main coverage metrics, as that can artificially inflate the total coverage (because at least most tests run during testing).

**Comment by jakehader** [comment]
I've run the framework tests locally in recent PRs and didn't see any differences in terms of passing using `pytest` but didn't check if the automated version on GitHub captures the same number of tests.

**Comment by john-science** [comment]
I am running a test for this locally.

Though [Tony and I](https://github.com/terrapower/armi/pull/1163#discussion_r1100336212) found one test today that exited early and didn't run at all.  So, they are out there.

**Comment by john-science** [comment]
I note that we have a couple NucleardataIO unit tests that never run because they are incomplete or broken (or our code is broken?):

https://github.com/terrapower/armi/blob/40519daa1d9b817644c0e01c70baa658d6d539ae/armi/nuclearDataIO/cccc/tests/test_dlayxs.py#L311-L314

https://github.com/terrapower/armi/blob/40519daa1d9b817644c0e01c70baa658d6d539ae/armi/nuclearDataIO/cccc/tests/test_dlayxs.py#L939-L942
