### ISSUE TITLE
The `single` log messages should store a hash

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1135]
Right now, you can ask `runLog.py` to never repeat a particular log message by using `single=True`:

https://github.com/terrapower/armi/blob/8b6ea1abcfe6ea4587ab0a2622f4d7c03e214e83/armi/runLog.py#L445-L453

That's great. But testing for GIANT, long log messages can be slow, particularly when people put `single=True` all throughout their code. That's why we had to add the extra `label` feature.

We should just hash the message and skip the label. Pick a _fast_ hash algorithm, and don't worry about cryptographic security.

**Comment by drewj-usnctech** [comment]
Would [builtin `hash`](https://docs.python.org/3.7/library/functions.html#hash) be sufficient? Just `hash(msg)`?

**Comment by john-science** [comment]
> Would [builtin `hash`](https://docs.python.org/3.7/library/functions.html#hash) be sufficient? Just `hash(msg)`?

That would definitely work.

(I was just wondering if there was anything faster.  For instance, I know the SIMS use something like the [FNV hash](https://github.com/Cilyan/stblc/blob/master/STBLWriter.cs#L58) for string comparison. And [murmer3](https://stackoverflow.com/a/5400389/1287593) is fast I'm told, but also... I don't want another dependency. It's not important.)
