### ISSUE TITLE
Make the test reactor reliably use material definitions that ship with ARMI

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#114]
There is no specification of the material namespace search order (`materialNamespaceOrder`) in the settings file for the test reactor, upon which lots of unit testing is performed. This leaves the actual state of that reactor sensitive to which plugins are active, potentially using plugin-provided material definitions. We should update the settings to explicitly request `armi.materials` so that the various physical properties can be relied upon in peoples' tests.

**Comment by ntouran** [comment]
We should be able to update the test input blueprints to point to `armi.materials.HT9` explicitly to override any app's namespace order.

**Comment by ntouran** [comment]
Actually we aren't quite ready to do this because some external app tests require the app's "fancier" versions of some materials (with more material properties, etc.). The feature in #192 gives app tests the option to load app-specific test inputs that can be more specific.
