### ISSUE TITLE
Hardcoded interface disabling in snapshots.py

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1142]
PR #1141 highlighted something that I thought was strange. I understand that it makes sense to skip interfaces when doing different run types, like snapshots. But at the same time, it feels wrong to me to have this hardcoded into the operator. 

https://github.com/terrapower/armi/blob/1566331d88d1c2a3ad9a408203f74084da264513/armi/operators/snapshots.py#L31-L33

Rather, I think it makes some sense to make this a user setting, something like `interfacesToDisableInSnpshots`. We could have the hardcoded interfaces have default values that match what's hard coded now for backwards compatability. 

... 

The proposed setting name could be shortened up if we did settings organization like discussion #1083 brings up 😁 
We could do something like:
```yaml
armi app run type:
  run type: snapshots
  interfacesToDisable: _a list of interface names_
```
where `interfacesToDisable` is only valid when under `run type: snapshots`; otherwise an error is thrown.

**Comment by keckler** [comment]
I always like making this like this configurable, but good luck 😆

**Comment by onufer** [comment]
In general, configurable is nice. In this case snapshots want to run "everything that doesn't change state of reactor or advance time" so it skips shuffle and depletion. we haven't found anything else needed to skip since making the operator. if you want TH off just turn it off in your run. Depletion and shuffle are different because as soon as you do either of those you are not looking at the same snapshot.

**Comment by john-science** [comment]
Looking at the code, it appears this hasn't changed in 4 years.

So, in that light, it doesn't seem like a setting people would use very often.

Why not just refactor the code so it is possible for people to adjust the list?  Some things will always have to be code, not everything can be a setting.

How often do you expect use the new setting?

**Comment by onufer** [comment]
if we want to do anything, making a class attribute called

snapshotsIDisabledInterfaces = ["fuelHandler", "optimize", "depletion"]

is probably the right path.
