### ISSUE TITLE
Unused getLifeMetal methods?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1147]
There appear to be two totally unused, strangely-named `Material` methods.  I'm wondering if we can just delete them:

https://github.com/terrapower/armi/blob/da54ff1962c3b7dc01fb7733797b6657b91f2d6b/armi/materials/material.py#L476-L480

https://github.com/terrapower/armi/blob/da54ff1962c3b7dc01fb7733797b6657b91f2d6b/armi/materials/material.py#L491-L495

These are not used downstream in any repo or project I can find.  They aren't well documented or even tested.

Are they removable?

**Comment by keckler** [comment]
LIFE-metal is a fuel performance code developed by ANL. I expect that it was at one point used at TP.

**Comment by john-science** [comment]
@ntouran @jakehader I find no usage of this in any repo I have access to.  As such, since this methods are undocumented and untested, I would like to remove them from the base `Material` class.

If there IS some use of these two methods, speak now.  :)

**Comment by jakehader** [comment]
Please remove!
