### ISSUE TITLE
Guide for First-Time ARMI Contributors

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1180]
@jasonbmeng recently mentioned that he is looking to make his first PR into ARMI, but didn't find a "quick start guide for first-time ARMI contributors", or something similar. I think this is a _really_ good idea. 

I also, don't think it will be hard to do because we have much of this stuff already documented in our: [PR Template](https://github.com/terrapower/armi/blob/05765608596bc907a88a6033cf5d4640f610ab7d/.github/pull_request_template.md), [Standards and Practices Docs](https://terrapower.github.io/armi/developer/standards_and_practices.html), and our [Tooling and Infrastructure Docs](https://terrapower.github.io/armi/developer/tooling.html).  BUT, there should be a clear, easy-to-find, guide for first-time ARMI contributors to get up and running.

Here are my ideas for important topics:

* You must use the PR process
* You will need a personal GitHub.com account.
  * Maybe setting up your `.git-credentials` file
* You need to fork the repository to open a PR
* HOW to fork the repo
* HOW to open your first PR
* Signing the Contributor License Agreement
* What we expect of the PR

**Comment by john-science** [comment]
@drewj-usnctech @Till223 @jasonbmeng @bherlethtwo 

You guys would have the best boots-on-the-ground view of this.  What else do YOU think should go in the "First-time ARMI Contributors Guide"?

**Comment by bherlethtwo** [comment]
The documentation indicates you should use Python 3.7 and above but and I don’t think it works with 3.10 or 3.11.

**Comment by john-science** [comment]
> The documentation indicates you should use Python 3.7 and above but and I don’t think it works with 3.10 or 3.11.

That's an interesting point.  Right now, we ALMOST have full support for [Python 3.11](https://github.com/terrapower/armi/issues/957). The last hold-out is the h5py library.  And, after working with that team, we have that working, but only in Linux, not Windows or MacOS.  So... it's close.

But worth call out.  Thanks!

**Comment by drewj-usnctech** [comment]
The list you have looks great. I would also recommend linking to the contributor license agreement. I can't find the link to where that's hosted, but a while back it wasn't hosted in the repository but in someone's personal github account. Is that still correct?

**Comment by Till223** [comment]
I think "Choosing a good first issue" would also make sense as a topic. Maybe with a link to the [good first issues](https://github.com/terrapower/armi/labels/good%20first%20issue) and where to ask for help when you have trouble finding an issue.

**Comment by john-science** [comment]
> I think "Choosing a good first issue" would also make sense as a topic. Maybe with a link to the [good first issues](https://github.com/terrapower/armi/labels/good%20first%20issue)

Good point! To that end I just put a "Good First Issues" badge (button) right at the top of our README file.  It should be very visible now. 

But good point!

**Comment by ntouran** [comment]
We do have a contributors guide in a standard location here that might be a good place to expand and point people to: https://github.com/terrapower/armi/blob/main/CONTRIBUTING.md

**Comment by john-science** [comment]
The benefit of a lot of time makes me think this ticket should mostly just beef up the `CONTRIBUTING.md` file, and/or maybe copy/paste that file into the docs.
