### ISSUE TITLE
change internal child container from list to locator/child mapping

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#119]
### Currently
ArmiObject composite model children are a simple list. Order is usually not important.

### Problem
We need a good way to get certain children by locators, but `obj.childrenByLocator` can get out of date and be wrong and be hard to synchronize

### Proposal 
@youngmit suggests making the `childrenByLocator` mapping *the* container, rather than the list. I really like this idea. 

For objects that don't have grids, we'll have to come up with some kind of locators that make sense (e.g. blocks with amorphous blobs of components), or just put amorphous grids on them with sequential locators or something.

**Comment by youngmit** [comment]
the actual representation of the children within a Composite is an implementation detail of the Composite class. if it wants to have a mapping keyed on location for stuff in a grid *and* a list for everything else, so be it! Get children would just need to honor both containers. Core currently does this to support the SFP/CFP.
