### ISSUE TITLE
"Property Data was Modified from the Source?"

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1192]
During a run, ARMI spits out a table into the stdout that looks like this:
![image](https://user-images.githubusercontent.com/21959600/220784265-8d8552ca-8e6b-420f-a293-fad31f8edaa9.png)

I don't usually think about this, but it caught my eye because all of the columns in the table say `False`, but I am FOR SURE modifying the source data in my current run.

So I dug into this a bit deeper. This is where that table is generated:
https://github.com/terrapower/armi/blob/3e47ec6e6359870866502c9356747cf1da4f9515/armi/reactor/blueprints/reactorBlueprint.py#L256-L272

It looks like the value is _always_ set to `False`. So really the output there is a lie.

So do we want to fix this, or just get rid of it completely?

**Comment by john-science** [comment]
Well, you're right, the current situation is no good.  It seems like the only two options are:

* Remove that column from the table.
* Get that column working, so it's correct.

In my experience, no one is really using that table output very heavily (notice how long this bug has gone unnoticed).  So the easy solution is definitely to delete the column that has clearly been unused for... what looks like 4 years minimum, in the commit history.

We could also fix the column, if there is suddenly someone who would USE it.  (Though, again, I feel confident no one has used it in at least four years.)

**Comment by keckler** [comment]
I would support removing that column. I'm not even sure how one would test for such a thing. And, to me, listing the source of the material is good enough.

**Comment by jakehader** [comment]
Note that this was being used but was changed here: https://github.com/terrapower/armi/commit/4699c867e6b6fb7c1308a879e03c241f1d946b75#diff-35981b27fc7626938830b47d5bc039adb28ee4eff283e7a9059a96f65238c132R259

The goal of this feature was to implement some way for the user or reviewer to know (a) what library base the material data is coming from and (b) if something was edited on consuming the material library data prior to it being used by an application.

Maybe the original implementation wasn't the best, but there was some utility here.

**Comment by john-science** [comment]
Our group opinion that this column should just be removed.
