### ISSUE TITLE
Why do Materials have a name attribute?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1196]
Every material in ARMI has a class-level attribute `name` string:

https://github.com/terrapower/armi/blob/3e47ec6e6359870866502c9356747cf1da4f9515/armi/materials/lithium.py#L27-L28

They are nearly universally the same as the class name, though a couple differ in whitespace:

https://github.com/terrapower/armi/blob/3e47ec6e6359870866502c9356747cf1da4f9515/armi/materials/uraniumOxide.py#L41-L42

When referencing the material in a blueprint file or something, you must use the class name.  Recently someone found this out the hard way, tried to use the `name` string somewhere and got an error.  Which begs the question: why are we duplicating this information? Can we just remove this string?

If people _really_ want a pretty-print version of the material, we already have a `Material.getName()` method that can just call `self.__class__.__name__` inside that method. (We can pretty-print it.) I still can't see a need for this duplicate attribute.

**Comment by john-science** [comment]
@opotowsky @alexhjames @jakehader  Does anyone know why this field exists?

Thanks!

**Comment by opotowsky** [comment]
I do not know the history but agree it can likely be removed with little to no impact to anyone's work.

**Comment by alexhjames** [comment]
I don't think we were the reason that it exists but I can say that Oxbow uses the `material.getName()` function so it knows what to call the material for input file writing. I'd be fine if the name attribute got removed and `getName()` got rerouted to return the class name.

**Comment by john-science** [comment]
> I don't think we were the reason that it exists but I can say that Oxbow uses the `material.getName()` function so it knows what to call the material for input file writing. I'd be fine if the name attribute got removed and `getName()` got rerouted to return the class name.

I could also just replace `getName()` to use the `mat.__class__.__name__`. Maybe pretty it up some.

**Comment by alexhjames** [comment]
@john-science That's exactly what I was thinking!

**Comment by john-science** [comment]
Okay, there appears one use-case for these names.

Broadly: people want to modify materials for different parts of the reactor. And they change the name to make this kosher.

So, I think a good backwards compatible step would be:

* Move `class.name` to `self._name`, and set it equal to `self.__class__.__name__` in the constructor.
* Add setters and getters to mirror the old `self.name` read/write access.
* Update all of our materials (for 99% of them, this will just mean removing the `name = XXX` declaration).

This should leave `getName()` unaffected, and be backwards compatible.

**Comment by john-science** [comment]
@sombrereau @opotowsky I would like to do this one next week. I mention it because it involves making a minor tweak to downstream materials in other project. Though, mostly, it will just main removing this one line:

https://github.com/terrapower/armi/blob/20be875219ce99d4776d7282be95d263f16d69e4/armi/materials/copper.py#L24

I believe the downstream codes will work mostly even without any changes, assuming the `name` variable matches the class name.

Thoughts?

**Comment by opotowsky** [comment]
I think @alexhjames went through and made sure the name variable matched the class name since they kept running into issues with it. 

So that shouldn't be a problem. As long as `getName` is preserved we should be good! Holler if you want someone to run internal tests on the update.
