### ISSUE TITLE
Type hint conflicts with docstring in `densityTools`

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#1198]
Type hint indicates that `massFrac` is a `dict`, but the doc string says it is a `float`. The usage in the function seems consistent with a float.

https://github.com/terrapower/armi/blob/3e47ec6e6359870866502c9356747cf1da4f9515/armi/utils/densityTools.py#L316-L336

**Comment by john-science** [comment]
We actually have a unit test for this:

https://github.com/terrapower/armi/blob/3e47ec6e6359870866502c9356747cf1da4f9515/armi/utils/tests/test_densityTools.py#L71-L84

So, you are correct. It appears the confusion was that the RETURN TYPE is a dict, but yes the input `massFrac` is a float.
