### ISSUE TITLE
Settings validation resolution appears to not work when submitted via cmd line

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#1221]
validation resolution such as
![image](https://user-images.githubusercontent.com/50242044/227262771-56d55621-11f8-4593-b5a6-260fe9fe3e3c.png)

doesnt seem to work in cmd line  even if you say `yes`
![image](https://user-images.githubusercontent.com/50242044/227263002-e51b94ff-0e0f-43af-9757-f356eea327a2.png)

**Comment by onufer** [comment]
yep correct. when you do it with the gui, it actually changes the settings files, saves new ones, and submits those, so that should be the actual behavior

**Comment by john-science** [comment]
Are we at all worried that we are over-writing the original setting file, and that is unrecoverable? 

For instance, if the settings file is on a share folder, and multiple people are using it for different purposes, then this gives someone the power to change the settings file out from underneath another user.

Just asking.

**Comment by onufer** [comment]
there could be some worry there. but the message warns you that this is what it will do. we could additionally rename the old file and write a new one.
