### ISSUE TITLE
Update logic in block.getNumPins

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1222]
If a block has `dummypin` components, `getNumPins` will ignore those and return the wrong number of pins. This method should be updated to account for more types of pins.

**Comment by john-science** [comment]
Sorry, I'm having trouble finding the string "dummypin" in ARMI.  I'm not trying to be obtuse.  Could you link an example line of code?

**Comment by opotowsky** [comment]
the issue isn't really an ARMI problem. It's that a `dummypin` component receives neither the `dummy` nor the `pin` flags. If it had the `pin` flag then the code would work fine. This can be resolved within the blueprints file itself by renaming to `dummy pin`.

If we think this is an issue that could affect others, we could add a conversion: [example here](https://github.com/terrapower/armi/blob/3e95bedf3dcd3b7251c26386fccaa323597074f7/armi/reactor/flags.py#L342) [`re.compile(r"\bINNERDUCT\b"): Flags.INNER | Flags.DUCT,`]

**Comment by opotowsky** [comment]
@dlangewisch didn't you discover this problem? It will be fixed via the above mentioned blueprints update.

**Comment by opotowsky** [comment]
> If we think this is an issue that could affect others, we could add a conversion: [example here](https://github.com/terrapower/armi/blob/3e95bedf3dcd3b7251c26386fccaa323597074f7/armi/reactor/flags.py#L342) [`re.compile(r"\bINNERDUCT\b"): Flags.INNER | Flags.DUCT,`]

@john-science I am happy to make this as a small PR instead since it affects more than one test. What do you think?

**Comment by opotowsky** [comment]
just gonna fix the component name in the tests. Closing!
