### ISSUE TITLE
TH inlet/outlet parameters should have different `ParamLocation`

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#1233]
`THcoolantInletT` and `THcoolantOutletT` are defined as `ParamLocation.AVERAGE`, but they should be `ParamLocation.BOTTOM` and `ParamLocation.TOP`, respectively.  Also, `THhotChannelOutletT` should be `TOP`.

https://github.com/terrapower/armi/blob/c8a40c76d9da31e3f8322a51eb52d3864a3f68a6/armi/physics/thermalHydraulics/parameters.py#L208-L220

Can anybody think of a reason these should be `ParamLocation.AVERAGE` instead of top/bottom?

**Comment by john-science** [comment]
@andfranklin Do you agree with this?

**Comment by andfranklin** [comment]
I agree with that. I want to ping @dlangewisch to ensure these changes won't have unintended consequences.

**Comment by dlangewisch** [comment]
I'm not aware of any potential issues this might cause, but then again I'm not familiar with how parameter locations are utilized in the overall armi/nala framework so I could be overlooking something.

**Comment by john-science** [comment]
Thanks, all!

I'll run all the downstream unit tests before merging the change into ARMI.
