### ISSUE TITLE
Application version not stored in the database

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#1234]
It would be ideal if there was a placeholder in the database to store the version of the ARMI application that was run. See:
https://github.com/terrapower/armi/blob/9de4be8b706a3b4ef96d78b57632fb3130bf3114/armi/bookkeeping/db/database3.py#L215

**Comment by john-science** [comment]
I believe it will be hard to get ARMI to know about the Application (which is outside it).  But an ARMI Application could certainly call an ARMI function to write the Application version/hash into the DB.  That seems fine.

ACTUALLY

We already finished this ticket in another way. Have you seen [this](https://github.com/terrapower/armi/issues/1095)?

**Comment by john-science** [comment]
Wait, are the settings not saved to the DB?

**Comment by jakehader** [comment]
They are saved to the database, but at the surface it is difficult to assess which version of the code was used to generate the database. I saw that you added an option in the settings to store this, but it would be nice if the database itself stored this data directly. The reason this is coming up is that someone passes a database to someone else they don't immediately know the version. Additionally, when we run integration tests it would be nice to know when the last rebaselined version was generated.

**Comment by drewj-usnctech** [comment]
If version data is provided as settings (like discussed in #1267), then this is done automatically, right?

**Comment by john-science** [comment]
> If version data is provided as settings (like discussed in #1267), then this is done automatically, right?

Yup!

The tickets are heavily intertwined.

**Comment by jakehader** [comment]
I think that this ticket might still be open (or at least from my perspective it should be). I think have version in the settings file adds something but it's not tied to the same release version number (or forced to) based on some git history or setup.py version. Basically for database migrations we still need the version number and maybe this is just opening up the settings stored in the DB and getting the version string from there but that seems fragile.

Thoughts @opotowsky and @john-science?

**Comment by opotowsky** [comment]
Presume I'm clueless ;-)

What's the difference between opening the db to get the version via `h5db.attrs["version"]` and getting it via `h5db["inputs/settings"]`?

**Comment by opotowsky** [comment]
You're right about the validation piece though. I can have `versions: armi: 0.8000.1` in my settings and if I'm running `armi 0.2.7` nothing will fail. When we want this perhaps to also validate the version bein run, correct?

**Comment by john-science** [comment]
We will not be removing the setting, as suggested in your option (1).  Here are three reasons:

1. **Numerous people people have requested this feature.**
    * The feature is used.
2. **ARMI output traceability.** 
    * As a fun example, in meteorological and climate modeling the standard of best practice is to store the versions of software you are using in your configuration and output files. I agree with that standard. If in 3 years you're looking at an ARMI output database, and you don't know what version of ARMI that was used to generate it, the value of that output DB is greatly reduced.
3. **Database Migrations.**
    * How could we possibly do database migration if we don't know the versions?
    * You can not see it yet, but the upcoming re-design for the `armi/migration/` module depends on this setting.

Sure, (2) is an interesting idea.  We can do that.  Open a new ticket. (However, if your concern is just that this setting is not used, the DB migration redesign is on the [Roadmap](https://github.com/terrapower/armi/wiki/Roadmap).)

**Comment by albeanth** [comment]
I support keeping the version in the DB, just that we actually make it useful. The concern is not that the setting is unused, but rather it's current use is confusing. 

I will open a new ticket!

**Comment by john-science** [comment]
> I support keeping the version in the DB, just that we actually make it useful. The concern is not that the setting is unused, but rather it's current use is confusing.

Again, it will be used in the database migration, but that work was postponed with all other ARMI work.
