### ISSUE TITLE
`pseudoDensity()` is being used in `getTemperatureAtDensity()`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1246]
I think it's probably unlikely that somebody would expect to have to pass in the 2D-expanded density to this method:
https://github.com/terrapower/armi/blob/26bda056b51e42cb705c8dbfa4b977243c8eec6d/armi/materials/material.py#L363-L373

My guess is that this is a bug, but somebody else might be able to confirm?

**Comment by john-science** [comment]
It _does_ look suspicious.

I guess the question is: does the linear expansion logic use this?  

If the linear expansion is the only user of this method, then this method is correct.  But needs a better docstring. In any other situation, this seems wrong.

**Comment by keckler** [comment]
The only place I see this being used is through a call to `getTempChangeForDensityChange()` in one of our internal plugins. In that case, it does appear to be a bug. Ping me offline and we can talk about that specific use case.
