### ISSUE TITLE
Settings Report page is broken

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1249]
Sometime in the past week or two, the "Settings Report" page of our docs appears to have broken. It no longer renders the big table of all the settings. This is what I see when I go to the page:
![image](https://user-images.githubusercontent.com/21959600/234339385-0f78e521-f86f-4b76-a4ec-9a96fc3c120e.png)

**Comment by john-science** [comment]
I guess we need to find the commit that broke this.  Damn.
