### ISSUE TITLE
Update the pinned version of black to the latest

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1251]
Right now, we have a version pin of `black==20.8b1`. Upon official release, the backwards compatibility was broken with previous versions. Since then, however, black has guaranteed backwards compatibility. So we should make the leap, reformat ARMI, and jump to black v23+

**Comment by john-science** [comment]
Actually, I think we SHOULD still pin the version of `black`. But just pin it to something much more modern.

**Comment by opotowsky** [comment]
Notes on this: v22 has ~50 file diffs, v23 has ~100. pinning to v22 is "less work" if we do this to more repos. (Many repos have no update at all!)

**Comment by john-science** [comment]
The usual approach in a software company for things like this would fall into two scenarios:

1. Constantly update the version of dependency to the latest-and-greatest.
2. Occasionally, say once a year, go through and updated the version of this dependency to near latest-and-greatest.

Now, software projects with a large direct-import user base rarely do (1) and I caution against it.  

I like the idea of (2) going through and (say once a year) trying to update the version of `black` to near  latest-and-greatest.

**Comment by opotowsky** [comment]
I wholeheartedly agree. I think if we update to v22, we can make it happen whenever because the internal impact is minimal (the 40ish ARMI files plus 40 more across 10 repos). If we do v23, the impact is pervasive internally so we'd need to time it during a quiet dev period.

**Comment by john-science** [comment]
We have made our decision and pinned `black` to a more recent version:

https://github.com/terrapower/armi/blob/360791847227df3f3a337a996ef561e00f846a09/setup.py#L83

So, we are closing this ticket for now.
