### ISSUE TITLE
Can we move the "version" setting out of metadata?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1267]
Right now, all settings in the `CaseSetting` object are easily retrieved through the simple method:

```python
cs["nCycles"]
```

This is great. It easy to use and clear.

However, one setting is unique and different: "version" is the version of ARMI the simulation was run with, and it is in a special "metadata" area, outside the settings:

https://github.com/terrapower/armi/blob/fc26c390e01ce541e5f66fb530a89ada2479a6e9/armi/tests/armiRun.yaml#L1C1-L2

This is pretty annoying.  Because you can't just do `cs["metadata"]` or `cs["version"]` or anything.  But people have frequently asked me how to get this information programmatically, because they need it.  And I have to write them some code that fines and parses the YAML file in question NOT using ARMI or `yamlize`.  

It would be an API change, but it feels like we should just remove the `metadata` tag entirely from this file, and make `version` a regular setting.

**Comment by john-science** [comment]
Alternately, I have opened a `yamlize` ticket to see if there is an easy work-around I can bake into the `CaseSetting` class without having to change our settings files or API.

**Comment by john-science** [comment]
Also related #1234

**Comment by jakehader** [comment]
@drewj-usnctech - the introduction of version might have been something that we had discussed for your needs. If so, can you take a look at #1234 and see if we can remove the setting for version and just slap it into a database? Maybe the version number predates this though.

@john-science - it might be that version was / is used in the settings for auto migration purposes. I'm not sure the history there but @ntouran could remember. I still think that the tagged issue is a good one but might be independent here.

**Comment by john-science** [comment]
@drewj-usnctech  Thanks!

Also, this is my current favorite:

```yaml
settings:
  versions:
    armi: 0.2.6
    mySnazzyApp: 0.1.0
    coolPlugin: 2.4.1
```
