### ISSUE TITLE
Arbitrary Structured ARMI database

### ISSUE THREAD

**Issue by sombrereau** [terrapower/armi#1269]
I have a reactor that does not have solid fuel assemblies could I use the ARMI database to store nuclear design parameters (multi-group flux, volume, power, DPA rate, number density etc).

I'd like to be able to read/write outputs in hd5 leveraging the ARMI database infrastructure would be a value add rather than doing a million things ad hocs.

Can I do this without making an ARMI reactor?

**Comment by sombrereau** [comment]
We can start this with a simple model that has 

reactor
- core 
 -- fuel salt
 -- reflector
- pipe 

and I'd like to save 33 group flux on the fuel salt, the reflector and the pipe

**Comment by jakehader** [comment]
Hi @sombrereau - the ARMI database is well structured based on the composite tree and reactor core map. I think that you might be able to achieve what you are looking for with a new type of hdf5 structure outside of the framework or it could even look like a JSON or YAML file if that's easier to communicate with in terms of loading into a Python dictionary.

If you still wanted to use the framework you may be able to leverage some pieces to build new composites that can be associated with the parameter system but I think this would definitely look like a new database interface with hdf5 with a lot of custom tooling.

What do you think?

**Comment by sombrereau** [comment]
what I'm hearing is that it could be done .. but it would probably be a lot of work because this use case wasn't considered when designing the ARMI database system?

**Comment by jakehader** [comment]
Is your data storing need just to store flux or are you looking for any and up to all ARMI/ARMI application parameters? Is there something. Specific about the HDF5 format that you like? 

It should be pretty simple to write a new plugin to make a database file for storing data (i.e., open up a file with h5py, make new records and write to them, and close the file), but if you're looking to load it back to anything related to the reactor you'll need to also build that as well. 

The database that ARMI writes is also not intended to be used for pulling data directly from it and the design is such that the user should load the data onto an existing reactor data model and inspect the reactor from there. I believe the structure attempts to remove duplication to reduce size and also puts parameters in a slightly different order that only the database interface knows how to extract from.

I'd like to help solve your problem if you can provide a bit more info on your desirements/requirements/concept that you are thinking about

**Comment by john-science** [comment]
One possible solution to this would be to an `ExCore` child to the `Reactor`.   Then Pylot could define parameters for the objects in that structure, like we do in so many other places in ARMI and in downstream plugins:

https://github.com/terrapower/armi/blob/6163e942abe873129533b84a6f2efa632f260b47/armi/physics/neutronics/parameters.py#L30-L32

So, we would define:

* `class ExCore(composites.Composite)`, to be a hierarchical data object for storing ex-core structures.
* `Reactor.excore` would be added as a attribute to the `Reactor` class.
* Something like an `ExCoreStructure` / `ExCoreBlock` would need to be created, so we have something to add `Parameter`s to.

This all seems quite easy to do. And then ex-core structures would be automatically read to-and-from the ARMI Database.

Downsides on this first draft, that ARMI could improve in future versions:

* You would have to define your ex-core structures in code (this doesn't solve the need for "3D blueprints").
* If you wanted objects like `Shielding` or `ContainmentVessel` or `Pipe`, you would have to subclass our `ExCoreBlock` and define them yourself.
