### ISSUE TITLE
densities are ignored on custom isotopics when material is provided

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#1272]
https://github.com/terrapower/armi/blob/76031431c1d96e17c1135874926bd24ac92a3e65/armi/reactor/blueprints/isotopicOptions.py#L359-L367

We should be able to support this. it should probably be elevated to more than a warning since it is completely ignoring using input.

A code fix where the density was accounted for would be better

**Comment by jakehader** [comment]
@keckler - you may have some opinions on this with your benchmarking custom classes for materials. Have anything to add here with respect to your implementation?

**Comment by keckler** [comment]
Thanks for checking! 

@onufer and I talked about this offline, and we are in agreement that this should be supported.

I think the biggest thing that needs to be considered is how the mass density that a user specifies should scale with thermal expansion. 

I think the most obvious or expected action would be that the component applies the thermal expansion relative to "nominal" based on the material class's thermal expansion routines. This sounds straightforward, but in my experience is difficult to generalize based on the wide variety of ways in which the thermal expansion is implemented under the hood on different material classes. It would also require the temperature associated with the input number densities to be specified, although we could force this to be equal to `Tinput` for the component.

A related ticket that keeps getting brought up and shut down is https://github.com/terrapower/armi/issues/535
