### ISSUE TITLE
Make hasFlag function recursive

### ISSUE THREAD

**Issue by clstocking** [terrapower/armi#1295]
@john-science @opotowsky I think that it would be helpful if the `hasFlag` function in the various reactor objects was recursive and searched all of the included objects. For instance `a.hasFlags(Flags.WIRE)` would search not just the assembly, but all included blocks and components for the WIRE flag. It seems intuitive to me that if an assembly contained wire components that the return of the function should be `True`.

I am not sure if there is a good reason that this is not how the function currently operates.

**Comment by opotowsky** [comment]
I was thinking too narrowly, like "sure lets do this but at least preserve the current functionality so a million code changes aren't needed in ARMI and in all downstream plugins"

But what if we just made a new one? `assemblyHasFlags` that loops over blocks and components looking for block- and component-only flags?

**Comment by clstocking** [comment]
@opotowsky I agree that it should be a separate function. There could be cases such as a fuel assembly with a reflector block or something that could lead to unintended results changing the existing function.

**Comment by john-science** [comment]
Hmmm...

`c.hasFlagsRecursive()` would be easier for me to do.

I would need to do a lot of testing and research to figure out _all_ the places in our various code where making this recursive assumption would surprise people. 

Off the top of my head, there are at least a couple places where people will still want to just inspect the specific reactor component they are looking at, and not every sub-component below it.  So we will still need to support the non-recursive form of `hasFlags()`.

**Comment by clstocking** [comment]
I agree that seems like a good solution. Just to add I think it would be best that this function is available at all levels of the reactor. So for an assembly it would search the assembly, blocks, and components and for a block would search the block and components.

Thanks @john-science and @opotowsky for taking this on

**Comment by john-science** [comment]
Also, fun fact, the `Composite.hasFlagsRecursive(flag)` method would be exactly the same as:

```python
c.doChildrenHaveFlags(flag, deep=True)
```

And that doesn't just work on Assemblies, it works on ANY part of a Reactor, big or small.

I hadn't really noticed this before, but it's already in there:

https://github.com/terrapower/armi/blob/b66c4dc1386ccb617678eb1c97cd39ec14cd5e0f/armi/reactor/composites.py#L549-L563

**Comment by opotowsky** [comment]
Well how 'bout that!?

**Comment by clstocking** [comment]
@john-science there is no need to add another function that serves the same purpose. I was not aware of that function, but if it already does what I was asking for then I think we could probably just close the issue.
