### ISSUE TITLE
Enable simpler command line unit testing

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1300]
## Summary: 

I want to run `pytest .` and have it work

## Detail: 

Right now, if someone wanted to run unit tests locally, they would need to run `pytest --ignore=armi/utils/tests/test_gridGui.py .`

I always forget this myself, and field questions about it semi regularly. We should delete the broken tests, or find some other way for `pytest .` to work.

Is there a reason to keep these tests? Could we just add `skip` decorators to them?

**Comment by john-science** [comment]
Okay, I am trying to reproduce your bug.  I believe there are two different things that can cause this test (there's only one in the file) to be skipped or run:

1. Do you have `wxpython` installed?

https://github.com/terrapower/armi/blob/77ed83c22a1a08e6a1e890ade931352fc0dd8916/armi/utils/tests/test_gridGui.py#L61

2. Do you have the `ARMI_GUI_TESTS` environment variable set?

https://github.com/terrapower/armi/blob/77ed83c22a1a08e6a1e890ade931352fc0dd8916/armi/utils/tests/test_gridGui.py#L144-L145

So I tried all the combinations of the above to things to see what happened:

| wxPython Installed? | True | False |
|--------------|-----------|------------|
| env var True | **Failed** | skipped |
| env var False | **Failed** | skipped |
| env var unset | skipped | skipped |

And the failures both have the same cause:

```bash
FAILED armi/utils/tests/test_gridGui.py::Test::test_setNumRings - AssertionError: 1 != 196
```

So I think I have learned two things here:

1. I am surprised this test ever runs on your machine (you must have the env var `ARMI_GUI_TESTS` set).
2. The test is straight-up broken.

**Comment by john-science** [comment]
I am leaning toward just deleting the test file.

The test has been broken for at least one year (I haven't looked back further).

And even if it _did_ work, we have been explicitly blocking using it on GitHub or our local workstations for years.
