### ISSUE TITLE
Improve latticePhysicsWriter unit testing

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1303]
> The lattice physics writer has a barely-test that covers it, so the small code cov drop is a result of the code in `latticePhysicsWriter.py` changing a little so 4 new lines are uncovered. Since this is mainly a feature reversion I don't want to hold up progress, and we need to get some real tests covering that module. Making an issue about it so I can merge this PR.

_Originally posted by @opotowsky in https://github.com/terrapower/armi/issues/1298#issuecomment-1588172626_

**Comment by onufer** [comment]
we have lots of tests in terrapower proprietary code in the mc2 plugin.

**Comment by john-science** [comment]
There is only one unit test for `latticePhysicsWriter.py`, and it is [here](https://github.com/terrapower/armi/blob/bc2763fe14fd4f9b8cb1b50b0c9b53dea25452c8/armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py).  So I totally agree.

The actual [code coverage](https://coveralls.io/builds/60684385/source?filename=armi%2Fphysics%2Fneutronics%2FlatticePhysics%2FlatticePhysicsWriter.py) for the file is pretty good (~76%), but that's clearly not from direct unit tests.

Good catch, Arrielle!
