### ISSUE TITLE
Make the SFP a child of the Reactor, not the Core

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1317]
For some historical reason, the Spent Fuel Pool (sfp) is a child of the core, not the reactor:  `r.core.sfp`.  This needs to be fixed.

This is not a hard change to make.  But it _might_ mean tons of little tweaks in ARMI and in downstream repos.  So I expect a mildly inflated LOE.

https://github.com/terrapower/armi/issues/876#issuecomment-1248565251

**Comment by keckler** [comment]
Please keep me in the loop with any work that goes on here, it will have implications for multiple models that I am responsible for.

**Comment by john-science** [comment]
@keckler @opotowsky  Actually, after grepping around, I can't find any downstream repos that USE the Spent Fuel Pool (SFP) at all.  So, unless Chris has access to a repo I don't normally check, I think this change can be made quite freely, as it will be ARMI-only.

**Comment by john-science** [comment]
So, the hold up on this ticket is the method `Core.removeAssembly()`:

https://github.com/terrapower/armi/blob/71406e3ce6cb86f72f5eb718b7456fa5c0bf7d61/armi/reactor/reactors.py#L426

Which is part of the `Core` class and has the power to move an assembly from the core to the SFP:

https://github.com/terrapower/armi/blob/71406e3ce6cb86f72f5eb718b7456fa5c0bf7d61/armi/reactor/reactors.py#L468-L471

But if I move the SFP to`Reactor.sfp`, then when you `Core.removeAssembly()` the `Core` class wouldn't have access to the `Reactor` class to put the removed assembly to the SFP.

I could fix this indirectly, but I found a dozen downstream plugins that are using `Core.removeAssembly()` directly.  And I was hoping to avoid a big, multi-repo change. 

TBD

**Comment by keckler** [comment]
I have some model repos that use the SFP. But I do not know of any plugins that use it.

I am reviewing #1336 right now and checking it against my models.
