### ISSUE TITLE
`resolveMarkupInclusions` takes `TextIOBase` as input but can't take it all the way home

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1329]
If I have code like so: 

```python
yaml = YAML()
loadedYaml = yaml.load(pathlib.Path(readPath))
#...skipping some important but unrelated stuff that is the reason for this approach...
yamlStream = TextIOBase(loadedYaml)
yamlStream = resolveMarkupInclusions(src=yamlStream, root=pathlib.Path(readPath).parent)
```

I get:
```
    yamlStream = resolveMarkupInclusions(
  File "<path>framework\armi\utils\textProcessors.py", line 187, in resolveMarkupInclusions
    return _resolveMarkupInclusions(src, root)[0]
  File "<path>\framework\armi\utils\textProcessors.py", line 247, in _resolveMarkupInclusions
    _processIncludes(src, out, includes, root)
  File "<path>\framework\armi\utils\textProcessors.py", line 96, in _processIncludes
    for i, line in enumerate(src.readlines()):
io.UnsupportedOperation: readline
```

`resolveMarkupInclusions` should be able to take either a filepath to a yaml, or a yaml `TextIOBase` "stream". But as you can see above, this line can't handle `src` being a `TextIOBase` object:
https://github.com/terrapower/armi/blob/47e02154ee44b4e2f9d1d82e460281f42ab8396f/armi/utils/textProcessors.py#L96

There is a nonzero chance the error is mine, but I've looked at the problem long enough that I'm comfortable making this issue.

**Comment by opotowsky** [comment]
If it makes any difference, I tried to edit the code snippet above to this (this was actually my first attempt):
```python
yaml = YAML()
loadedYaml = yaml.load(pathlib.Path(readPath))
#...skipping some important but unrelated stuff that is the reason for this approach...
yamlStream = TextIOBase()
yaml.dump(loadedYaml, yamlStream)
yamlStream = resolveMarkupInclusions(src=yamlStream, root=pathlib.Path(readPath).parent)
```

And got:
```
    yaml.dump(preBuildData, TextIOWrapper(preYamlStream))
  File "<path>venv\lib\site-packages\ruamel\yaml\main.py", line 574, in dump
    return self.dump_all([data], stream, transform=transform)
# skip a bunch of the stack trace
  File "<path>venv\lib\site-packages\ruamel\yaml\emitter.py", line 1740, in write_comment
    self.stream.write(value)
io.UnsupportedOperation: not writable
```

**Comment by john-science** [comment]
Arrielle and I have worked on this offline and found a good path forward. It appears to be a combination of two problems: one because an ARMI method has no type hints/docs, and one in ruaml.yaml not round-tripping comments in YAML files well.

Both are solvable, PR incoming.

**Comment by opotowsky** [comment]
For the round tripping of comments issue, I found a resolution in my script. 

I was trying to do:
```python
yaml.load(filepath)
```
which on Windows added a `\r` to the end of every comment. The workaround was stealing this code:
https://github.com/terrapower/armi/blob/680fcc302412850eb8b51623179d9b7b447000f8/armi/utils/textProcessors.py#L237-L238

No more windows line endings ruining my day
