### ISSUE TITLE
`Ring` and `Pos` assembly parameters

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1337]
There are a couple different assembly parameters that are meant to indicate the assembly's location in a core, `Ring` and `Pos`:
https://github.com/terrapower/armi/blob/17a35237fd26537b5eb5f386b5d86392d1d38ec2/armi/reactor/assemblyParameters.py#L305-L307

These parameters appear to be completely unused throughout ARMI and all of our internal plugins (at least the ones I can see). My guess is that their intention has been usurped by the use of `spatialLocator`s by now, and the parameters are just legacy cruft. I suppose also, they are only relevant to hexagonal cores.

At the very least, their names use inconsistent capitalization in comparison to other parameters, and their definitions should be cleaned up to not just be a bunch of question marks.

I propose to just get rid of them, as I don't think they serve any use anymore.

**Comment by john-science** [comment]
We can remove them and find out!

**Comment by jakehader** [comment]
I think that there is value in having these only if they are used correctly, but if they are now not set or worse set incorrectly then it makes sense to move out of the framework.

**Comment by ntouran** [comment]
> My guess is that their intention has been usurped by the use of `spatialLocator`s by now, and the parameters are just legacy cruft.

Correct.
