### ISSUE TITLE
Installing requirements-testing.txt locally takes very long

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1339]
I got a lot of this when installing `requirements-testing.txt` deps in a fresh venv:
```
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
```
Running this installation step locally is going on 90 minutes now. I'm not sure if this slows down github actions or why it's taking so long locally, but we may or may not want to take pip's advice on this...

**Comment by john-science** [comment]
I tried this:

1. I created a fresh venv
2. I did a direct `pip install -r requriements-testing.txt`, with no other install first.

The results:

1. On my work/Windows laptop:  ~4 minutes
2. On my personal/Linux laptop:  45.4 seconds

**Comment by john-science** [comment]
Also, this install is pretty fast on GitHub Actions. Though I don't have an exact timer there, it's under 5 minutes.

**Comment by opotowsky** [comment]
Ok, I've confirmed this is an internal/me problem. Sorry for the noise!
