### ISSUE TITLE
Update docs dependencies to be compatible with python 3.11

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1344]
Sphinx, sphinx helper packages, and other docs deps are a delicate balance. Change one and everything breaks. 

In trying to even install python 3.11-compatible deps I ran into an issue installing `sphinx-data-viewer`. And it is no wonder:
![image](https://github.com/terrapower/armi/assets/5347433/4d23fb8c-a431-4400-90c1-813c7cbece5b)

This is not a primary dependency, but it's a secondary dep of `sphinxcontrib-needs`. We will need to research if this package has any py311-friendly alternatives or if we just need to wait. 

While this happens, the ARMI default CI python will be 3.11 and the deps will keep building on 3.9.

**Comment by ntouran** [comment]
I have good news. Sphinx-needs changed from sphinxcontrib-needs to sphinx-needs a few years ago. Swap that and this will work great on 3.11 👍

https://sphinx-needs.readthedocs.io/en/latest/

**Comment by opotowsky** [comment]
> Sphinx-needs changed from sphinxcontrib-needs to sphinx-needs a few years ago. Swap that and this will work great on 3.11 👍
> 
> https://sphinx-needs.readthedocs.io/en/latest/

🙇 You sir have saved the day. I am sure I would have figured this out eventually but it's nice to be handed this info on a 🍽️
