### ISSUE TITLE
Unreachable Code

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1354]
Was stepping through a debugger and noticed that this was all unreachable code. It can be safely removed or if is something we actually want to keep should be relocated. 

https://github.com/terrapower/armi/blob/5912372a9c037f8b6caf52749ebe6dc28c06b873/armi/reactor/blocks.py#L1968-L1974

**Comment by albeanth** [comment]
@john-science @jakehader

**Comment by jakehader** [comment]
What a strange piece of code! Not even sure that method really should be on a block... Looks like a helper function if anything. Is this called on block initialization?

**Comment by john-science** [comment]
Yeah, I'm in favor of just deleting this block of code.

**Comment by mgjarrett** [comment]
It was probably just a simple indentation error. Is it possible that we actually wanted that error check, and it just needed to be bumped out one level of indentation?
