### ISSUE TITLE
Broken Link in Docstring

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1361]
Was poking around here as part of a PR review and found that this link is broken. 

https://github.com/terrapower/armi/blob/f947ea12266b688f3f2e3402fa458076849d1375/armi/reactor/parameters/parameterDefinitions.py#L41

**Comment by john-science** [comment]
That HTML link was added more than 4 years ago:

https://github.com/terrapower/armi/blame/f947ea12266b688f3f2e3402fa458076849d1375/armi/reactor/parameters/parameterDefinitions.py#L41

I suppose I am not surprised the link is dead.

Perhaps we should just remove it?  

Or do we NEED to find another?
