### ISSUE TITLE
Audit Composite/ArmiObject methods and their applicability to all objects

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#1375]
This is a general request to go through the implementation of each composite and to understand if an implementation should be applied generically to all objects in the composite tree. Examples include:

- [ArmiObject.changeNDensByFactor()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L1705-L1710)
- [ArmiObject.getDominantMaterial()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L2656)
- [ArmiObject.getMgFlux()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L2285) - suspect
- [ArmiObject.getMaxVolume()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L901) - abstract method
- [ArmiObject.getMicroSuffix()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L950) - abstract method
- [ArmiObject.getUraniumNumEnrich()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L1785) - suspect
- [ArmiObject.getUraniumMassEnrich()](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/composites.py#L1777) - suspect
- etc.

We might have went a bit too far on the data model in terms of inheritance of methods across the system and it leads to quirks like having material-specific implementations, using a `LumpedFissionProduct` within the system (physics related), assuming that an implementation could be made generically on a `Core`, `Assembly`, `Block`, or `Component`. 

Some things to think about are:

- Using functions that can consume an `ArmiObject`, check its type, and then perform the work requested
- Forcing implementations so that it's clearer how inheritance is happening (e.g., `Blocks` jump to `Composites` and then to `Components` in some implementations and this can be confusing to sort through)

Associated Tickets/Issues
---------------------------
- [ ] https://github.com/terrapower/armi/issues/1374

**Comment by john-science** [comment]
Notes on the usage of the above suspect methods:

* `ArmiObject.changeNDensByFactor()` - Mostly just used in ARMI. Though used in a few places.
* `ArmiObject.getDominantMaterial()` - Used in ARMI and downstream a bit, for `Block`s and `Core`s.
* `ArmiObject.getMgFlux()` - Used Broadly. Though nearly always at the `Block` level.
* `ArmiObject.getMaxVolume()` - This is unused outside of ARMI. And inside ARMI only uses this for [DerivedShapes](https://github.com/terrapower/armi/blob/64351a0a5538e6a150d2c4f9a1183fa6558f5269/armi/reactor/components/__init__.py#L386-L397).
* `ArmiObject.getMicroSuffix()` - Used Broadly. Though nearly always at the `Block` level.
* `ArmiObject.getUraniumNumEnrich()`  - only used in one place ANYWHERE in the ARMI universe: a single line in a fuel performance interface for Alchemy.  And in that situation it is only used at the `Block` level.
* `ArmiObject.getUraniumNumEnrich()`  - only used in two places downstream. Both times it is only used at the `Block` level.

**Comment by john-science** [comment]
Ideally, I will write a little tooling to help us see where and how all the methods on `ArmiObject` and `Composite` are used downstream.

I think we have a lot of bloat here that I would love to clean up. Having said that, I will probably need to prioritize removing the bloat by the low-hanging-fruit method.
