### ISSUE TITLE
Find a way to run `coverage` on python 3.11

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1377]
Typically, github actions are set to run on the latest version of python that we have tested with ARMI. #1341 originally set out to bring all GH actions up to python 3.11, but a known issue with `coverage` (#1058) prevented us from updating the coverage dependency to a python 3.11 compatible version. 

We need to investigate the bug with the coverage version and see if it can be fixed.

I had coverage pinned to 7.2.1 in both setup.py and the coverage workflow, and the action failed. 

Update: I'm not sure what the above bug is all about, but `coveragepy_lcov` has not been updated in 1.5 years and is not python 3.11 compatible. So we will need to completely rework the cooverage step to make it run on python 3.11

**Comment by john-science** [comment]
Well, that's a bit of a shame.  

ARMI currently uses `coveragepy_lcov` and `coveralls.io`. 

To be honest, I don't love `coveralls.io`.  It's been fine lately, but last year it broke a bunch of times.  My guess is if we moved away from that, we would end up using some other tool than `coveragepy_lcov` anyway.

https://github.com/terrapower/armi/issues/1017

**Comment by ntouran** [comment]
Open issue with coverage_lcov being incompatible with coverage 7.0.0 is [here](https://github.com/chaychoong/coveragepy-lcov/issues/5)

FWIW, running `coverage run -m pytest -x -n 32 armi` with python 3.11 works like a charm using coverage 7.2.7, which I guess you already knew. 

Looks like pytest can output directly to lcov format though so we can skip the lcov conversion:

```
commands = pytest --cov --cov-report=lcov
```

ref: https://github.com/epitools/epitools/pull/72/files
