### ISSUE TITLE
Lots of warnings about not being able to find zones but nothing breaks

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#1408]
We leverage the zoning features for lots of physics routines, which means we often fall back to [`Zones.findZoneItIsIn`](https://github.com/terrapower/armi/blob/5c4c5cfd80434e66363bd849d4ac32d456277ea7/armi/reactor/zones.py#L375-L398) quite a lot.

This allows zones to not be found and will return `None`. Which isn't a problem for our applications because we don't do the thing if an assembly isn't in some zone. But this can flood the run log with messages like
```
[warn] Was not able to find which zone <fuel stack Assembly A0001 at 002-005> is in
[warn] Was not able to find which zone <fuel stack Assembly A0003 at 002-006> is in
...
```
due to

https://github.com/terrapower/armi/blob/5c4c5cfd80434e66363bd849d4ac32d456277ea7/armi/reactor/zones.py#L395-L398

Is the runlog call really necessary? Or should it be left up to the thing that uses `Zones.findZoneItIsIn` to determine if `None` is okay, worth reporting a warning, or raising an error?

**Comment by john-science** [comment]
There is only one place ARMI uses `findZoneItIsIn()`:

https://github.com/terrapower/armi/blob/7f8936723f6413fcf57ca648a58bc6f6f2ced706/armi/reactor/converters/geometryConverters.py#L1289-L1293

I also can't find anywhere else that anyone at TerraPower is using this method.  And that's my guess for why you would be seeing many warnings and they wouldn't have been seen before.

A few thoughts:

1. We don't want this to raise an error, it is quite common and totally acceptable when converter a 1/3 core.  (Converting this to a full error would break things for a lot of users.)
2. We could make sure that this log statement is never duplicated by adding a `single=True` statement.  (This stops any log statement for being repeated during a run.)
3. We could move this to debug.

Thoughts?

**Comment by drewj-usnctech** [comment]
> We don't want this to raise an error

Agree. It would break a lot of things for us too 😅 

> adding a single=True statement

If it's important enough to let someone know one assembly wasn't found, why not all of the assemblies?

> We could move this to debug

seems like a good option. Then if someone's model gets wonky they can debug it.

I would also be okay to removing the runlog call (warning / debug) wholesale, and letting things that use this method raise take appropriate action

**Comment by john-science** [comment]
> > adding a single=True statement
> 
> If it's important enough to let someone know one assembly wasn't found, why not all of the assemblies?

Just to be clear, the "single=True` logic would determines uniqueness of a log statement based on exactly matching strings.  So, if this log statement was hit 100 different times for a total of 2 different assemblies, only 2 log statements would show up for the end user.

**Comment by drewj-usnctech** [comment]
>  So, if this log statement was hit 100 different times for a total of 2 different assemblies, only 2 log statements would show up for the end user.

Ah, okay. I misunderstood your intention. Thanks for clarifying
