### ISSUE TITLE
Explicit fission products with depleting structural material will cause heavy metal to be put into structural material upon new assembly creation

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#1414]
steps to reproduce
1) turn on depletion for both fuel and stucture in the same block
2) `o=armi.init`
3) `o.getInterface("fissionProducts").interactBOL()`
4) `a=o.r.core.createAssemblyOfType("myType")`
5) `b= a[indexWithFuel]`
6)  `for c in b:     print(c, c.getHMMoles())`

expected result is heavy metal in structural

we may want to rethink having fp model as an interface and having it automatically called during reactor constitution/init...

**Comment by onufer** [comment]
@jakehader  @john-science

**Comment by jakehader** [comment]
Might be related to #1374

**Comment by onufer** [comment]
I agree its related. It might be nice if would could not have FP model as full interface and just have it do its thing on creation of assemblies

**Comment by onufer** [comment]
This is no longer reproducible after this
https://github.com/terrapower/armi/pull/1665

**Comment by mgjarrett** [comment]
Closing as fixed by #1665
