### ISSUE TITLE
`plotBlockDiagram()` doesn't respect block orientation

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1421]
The [`plotBlockDiagram()`](https://github.com/terrapower/armi/blob/8041ad889a0203da4602f0be321b54ebef5995b6/armi/utils/plotting.py#L1375) function appears to always assume that the lattice within the block is "flats-up". This becomes an issue if one has manually defined a "points-up" 
pin grid. In that case you'll get a print like the following:
![image](https://github.com/terrapower/armi/assets/21959600/e99d44fc-4f7d-48b7-840b-c8f45d09fa8c)

The problem lines appear to be in this chunk:
https://github.com/terrapower/armi/blob/8041ad889a0203da4602f0be321b54ebef5995b6/armi/utils/plotting.py#L1283-L1290

Instead of always rotating the hex patch by 30 degrees, it needs to instead be able to interrogate the underlying grid to know the rotation. Unfortunately I think this is a challenge right now, as the block itself doesn't know the type of grid that is in it (that info is stored on the associated block _blueprint_). Even still, many block blueprints don't actually have a grid attribute even if the block later gets an auto-generated grid. This is related to https://github.com/terrapower/armi/pull/730#discussion_r913942220

This type of problem could be solved once https://github.com/terrapower/armi/issues/1284 is implemented, I would guess.

**Comment by drewj-usnctech** [comment]
Possibly related to a lot of the assumption that most hexagons are flats up - #1278

**Comment by mgjarrett** [comment]
I don't think the block needs to know what kind of grid is inside it, it just needs to know what kind of grid it is in. For a hex grid, the block grid and the pin lattice should be opposites. If they're not opposites, that's an input error.

**Comment by keckler** [comment]
> I don't think the block needs to know what kind of grid is inside it, it just needs to know what kind of grid it is in. For a hex grid, the block grid and the pin lattice should be opposites. If they're not opposites, that's an input error.

I agree with this idea, and it is actually pretty slick. 

However, if you consider the printed diagrams to be a tool for diagnosing input errors, then maybe relying on the user being correct is not a good idea. Unless, of course, there is another check in place to ensure that the grid and block rotations are appropriate for each other.

**Comment by mgjarrett** [comment]
> > I don't think the block needs to know what kind of grid is inside it, it just needs to know what kind of grid it is in. For a hex grid, the block grid and the pin lattice should be opposites. If they're not opposites, that's an input error.
> 
> I agree with this idea, and it is actually pretty slick.
> 
> However, if you consider the printed diagrams to be a tool for diagnosing input errors, then maybe relying on the user being correct is not a good idea. Unless, of course, there is another check in place to ensure that the grid and block rotations are appropriate for each other.

I agree that there should be input validation to ensure the blocks and pins are correctly rotated w.r.t. one another. We don't currently have any such input validation that I know of.

**Comment by keckler** [comment]
See https://github.com/terrapower/armi/pull/1648 for an incoming fix.

**Comment by drewj-tp** [comment]
I wonder if the problem is related to the `HexBlock.autoCreateSpatialGrid` defaulting to assuming the sub-block grid is corners up

https://github.com/terrapower/armi/blob/9dbe15c621ecac1060bdfde9715cf87697c24208/armi/reactor/blocks.py#L2371-L2373

If you have a flats-up super-grid, or the grid on which blocks are assigned, the pins on those blocks will be corners up. But, the grid created by `HexBlock.autoCreateSpatialGrid` is *always* corners up, like in the picture @keckler posted.

The grid being the wrong orientation is going to influence the locations of the items on that grid, which I assume is what the block plotter is looking at when it makes the patches for the circles

**Comment by john-science** [comment]
> I wonder if the problem is related to the `HexBlock.autoCreateSpatialGrid` defaulting to assuming the sub-block grid is corners up
> 
> https://github.com/terrapower/armi/blob/9dbe15c621ecac1060bdfde9715cf87697c24208/armi/reactor/blocks.py#L2371-L2373

So... the method `autoCreateSpatialGrid()` is only called (ignoring unit tests) when loading from an incomplete blueprint file that doe not have a grid design defined. Most of the time this will result in an error anyway, so I doubt this method is called often.

This is a default for that won't apply if you have a `lattice map` in your blueprints.
