### ISSUE TITLE
Investigate h5py v3.10.0 failure to unpin dependency

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1428]
## Background 

CI for PRs mysteriously began failing on one blustery day in October. @keckler was the first down.

Here's an example failure: https://github.com/terrapower/armi/actions/runs/6460630865/job/17538712292

```
 Traceback (most recent call last): 
523  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\unittest\case.py", line 57, in testPartExecutor 
524  yield 
525  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\unittest\case.py", line 623, in run 
526  self._callTestMethod(testMethod) 
527  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\unittest\case.py", line 579, in _callTestMethod 
528  if method() is not None: 
529  ^^^^^^^^ 
530  File "D:\a\armi\armi\armi\bookkeeping\db\tests\test_database3.py", line 453, in test_mergeHistory 
531  database3.Database3._writeAttrs( 
532  File "D:\a\armi\armi\armi\bookkeeping\db\database3.py", line 1386, in _writeAttrs 
533  obj.attrs[key] = value 
534  ~~~~~~~~~^^^^^ 
535  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper 
536  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper 
537  File "D:\a\armi\armi\.tox\test\Lib\site-packages\h5py\_hl\attrs.py", line 104, in __setitem__ 
538  self.create(name, data=value) 
539  File "D:\a\armi\armi\.tox\test\Lib\site-packages\h5py\_hl\attrs.py", line 202, in create 
540  attr = h5a.create(self._id, name, htype, space) 
541  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
542  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper 
543  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper 
544  File "h5py\h5a.pyx", line 50, in h5py.h5a.create 
545 OSError: Unable to synchronously create attribute (object header message is too large)
```

This mystery failure was from a new release of the h5py package to PyPI. 

**_So the temporary solution is to version pin h5py to <= 3.9.0. Since we don't yet have a habit of reviewing version pins, however, I would like to unpin this dependency as soon as we find a fix for the problem._**

## More Details

I spent a little time tracking down what could be the failure but since we have a temporary fix I cannot justify more time sleuthing this week (the technical debt conundrum). Here's where I left things:

h5py 3.10.0 changelog: https://docs.h5py.org/en/stable/whatsnew/3.10.html

What I believe to be the responsible PR: https://github.com/h5py/h5py/pull/2134/files

**Comment by john-science** [comment]
I actually think pinning a version range to ALL dependencies on ARMI would be a good approach.

It would prevent situations like this. And when we wanted to update our versions of dependencies, we could do so at our leisure, without a panic attack.

BUT, for now, let me open a PR to pin this one library.

**Comment by opotowsky** [comment]
Well we don't have any procedures in place yet to update version pins, which is why I made the issue. But if you are cool with it, I'm cool with it.
