### ISSUE TITLE
Tests are leaving crumbs

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1442]
Last year I cleaned up all our unit tests so they don't pollute our working area with extra test files.  BUT, it looks like several unit tests have been added/modified that leave us with a dirty work env again. 

For instance, if you run all the unit tests in ARMI locally, you will find the following files in the ARMI home dir:

* [ ] `armiRun.code-timeline.png`
* [ ] `armiRun.h5`
* [ ] `armiRunRadialCoreMap.png`
* [ ] [coreAssemblyTypes1.png](https://github.com/terrapower/armi/blob/85d4f6e8af38f1901c1a20306d6b1d6b0c891ba6/armi/utils/tests/test_plotting.py#L54)
* [ ] [coreAssemblyTypes2.png](https://github.com/terrapower/armi/blob/85d4f6e8af38f1901c1a20306d6b1d6b0c891ba6/armi/utils/tests/test_plotting.py#L58)
* [ ] [ISOtopics.txt](https://github.com/terrapower/armi/blob/85d4f6e8af38f1901c1a20306d6b1d6b0c891ba6/armi/nuclearDataIO/tests/test_xsLibraries.py#L130)

These all need to be cleaned up. Possibly, those tests just don't make use of our [TemporaryDirectoryChanger](https://github.com/terrapower/armi/blob/85d4f6e8af38f1901c1a20306d6b1d6b0c891ba6/armi/utils/directoryChangers.py#L229), or they are not using it correctly.

**Comment by elprogramadorgt** [comment]
Hi @john-science, I want to help  with this issue, can you explain me? I already cloned the repo, do you want me to remove those test files?

**Comment by john-science** [comment]
Hello @elprogramadorgt !

The problem is that when you run the tests in armi:

```python
pytest armi

# or
pytest -n 4 armi
```

The above 6 files get created and are placed in the `armi/` home directory.  That's annoying.

In other tests we use our [TemporaryDirectoryChanger](https://github.com/terrapower/armi/blob/85d4f6e8af38f1901c1a20306d6b1d6b0c891ba6/armi/utils/directoryChangers.py#L229) to solve this problem. I'm hoping we can do the same for these files.

Does that make sense?

**Comment by elprogramadorgt** [comment]
Oh you want those file to be created in the new directory, is that correct ?

**Comment by john-science** [comment]
> Oh you want those file to be created in the new directory, is that correct ?

Yeah, the "TemporaryDirectoryChanger" creates a little test dir to run the tests in, and then if the tests pass, it deletes the directory.

This keeps our workspace clean, and stops a lot of confusion.

**Comment by elprogramadorgt** [comment]
Hi @john-science  I ran the project, with 

```
pytest armi
```
but it takes a lot of time doing the test.

Can you tell me the specific file or give me some instructions of how to fix this issue?

I would really like to help but I'm kind of lost here.

Regards

**Comment by john-science** [comment]
@elprogramadorgt If that's slow, try `pytest -n 4 armi`, that should run faster. (It runs the tests in parallel.)

As far as pointing at specific tests, you can see at the list of 6 files at the top of this file that I have made links to the test locations for three of them.  The other three I didn't immediately find.

**Comment by john-science** [comment]
@elprogramadorgt You got questions, man?  How's it going?

**Comment by john-science** [comment]
Okay, this ticket finally appears to be done. I ran the unit tests locally on a couple of different operating systems, and this came back clean:

```bash
git clean -xnd | grep -v pycache
```
