### ISSUE TITLE
armi.utils.reportPlotting:plotReactorPerformance has out of date parameters

### ISSUE THREAD

**Issue by cbroman-usnctech** [terrapower/armi#1450]
The plotting utility function ``armi.utils.reportPlottings:plotReactorPerformance`` has an outdated Reactor parameter named ``eFuelCycleCost`` causing ``getHistory`` function to fail. On line 70.  

```python
    try:
        data = dbi.getHistory(
            reactor, params=["cycle", "time", "eFeedMT", "eSWU", "eFuelCycleCost"]
        )
```

``plotReactorPerformance`` also has an input argument named ``history`` which defaults to ``None``. This variable is passed to the function ``xsHistoryVsTime`` as a required parameter on line 117.

```xsHistoryVsTime(reactor.name, history, buGroups, extension=extension)```

**Comment by john-science** [comment]
@cbroman-usnctech I would just remove that one string from that line of code.

Do you want to open a PR for it, or should I?

**Comment by cbroman-usnctech** [comment]
@john-science I can make a PR.
