### ISSUE TITLE
Remove unnecessary `isotopicDepletion` stub

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1458]
This file is not useful. If a user wants to use the `STACK_ORDER.DEPLETION` constant, they can just use it directly from the `interfaces` module. None of the other imports in this file are used.

https://github.com/terrapower/armi/blob/9da65879499bda3b9f1e9829e3d9f935275eeaa7/armi/physics/neutronics/isotopicDepletion/__init__.py#L15-L23

Unfortunately we have an internal plugin that directly imports `ORDER` from here. So we can't just delete this. But it should be slated for removal.

**Comment by keckler** [comment]
Same goes for the stub in `latticePhysics`:
https://github.com/terrapower/armi/blob/c7995865ca66d97eefaeb958148aa758358e479c/armi/physics/neutronics/latticePhysics/__init__.py#L15-L24

**Comment by john-science** [comment]
@keckler @albeanth 

Okay, I understand this file is mostly empty. And I would like to remove it.

I can only find one place where this stub is used downstream, and I have opened a ticket there. When THAT is cleaned up, we can happily remove this stub.

**Comment by john-science** [comment]
@keckler As we are going to move the entire `latticePhysics` package out of ARMI, I am not so concerned about the second stub you mention.
