### ISSUE TITLE
Docs Issue - Does not render on html

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1490]
While generating documentation for a downstream Application, I noticed that this little chunk does not render in the html docs. Haven't looked into this at all but just wanted to leave a note. 

https://github.com/terrapower/armi/blob/f5681d7162b100fa74e290f9a0f7c5e807076a54/doc/tutorials/making_your_first_app.rst?plain=1#L103-L107

![image](https://github.com/terrapower/armi/assets/18561046/4aad63c3-3603-4516-b2a3-3cd819142658)

**Comment by ntouran** [comment]
`armi-example-app` us supposed to be a submodule in the doc folder pointing to embedded repo https://github.com/terrapower/armi-example-app for this purpose, but it looks like it's gone, which broke this whole part of the docs. I'll check the commit history to see why/when it was removed.

**Comment by keckler** [comment]
Huh. I'm 99% sure that was an accident. I don't know of any reason why we can't have the example app as a submodule.
