### ISSUE TITLE
snapshotRequest attempts to copy deprecated file

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#1516]
https://github.com/terrapower/armi/blob/4f55d94d56cb81f3bd44714082c3295eea16853f/armi/operators/operator.py#L1160-L1169

The files with extension `*.flow_history.txt` and `*.pressure_history.txt` were presumably once being produced by a downstream thermal-hydraulics plugin. These files are no longer being produced, and apparently have not been for a long time. Based on the name, I can infer that the content of these files is now written to a file with the name `*.flow_requirements.txt`.

We should either change the `copyOrWarn` to copy `*.flow_requirements.txt`, or remove it altogether.

**Comment by john-science** [comment]
> I vote to remove both of these statements, as they are fully defunct.

And since ARMI does not make any reference to `*.flow_requirements.txt`, I think it would be awkward to reference that file here. 

Good find, @mgjarrett !

**Comment by jakehader** [comment]
I think it would be good to allow plugins to define which files should be copied since these files specifically are dependent on the TH solver needs internally.

**Comment by john-science** [comment]
> I think it would be good to allow plugins to define which files should be copied since these files specifically are dependent on the TH solver needs internally.

Hmm.... I'm trying to decide if this is a good idea, or not.

On the one hand, sure, I could add an argument or two and let people pass file paths around. Probably this isn't hard.

On the other hand, as a matter of design... do we want to build features into ARMI to help organize and run completely external, downstream code? Shouldn't it just the plugin's job to decide to copy a file when it wants to? Why would ARMI be involved in that?
