### ISSUE TITLE
Dead parameter `rotationDegreesCCW` in `Block.coords()`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1518]
If one specifies the `rotationDegreesCCW` parameter to `coords()`, it will either result in an error or do nothing with it:
https://github.com/terrapower/armi/blob/4f55d94d56cb81f3bd44714082c3295eea16853f/armi/reactor/blocks.py#L597-L607
https://github.com/terrapower/armi/blob/4f55d94d56cb81f3bd44714082c3295eea16853f/armi/reactor/blocks.py#L1620-L1634

I can't find any use of this parameter in any repos that I have access to. I'm not even sure what it would mean for the rotation of a block to impact its location, assuming that orientation is about the centroid of the block.

Extremely low priority, but just pointing it out.

**Comment by john-science** [comment]
I agree with Chris' assessment.  This parameter looks like it should be removable from both methods.

It's _possible_ that someone is passing unused values into one of those methods, positionally. But (a) unit tests would catch that, and (b) we'd want to know if people were trying to use this defunct parameter anyway.
