### ISSUE TITLE
Messed up docstring

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1531]
![image](https://github.com/terrapower/armi/assets/21959600/e12e138a-46f2-4699-93b4-e83a42eaf460)

**Comment by john-science** [comment]
Sorry, I don't mean to be obtuse.  Maybe it's just Friday.

What's wrong with this?

**Comment by keckler** [comment]
The parameters are wrong. They just took a sentence and gobbled it up. The docstring actually looks like this:
https://github.com/terrapower/armi/blob/9f2b322047af443fb96c3409c5afc91dcebdb5de/armi/reactor/reactors.py#L778-L796

There is only 1 real parameter. The others are coming from incorrect formatting in the docstring.

**Comment by john-science** [comment]
Yeah, sorry Chris, you're totally right.   Happily, it's an easy fix.

**Comment by john-science** [comment]
Fixed by the PR.
