### ISSUE TITLE
Assembly Rotation Cleanup

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1533]
There several rotation methods:
1. https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/assemblies.py#L1215
2. https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/assemblies.py#L312
3. https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/blocks.py#L1827
4. https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/blocks.py#L1902
5. https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/physics/fuelCycle/assemblyRotationAlgorithms.py#L76

It looks like they all boil down to the two methods on `blocks.py`, `rotate` and `rotatePins`. The docstring for `rotatePins` suggests that calling it on it's own does _not_ constitute rotation.
https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/blocks.py#L1928-L1932

That said, I think we should consider making `rotatePins` private and/or putting warnings in docstrings (on that method, assembly.rotatePins, and assemblyRotationAlgorithms.py::simpleAssemblyRotation) saying that it's an incomplete rotation.

**Comment by albeanth** [comment]
Additionally, `rotatePins` is fixed to increments of 60 degree rotations, while `rotate` is expected to be a flexible rotation. However, once `assembly.rotate` boils down to `blocks.rotate`, that flexible rotation angle needs to be in 60 degree increments
https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/blocks.py#L1839-L1844

**Comment by drewj-tp** [comment]
Should we remove `Assembly.rotatePins`? If you call `Assembly.rotate`, it will call `Block.rotate` for all contained blocks, which in turn (at least for hex blocks) calls `Block.rotatePins`, which could double rotate your pins.

**Comment by john-science** [comment]
> Additionally, `rotatePins` is fixed to increments of 60 degree rotations, while `rotate` is expected to be a flexible rotation. However, once `assembly.rotate` boils down to `blocks.rotate`, that flexible rotation angle needs to be in 60 degree increments
> 
> https://github.com/terrapower/armi/blob/7e1e16736b7082c2ce4892bb36243fb080c63a48/armi/reactor/blocks.py#L1839-L1844

Just a note: we DO definitely want `HexBlock.rotate()` to only rotate by increments of 60 degrees.  Though the generic `Block` class should be free of that.

We should make sure that `HexBlock` and `Block` are not confused in these `.rotate()` or `.rotatePins()` methods. In the past, ARMI made some bad assumptions that all assemblies were hex-based, and I have tried to squash those. But this seems like another potential case.

**Comment by drewj-tp** [comment]
Looking through the `assemblyRotationAlgorithms` code, I think we should use `Assembly.rotate` over `Assembly.rotatePins`. `Block.rotate` includes pin rotation. I couldn't find any direct usage of `Assembly.rotatePins` except for tests and places that call rotation algorithms. So not even direct usage on the last one

Potential plan for the clean up:

1. Make `Block.rotatePins` private
2. Remove `Assembly.rotatePins`
3. Replace all instances of `Assembly.rotatePins` in the `assemblyRotationAlgorithms` with `Assembly.rotate`

> Just a note: we DO definitely want HexBlock.rotate() to only rotate by increments of 60 degrees. Though the generic Block class should be free of that.
> 
> We should make sure that HexBlock and Block are not confused in these .rotate() or .rotatePins() methods. In the past, ARMI made some bad assumptions that all assemblies were hex-based, and I have tried to squash those. But this seems like another potential case.

Big agree
