### ISSUE TITLE
Can we remove FuelHandler.prepSearch?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1550]
It appears to me we should be able to remove the method `FuelHandler.prepSearch()`:

https://github.com/terrapower/armi/blob/0977ee48953e2099d434c6df32a1b184c7ae259f/armi/physics/fuelCycle/fuelHandlers.py#L207

Because it hasn't done anything but raise a `DeprecationWarning` in years:

https://github.com/terrapower/armi/blob/0977ee48953e2099d434c6df32a1b184c7ae259f/armi/physics/fuelCycle/fuelHandlers.py#L226-L230

I can find no downstream uses of this method either.

**Comment by albeanth** [comment]
Oh yeah. This hasn't been touched for a long time and just spits a DepracationWarning. I say time to remove the warning and just yank it!

**Comment by jakehader** [comment]
This might impact downstream fuel handling scripts internally. Maybe note this to @onufer

**Comment by john-science** [comment]
@onufer If there is some downstream code calling this and just getting a `DeprecationWarning`, let me fix that down stream code so it doesn't and we can safely delete this.

I guess the only other option is there are some downstream scripts which are sub-classing this and using it.  That would be a different situation.

**Comment by jakehader** [comment]
@john-science - I think it's been long enough that we could remove this and fix downstream if it causes an issue. I didn't mean to block removing by my comment.

**Comment by john-science** [comment]
I did as Jake suggested and removed this (now fully unused) method two weeks ago: https://github.com/terrapower/armi/pull/1845
