### ISSUE TITLE
Various tiny issues with MPI documentation

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1561]
1. What are the "before" values in this table referring to?
![image](https://github.com/terrapower/armi/assets/21959600/569b7451-25f8-40dd-829d-24baefc09504)
2. Reference to some [`twr_shuffle.py`](https://github.com/terrapower/armi/blob/ddce755e7509b6209b4479fe274b25327ee7d8e0/doc/developer/parallel_coding.rst#L110) file that doesn't exist
3. Multiple instances of ".:" in text, which is just a tiny grammatical issue

**Comment by john-science** [comment]
Ooof.  That (2) is nasty.

Is THIS why everyone was asking how to build MPI tests?   Because that example isn't copy/paste working.

Why would we bother having a half-working example script in the docs?

#embarassing  #i-didn't-write-it  #fixing-it-now

**Comment by keckler** [comment]
There are a number of things in that tutorial page that might be improved upon, including supplying working examples that one can execute.
