### ISSUE TITLE
Add new loadMinimalTestReactor() test method

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1563]
Our current function to create a reactor for unit tests is widely used in ARMI and the ARMI ecosystem:

https://github.com/terrapower/armi/blob/main/armi/reactor/tests/test_reactors.py#L139-L143

However, it loads a full reactor and is this rather slow if you are using it in thousands of unit tests. That's why we have this helper method:

https://github.com/terrapower/armi/blob/main/armi/reactor/tests/test_reactors.py#L203

It reduces the size of the reactor. Which doesn't speed up the "loading" part of the unit test, but it _does_ make a smaller reactor, which makes many unit tests faster.

What would be nice is if we had a new, faster function to generate a test reactor; something like `loadMinimalTestReactor()`. The idea is that it would generate a simple one-assembly reactor core, with only one block, and one parameter. And it would be even better if you could pass it a number of assemblies, blocks-per-assembly, and number of parameters.

The goal is to make loading times faster. But, also, the goal would be to replace as many full `loadTestReactor()` tests as possible with the new, faster version.

**Comment by albeanth** [comment]
I think `pickle` was employed at one point to try and help mitigate this issue. In my experience though this doesn't seem to help much. Not saying it _doesn't_ work, just that I haven't seen it leveraged much first hand. 
https://github.com/terrapower/armi/blob/87c61b903584eeb9efbf5129e080e9cd635af48c/armi/reactor/tests/test_reactors.py#L170

**Comment by john-science** [comment]
> I think `pickle` was employed at one point to try and help mitigate this issue...

Yeah, but that can only help with LOAD times. If people are running complicated code on the reactor core, say running it through the interface stack for a whole cycle, then the RUN time of that code depends on the size and complexity of the reactor core model.

That's my idea, anyway. Caveat emptor.

**Comment by john-science** [comment]
This ticket was solved by a recent PR: https://github.com/terrapower/armi/pull/1737
