### ISSUE TITLE
Convert specifyInputs from an interface staticmethod to a plugin hook

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#161]
This would be useful to be able to specify which inputs are a part of a plugin, since it's not a strict requirement that all plugins have interfaces defined.

**Comment by youngmit** [comment]
Hmm... but inputs _are_ case-specific... at which point you should have an Operator/Interfaces to guide the determination of what is "input". If we are going to say that there are new things that a plugin can bring along that are inputs _descriptive of the system itself_, regardless of the type of analysis being performed, then this is perhaps a deeper discussion.

Could you provide some motivation for why you need this?

**Comment by jakehader** [comment]
I was thinking of a possible scenario where settings could be used by a plugin directly to configure the reactor state outside of the context of needing an interface. There are already instances where we use a cs to do things or check things about the reactor state during the blueprints initialization (`afterContructionOfAssemblies`, `onProcessCoreLoading`) that have access to the cs, but are outside of an interface. In the case where our cs references another file (say as a part of a case suite) then this could fail if the say the path to an external file is not absolute. 

Maybe the solution here is to not make more things open on the plugin side of things, but require that any reactor modifications like the assembly construction, core processing, etc. actually live within an interface instead. This way the things don't happen to the reactor just because the plugin is imported, but rather because the interface is enabled within an improved plugin.

I think parameters, flags, etc are probably fine as a plugin hooks because they don't rely on settings.

Thoughts?

**Comment by jakehader** [comment]
After revisiting this request and understanding plugins better, it seems that this type of functionality could instead be achieved by introducing a new setting into the application within the plugin instead that defines a new input that is needed. The `specifyInputs` on the Interface serves a specific purpose based on case settings, so it should be left as is.
