### ISSUE TITLE
Remove unused `rotationDegreesCCW` argument

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1623]
While doing a review for #1619, I found that the argument `rotationDegreesCCW` is unused -- and I don't see any downstream projects that use it. So I think it's ripe for removal. 

https://github.com/terrapower/armi/blob/3d49274d8334b166e3a923770b4f4991333f6d69/armi/reactor/blocks.py#L597
https://github.com/terrapower/armi/blob/3d49274d8334b166e3a923770b4f4991333f6d69/armi/reactor/blocks.py#L1623

**Comment by john-science** [comment]
I checked downstream, and I can confirm that no one is using this argument.  This should is safe to remove.

**Comment by andfranklin** [comment]
Looks like this was recently removed. Ran `git grep rotationDegreesCCW` to confirm.
