### ISSUE TITLE
Document Flags

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#163]
We have sort of been firing from the hip on what `reactor.Flags` really mean, and how they ought to be used. I think it's time to get a little more formal/precise with their definition. Flags settings from #162 is getting us closer to the vision of Flags-as-description with settings to map Flags to specific behavior. We should codify this in the docs.

**Comment by jakehader** [comment]
We've had some discussions on this and the intent is that `Flags` can be used to define attributes of a composite, like `DUCT`, `FUEL`, `CLAD`, etc. as a way to differentiate between what the intended use of the composite will be within either the framework and/or plugins. 

When it comes to using `Flags` within the plugins, we are _not_ intending for them to be used to describe modeling behavior,  unless there is a specific setting that allows for the user to configure that behavior based on flags. One exception to this rule may be something like a `FuelHandler` plugin, where it may be obvious by the name of the plugin that the intent is to find the composites with `Flags.FUEL` and move them. Whereas if had a `Shuffler` plugin, we might want to have a setting to that describes the things can be shuffled/moved:

```
> cs["assemblyShuffleFlags"] = ["fuel", "control"]
> print(cs["assemblyShuffleFlags"]) 
> [Flags.FUEL, Flags.CONTROL]
```
