### ISSUE TITLE
Making our docstrings more consistent

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1633]
In our docstrings, we make use of two different ways to write "Warnings" and "Notes".  The first uses RST syntax:

https://github.com/terrapower/armi/blob/5879f956d6e57164ac84e7fd571be04a8a43fc29/armi/reactor/assemblies.py#L345-L346

And the second is to use the NumPy docstring syntax:

https://github.com/terrapower/armi/blob/5879f956d6e57164ac84e7fd571be04a8a43fc29/armi/reactor/assemblies.py#L1266-L1268

Personally, I like the `NumPy` docstrings better, because they are supported everywhere. And they are more readable in code. But I think the important thing is we need to make a decision and be consistent. I checked, and both render exactly the same in PDF and HTML:  [NumPy Example](https://terrapower.github.io/armi/.apidocs/armi.reactor.assemblies.html#armi.reactor.assemblies.Assembly.rotate) and [RST Example](https://terrapower.github.io/armi/.apidocs/armi.reactor.assemblies.html#armi.reactor.assemblies.Assembly.doubleResolution).  (Though, in that file, all the RST warnings are broken, as the RST syntax is apparently less clear.)

> We just need to pick: NumPy or RST Warning and Notes syntax?

**Comment by opotowsky** [comment]
NumPy is prettier to read. I vote numpy!

**Comment by keckler** [comment]
Numpy

**Comment by jakehader** [comment]
I agree with standardization of Docstrings. Does the `ruff` linter or another linter help to enforce this?

**Comment by partofthething** [comment]
Numpy does not have a generic `warning`. It has a [`Warnings` section](https://numpydoc.readthedocs.io/en/latest/format.html#warnings) that can be used in a class or method docstring. 

ReST has admonitions, of which `.. warning::` is one. It uses the standard rest directive syntax, which I hope everyone will soon enough know and love. The cool thing about it is that there are [lots of different admonitions](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives), and they can have different contexts and meaning throughout a documentation set:

> Admonitions: [attention](https://docutils.sourceforge.io/docs/ref/rst/directives.html#attention), [caution](https://docutils.sourceforge.io/docs/ref/rst/directives.html#caution), [danger](https://docutils.sourceforge.io/docs/ref/rst/directives.html#danger), [error](https://docutils.sourceforge.io/docs/ref/rst/directives.html#error), [hint](https://docutils.sourceforge.io/docs/ref/rst/directives.html#hint), [important](https://docutils.sourceforge.io/docs/ref/rst/directives.html#important), [note](https://docutils.sourceforge.io/docs/ref/rst/directives.html#note), [tip](https://docutils.sourceforge.io/docs/ref/rst/directives.html#tip), [warning](https://docutils.sourceforge.io/docs/ref/rst/directives.html#warning) and the generic [admonition](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions). (Most themes style only “note” and “warning” specially.)

Some sphinx themes make beautiful use of admonitions, like [sphinx-book-theme](https://sphinx-book-theme.readthedocs.io/en/stable/reference/kitchen-sink/admonitions.html):

![image](https://github.com/terrapower/armi/assets/5360219/f2e9645c-3b8e-4d67-9c7f-dd6143e03bd3)

They translate nicely to LaTeX for pdf as well.

I highly recommend that we use these standard ReST admonitions throughout the code, and use the Numpy `Warnings` section just as they're defined in numpydoc.

**Comment by opotowsky** [comment]
In the examples john linked, we have the numpy option rendering like: 
![image](https://github.com/terrapower/armi/assets/5347433/b72b9d53-e1ec-45a1-adac-17281faedc3b)

Which looks fine to me!

Note, his RST example actually renders WRONG:
![image](https://github.com/terrapower/armi/assets/5347433/ddfd1eea-7c26-4bcc-9efa-b1872fd00635)

I doubt that was the intent of:
![image](https://github.com/terrapower/armi/assets/5347433/11d0c42b-ac2d-4ba9-8306-76b53e954b46)

**Comment by ntouran** [comment]
> @ntouran Are you sure?

That other guy was apparently unaware of whatever part of numpydoc or docutils or something else? is rendering like that. Do we see any documentation of that happening? Is that a function of the active sphinx html theme? Do those render as `fancybox`'s in the PDF output?

I would just recommend we stick to documented features. Relying on what we see may not be stable if it's not defined somewhere.

**Comment by albeanth** [comment]
> I agree with standardization of Docstrings and I think we have `NumPy` in the majority of cases? Does the `ruff` linter or another linter help to enforce this?

Looks like this is an open item. https://github.com/astral-sh/ruff/issues/8425

But also looks like a separate validation could be set up https://numpydoc.readthedocs.io/en/latest/validation.html

I also like Numpy for things that exist - like warnings, notes, see also, etc. Just seems cleaner. But we _can_ use general rst admonitions for other things if we want to.

**Comment by ntouran** [comment]
I'm still trying to find how that otherwise undocumented `Warning` section is being rendered as an admonition. Haven't traced it down yet. I maintain that if the feature is not documented then we shouldn't rely upon it. 

Note that numpydoc people themselves use the admonition in their own docs. 

 https://github.com/numpy/numpydoc/blob/eb08110922fba1330daa40101386b87cc8a207ae/doc/format.rst?plain=1#L465

I'm checking the latex/pdf build as well. 

> Note, his RST example actually renders WRONG:

That same exact issue will occur if you try to put a note in the 

```
Warning
-----

.. note:: Blah
```

Section. To keep them separate, the

**Comment by ntouran** [comment]
I'll be damned: it is a fancybox in pdf! So this is getting processed somehow by docutils as an actual warning.

![image](https://github.com/terrapower/armi/assets/53948397/65e0bf12-02f1-42bb-bb16-2f25aa4a64cf)

**Comment by ntouran** [comment]
In any case, one major disadvantage I'd like to add of the mysterious and yet-to-be-indentified-as-not-a-bug "section" style instead of the normal "directive" style is related to what @john-science pointed out above: If you use the 'section' style, you _cannot cancel it without starting a whole other section!_

```rst
Warning
------
Blah blah blah This is a warning.

So anyway I was having a nice day. and this is not supposed to be a warning

uh oh this is still a warning! GAhh!
```

compare:

```rst
.. warning:: Blah blah blah this is a warning. 

So anyway I was having a nice day. and this is not supposed to be a warning

and yay it is not a warning!
```

**Comment by ntouran** [comment]
I just upgraded the doc libs to latest sphinx 7.2.6 and docutils 0.20.1 and the warning section still renders to an admonition as in the earlier deps tagged right now, so I guess that's good; it's not just a bug or something, or at least not one that has been fixed yet.

**Comment by ntouran** [comment]
Found it! This warning section -> Admonition translation [is facilitated by the Napoleon extension by this line](https://github.com/sphinx-doc/sphinx/blob/fa290049515c38e68edda7e8c17be69b8793bb84/sphinx/ext/napoleon/docstring.py#L226). The validity of using a `Warning` [section is defined here.](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections)! 

Ok so yeah I now agree that there's nothing wrong with putting a `Warning` section in a docstring. 

In terms of coming up with a standard, I would say that we shouldn't disallow the normal admonitions and should encourage their usage whenever they make sense: complex docstrings, narrative `rst` files, etc.

**Comment by john-science** [comment]
Nick convinced me there are time where both formats are useful.

I will close this ticket.
