### ISSUE TITLE
ARMI cannot be installed in editable mode with pip<22.1

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#1639]
Installation instructions for editable install not working: Since it does not have a `setup.py` nor a `setup.cfg`, it cannot be installed in editable mode. 

Docs say:

https://github.com/terrapower/armi/blob/0668e8ca1f52c67dc7074c25a0723e1073ddce4d/doc/user/user_install.rst?plain=1#L86-L90

But if you do this, you get an error:

```bash
(venv) $ pip install -e .[test]
Obtaining file:///home/nick/code/armi
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///home/nick/code/armi has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

I am using `pip==22.0.2`.

**Comment by ntouran** [comment]
Hmm, according [to this](https://stackoverflow.com/a/69711730/1279313), we may need to require setuptools 64

**Comment by ntouran** [comment]
Upgrading pip to 23.3.2 works!

`python -m pip install --upgrade pip`

We should reflect this somewhere in the setup docs I guess.

**Comment by ntouran** [comment]
The other thing we can do is just add a stub setup.py or setup.cfg which will restore the old behavior. I'll make a PR.

**Comment by john-science** [comment]
> Upgrading pip to 23.3.2 works!
> 
> `python -m pip install --upgrade pip`
> 
> We should reflect this somewhere in the setup docs I guess.

Great!

> The other thing we can do is just add a stub setup.py or setup.cfg which will restore the old behavior. I'll make a PR.

I would rather not do this.  We just spent a solid year having dozens of meetings to move ARMI to the more modern `pyproject.toml` format, and moving a `setup.py` or `setup.cfg` back into the repo is going to give all the people who fought against the `pyproject.toml` file ammunition.

**Comment by ntouran** [comment]
> We just spent a solid year having dozens of meetings to move ARMI to the more modern `pyproject.toml` format, and moving a `setup.py` or `setup.cfg` back into the repo is going to give all the people who fought against the `pyproject.toml` file ammunition.

I would be happy to talk to anyone about specific concerns about why having a stub setup.py that allows easy and broad installations to still work. It's pretty standard practice and has basically zero real downsides that I'm aware of. Can take offline if you prefer.

**Comment by caiodallaqua** [comment]
Hi there! Unable to reproduce this as well.

By the way, I'd like to suggest using quotes in such commands across the documentation, for shell portability.

Square brackets have special meanings in zsh so `pip install -e .[test]` breaks there. 
Changing it to `pip install -e ".[test]"` works for zsh, bash and sh.
