### ISSUE TITLE
It may be nigh time to replace wxPython

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1721]
#1719 and #1720 had some changes with wxPython for our docs build. When #1719 was merged, it broke the docs build because wxPython is not (really) supported by Linux per the PyPI entry. 

https://pypi.org/project/wxPython/
![image](https://github.com/terrapower/armi/assets/18561046/bd89c391-c063-4838-9c23-ba160b87d6aa)

Technically the readme for the source code has some description of how to get it to work for Linux, but it looks fragile. That said, I think we should find replacements for wxPython.

**Comment by john-science** [comment]
I am going to close this ticket (for now, at least, it might get opened back up), while I do some discovery:

https://github.com/terrapower/armi/discussions/1722

**Comment by partofthething** [comment]
Wxpython is very much supported on linux. that's what the POSIX entry is. Most normal linux distros have it in their package managers. 

![image](https://github.com/terrapower/armi/assets/5360219/24f4baa0-4c2c-4d40-9714-8ab0bba8d26a)

**Comment by albeanth** [comment]
@john-science just curious, what ever came of this? we/you/@opotowsky were having issues installing wxPython on linux, no?

**Comment by partofthething** [comment]
If that's an issue, I'd be happy to help anyone install wxpython on any modern (2006+) POSIX-related linux distro if needed. I have gotten it through package managers and also built it from source many times.

**Comment by opotowsky** [comment]
No it was CI via GH actions that failed. I haven't ever tried to install it on linux myself
