### ISSUE TITLE
Add descriptions for `copyFilesFrom` and `copyFilesTo` case settings

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1727]
We have two case settings with no descriptions:
![image](https://github.com/terrapower/armi/assets/21959600/8d3878c2-aa42-4b47-983d-15d85722d1ac)

These settings need descriptions. From what I can tell, `copyFilesFrom` can be a list of any length, but then `copyFilesTo` needs to be either of zero-length, length-1, or the same length as `copyFilesFrom`. This should be described for the user. It would also be good to know when the file copying takes place so the user knows when the new files will be available.

**Comment by john-science** [comment]
I have often wondered if these two settings are actually _used_ by anyone. This is one of those situations where I would have to pole my user base to ask.

The functionality is pretty general, and could copy any files, but the use-case presented in the comments makes me think this feature is only here for a particular user 8 years ago:

https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/bookkeeping/mainInterface.py#L96-L100

But, you're right, if I leave this feature in the code base, I might as well fill in the description fields.

**Comment by john-science** [comment]
@keckler I will do that. Sure. 

Out of curiosity, are people actually USING this feature of ARMI?
