### ISSUE TITLE
Force Settings to have descriptions

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1734]
I have [often](https://github.com/terrapower/armi/issues/1727) had to field questions about settings, because they did not have proper descriptions. This is a sign that settings without descriptions are problematic for our user base.

I propose we add an assertion to the settings constructor, to demand that a setting has a valid description, as is being done with [parameters](https://github.com/terrapower/armi/issues/1348).

This is an API-breaking change for our downstream repos, so we will have to take that into account with our timeline.

The following ARMI settings do not currently have descriptions:

* [x] [debug](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/settings/fwSettings/globalSettings.py#L449-L451) - Is this unused
* [x] [burnupPeakingFactor](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/settings/fwSettings/globalSettings.py#L423-L429)
* [x] [freshFeedType](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/settings/fwSettings/globalSettings.py#L523-L529)
* [x] [jumpRingNum](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/physics/fuelCycle/settings.py#L103-L105) 
* [x] [levelsPerCascade](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/physics/fuelCycle/settings.py#L106-L112)
* [x] [removePerCycle](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/settings/fwSettings/globalSettings.py#L665-L667)

> Update: All settings in ARMI now have descriptions.

**Comment by ntouran** [comment]
Seems like a good suggestion. 

FWIW all those settings (except `debug`) are fuel management control parameters that have been used in the past during multi-objective parameter sweeps to hunt for and optimize the fuel management programs.

**Comment by john-science** [comment]
@ntouran Is it possible [debug](https://github.com/terrapower/armi/blob/3b822bc34c88706f629a7d6b4f53b96aca64d30c/armi/settings/fwSettings/globalSettings.py#L449-L451) is entirely unused, and has been replace by `verbosity` and `branchVerbosity`?

**Comment by jakehader** [comment]
Is this ticket completed @john-science?

**Comment by john-science** [comment]
> Is this ticket completed @john-science?

Nope!

All the `Settings` in ARMI have descriptions now. But there is still a `DeprecationWarning` in place for settings that don't.  This ticket will be completed when we move the current `DeprecationWarning` to a hard error.

A cursory inspection of important downstream projects says I could make that change now, but I will give it another ~2 weeks to give people warning that we are about to make this change.

Thanks!
