### ISSUE TITLE
Replace `tabulate` with `prettytable`

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1749]
### Discussed in https://github.com/terrapower/armi/discussions/1747

<div type='discussions-op-text'>

<sup>Originally posted by **opotowsky** June 25, 2024</sup>
`tabulate` is a dead project and `prettytable` is not. But it's pretty extensively used here and downstream with the `runLog` module. </div>

**NOTE**: Because `tabulate` is a dead project, it is stopping us from moving to Python 3.11.

**Comment by john-science** [comment]
I have no particular love for `tabulate`, sure I'm game.

People might get touchy that you change the formatting of their log tables. But, that's not a big change, so I'm okay with it.

**Comment by jakehader** [comment]
I'm not sure if replacing is necessary if `tabulate` functions as needed. What is the threshold for updating stale dependencies? I say if there is a clear bug or problem we have with `tabulate` then sure, but if it's just because the project is "dead" I'm not sure. Maybe there is something to be said about unmaintained projects and potentially vulnerabilities in open source packages with the more recent Linux / JavaScript supply chain attacks / hacks though.

See: `xz`, `polyfill`

**Comment by opotowsky** [comment]
@jakehader `tabulate` is blocking us from moving to python 3.11, so it's way above the threshold for "must remove". (Given the speedups we hope to see with switching)

**Comment by jakehader** [comment]
Thanks for the context. That wasn't in the discussion so I didn't know about an issue with pip or how it's blocking.

**Comment by opotowsky** [comment]
> Thanks for the context. That wasn't in the discussion so I didn't know about an issue with pip or how it's blocking.

True that! I think I must've offered the context in an offline chat before making the discussion. I'd need to retrace my steps to remember exactly how it's failing for us but it's something really lame

**Comment by jakehader** [comment]
Sounds good - I'm fine with it if there is an issue with `tabulate` but if you can find the specific problem it would be good to provide that context in the ticket before updating so we can look back into the change / reason for the change.

**Comment by opotowsky** [comment]
will do. Just need time to get back to my python311 work.

**Comment by opotowsky** [comment]
We want to move to a project that isn't deprecated and we can rely on updates being pushed to PyPI. Just helps keep things running over the longer term.

**Comment by john-science** [comment]
Interestingly, I found the `tabulate` is only one Python file, and it's MIT licensed.

So I pulled the 2,800 line file out of that repo, and pulled it into an ARMI branch. It worked like a charm.

I also found I could reduce it to 1,500 lines, as there are a ton of features we don't want. 

So... that might be an option.

**Comment by opotowsky** [comment]
I'm a fan! either ingest it or fork it. Don't matter to me!
