### ISSUE TITLE
`composite.getReactionRates()` doesn't work on the `core` level

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1754]
Something appears to be wrong with this method:
https://github.com/terrapower/armi/blob/9d6e2b0097ac2e203c7726fdaa44a1a854648938/armi/reactor/composites.py#L3060-L3092

I recently loaded up a database and tried to examine some reaction rates as follows:
```python
>  r.core.getReactionRates("U235")
Loading microscopic cross section library `ISOTXS`
 {'nG': 0, 'nF': 0, 'n2n': 0, 'nA': 0, 'nP': 0, 'n3n': 0}

> r.core.getAssemblyWithStringLocation('002-001').getReactionRates("U235")
{'nG': 4.219163274625927e+16,
 'nF': 1.5933660772471552e+17,
 'n2n': 86100493155576.52,
 'nA': 0.0,
 'nP': 0.0,
 'n3n': 0}

>  r.core.getAssemblyWithStringLocation('002-001').getReactionRates("U238")
{'nG': 1.3747239159395538e+17,
 'nF': 2.0985393232144132e+16,
 'n2n': 706063666454843.1,
 'nA': 0.0,
 'nP': 0.0,
 'n3n': 0}
```

It doesn't make sense that the returned reaction rates for the core as a whole are zero, but non-zero values are returned for individual assemblies from the same core.

**Comment by john-science** [comment]
If there is a problem, I would guess the problem is here:

https://github.com/terrapower/armi/blob/9d6e2b0097ac2e203c7726fdaa44a1a854648938/armi/reactor/composites.py#L3086

At a glance, it appears this method only looks "one child deep", and doesn't try to recurse into deeply-nested structures (which, of course, a `Core` is).

**Comment by john-science** [comment]
Okay, it looks to me like `Composite.getReactionRates()` called `Composite._getReactionRates()`, which assumes you are lower than the `Core` in the heirarchy:

https://github.com/terrapower/armi/blob/f6ee15003bc8d85db89dda87eb453b98414b0181/armi/reactor/composites.py#L3040-L3043

It really looks like it expects the `Core` to be an ancestor (parent or above), and when you pass it a `Core` object and it just falls through this exception here (which returns all zeros):

https://github.com/terrapower/armi/blob/f6ee15003bc8d85db89dda87eb453b98414b0181/armi/reactor/composites.py#L3047-L3049

**Comment by keckler** [comment]
I agree with your assessment.

Another thing to put on your radar, in case we want to guard against it. I have seen that some blueprints name their assemblies something like `Inner core fuel`. This automagically gives the assembly the `CORE` flag. And then the logic that you highlight in your comment above will actually get tripped up, in particular the line
```python
self.getAncestorWithFlags(Flags.CORE).lib
```

The code will try to get a `lib` from the _assembly_ object, and obviously it will fail in this. The upshot is that more all-zero dicts are returned.
