### ISSUE TITLE
Need single=True for deprecation warnings

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1755]
I'm getting a lot of these, and think a single=True should resolve!
![image](https://github.com/terrapower/armi/assets/5347433/d27f8ecc-8d94-4908-b857-c84f71281fa5)

**Comment by john-science** [comment]
Oh, no!

That's hideous. 

But at least it's easy to fix.

**Comment by john-science** [comment]
Actually, I already did, from Day 1:

https://github.com/terrapower/armi/blob/b3a9992c4db122a061d407096fdcd762c0e86fc5/armi/settings/setting.py#L119-L121

So, is your issue above from concatenated from parallel processes?

**Comment by john-science** [comment]
Another solution here is just to fix the settings, and add descriptions.  For that effort, please see this ticket; https://github.com/terrapower/armi/issues/1734

**Comment by opotowsky** [comment]
Yep -- it appears I have misunderstood the use of `single=True`

I think your alternative path is better. Once that is closed this can be closed 😊
