### ISSUE TITLE
`buildCommand` only works on windows and probably doesn't belong in ARMI

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1772]
This method in the `Case` class won't work with other cluster tooling, e.g, slurm:

![image](https://github.com/terrapower/armi/assets/5347433/a1678ef8-8684-47d6-877c-f6b01c7c1a20)

**Comment by john-science** [comment]
I agree.

This method is not general enough to be in ARMI.  And it is not widely used in the ARMI ecosystem, so it will be easy to move out of ARMI.
