### ISSUE TITLE
Move to "import numpy as np"

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1775]
In 17 places in the repo we use the community standard numpy import:

https://github.com/terrapower/armi/blob/40c6d290814f12501aa8aacc9bf90a726a86726a/armi/utils/mathematics.py#L20

But in 69 places in the repo, we use the other import:

https://github.com/terrapower/armi/blob/40c6d290814f12501aa8aacc9bf90a726a86726a/armi/interfaces.py#L32

This is Low Priority, but I prefer we be consistent. And, as a preference, I would prefer we us `as np`.

**Comment by NeuralNoble** [comment]
As this is labeled as Low Priority, I'd be eager to take on this task to help maintain consistency in the repository. Could you please assign me to this issue? I'm keen to make my first contribution to open source and contribute positively to the project.
Looking forward to your guidance on how to proceed.

**Comment by MohitKambli** [comment]
Hello!
Hope you're doing well.
Could I possibly contribute to this issue too?
I literally got so involved in the issue, that I absolutely missed on giving an update to this ticket.
This is how the result of pytest command looks like for the files changes mentioned on the left:

![image](https://github.com/user-attachments/assets/d8e4f938-62e9-4915-9686-0bb6b496ed1a)

I just hope these code changes met the necessary requirement as mentioned in the issue description above.
Extremely sorry if I missed something.
If at all there is a chance of a combined contribution, then that would be just fine as well.
My deepest apologies for the trouble being caused.

Thanks and Regards,
Mohit Kambli

**Comment by jakehader** [comment]
> Hello! Hope you're doing well. Could I possibly contribute to this issue too? I literally got so involved in the issue, that I absolutely missed on giving an update to this ticket. This is how the result of pytest command looks like for the files changes mentioned on the left:
> 
> ![image](https://private-user-images.githubusercontent.com/31406633/348135384-d8e4f938-62e9-4915-9686-0bb6b496ed1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MDY4MTQsIm5iZiI6MTcyMDgwNjUxNCwicGF0aCI6Ii8zMTQwNjYzMy8zNDgxMzUzODQtZDhlNGY5MzgtNjJlOS00OTE1LTk2ODYtMGJiNmI0OTZlZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE3NDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYmFmMzhmNmRiNDMwM2I4MDk1ODgyNjc0ZTM1NzdhNjExMjlkODYzYTczMjRhZjM0YmIyZjJhZWRiMjI3NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dDfSgS6gt8VxolEw_1Rbn5_WKfUpEBi-VvNqk96FCEw)
> 
> I just hope these code changes met the necessary requirement as mentioned in the issue description above. Extremely sorry if I missed something. If at all there is a chance of a combined contribution, then that would be just fine as well. My deepest apologies for the trouble being caused.
> 
> Thanks and Regards, Mohit Kambli

@MohitKambli - I think @NeuralNoble beat you to the changes and Pull Request - if you have additional comments on that pull request, you're welcome to make suggestions. Thanks for your general interest in helping out and please feel free to look at other open issues. Please let us know if you're interested in others and comment on them so we can either assign them to you first or provide additional clarity on the issue.

Thanks!
