### ISSUE TITLE
Add reactor time to stdout summaries

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1781]
@opotowsky, @john-science - As I am looking at the open PR, I'm wondering now if we should also add anything about the reactors current "time" in the simulation as well. Cycle and Time node are great, but deciphering the cycle and node relationship to time step and cycle length could be helpful to users. @keckler I'm curious if this would helpful for you in multi cycle benchmarks like FFTF and EBR-II.

_Originally posted by @jakehader in https://github.com/terrapower/armi/issues/1748#issuecomment-2210954513_

**Comment by keckler** [comment]
I migrated this comment here so that it didn't get lost when #1748 was closed.

I agree with the suggestion above.

I would also propose that the cycle name gets added to the stdout summaries at each time node. With the detailed cycle histories, users are now able to enter a cycle name. Real reactors typically give their cycles names, and those are useful when searching through the results.

**Comment by john-science** [comment]
@opotowsky I know you just merged a PR with a vaguely similar goal.  Do you have any thoughts here, before I plow ahead?

**Comment by opotowsky** [comment]
@john-science yes the comment above came from that PR review. Chris seeks to extend that work, and I agree it's a great idea! Go for it!
