### ISSUE TITLE
ARMI param `core.p.powerDecay` Unused

### ISSUE THREAD

**Issue by wcscherer** [terrapower/armi#1793]
It appears that `core.p.powerDecay` is not updated or used anywhere in the ARMI ecosystem (only `Assembly` and `Block`-level `powerDecay` parameters are set and used). It may make sense to remove this parameter in the future if no projects end up requiring it. 

https://github.com/terrapower/armi/blob/31befeb1c749177ec61e9f7cb1104a6df0e66892/armi/reactor/reactorParameters.py#L358-L362

**Comment by john-science** [comment]
After some research, I determined this parameter is used downstream. So I am just going to close this.
