### ISSUE TITLE
Issues with running ARMI behind a web service

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#18]
If you try running ARMI behind a web service, there are a few issues:
* The `expanduser` line in `context.py` does not work if the user does not have a home directory (e.g. the typical `www-data` utility user). In fact, the `e` exception isn't defined there.
* The `signal` calls in `__init__.py` fail if they're called in threads

**Comment by youngmit** [comment]
The `expanduser` issue is pretty straightforward; we just need to decide where we want to put stuff in these cases. Perhaps `/tmp/armi-[PID]` or similar?

The `signal` issue is vexing. How are you invoking armi from your web service?

**Comment by ntouran** [comment]
I'm going to close this now as wontfix until it becomes an issue again just since it's pretty low priority.
