### ISSUE TITLE
Update pytest version

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#1802]
The pinned version of pytest is getting a little out of date ([7.0.0](https://github.com/terrapower/armi/blob/86b53f0f26f237a493f80bb551284a9672f66d17/pyproject.toml#L80) -> [8.3.2](https://docs.pytest.org/en/stable/changelog.html#pytest-8-3-2-2024-07-24)). Pytest's changelog indicates that this version is about [2.5 years old](https://docs.pytest.org/en/stable/changelog.html#pytest-7-0-0-2022-02-03).

Given the fairly limited used of pytest in ARMI and pytest's [backward compatibility policy](https://docs.pytest.org/en/stable/backwards-compatibility.html#backwards-compatibility-policy), I don't expect a version update to cause breaking changes.

I'm happy to work on this. Thoughts @john-science?

**Comment by john-science** [comment]
Actually, the ARMI project already _does_ use the latest version of `pytest`.  You can see the dependency in our `pyproject.toml`:

https://github.com/terrapower/armi/blob/86b53f0f26f237a493f80bb551284a9672f66d17/pyproject.toml#L80

So, if you look at [a recent ARMI CI build](https://github.com/terrapower/armi/actions/runs/10152144402/job/28072895487), you will see:

```
Collecting pytest>=7.0.0 (from armi==0.4.0)
  Downloading pytest-8.3.2-py3-none-any.whl.metadata (7.5 kB)
Collecting pytest-cov>=4.0.0 (from armi==0.4.0)
  Downloading pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting pytest-xdist>=3.0.0 (from armi==0.4.0)
  Downloading pytest_xdist-3.6.1-py3-none-any.whl.metadata (4.3 kB)
```

> ARMI is already using `PyTest 8.3.2`!

The idea here is that ARMI should try to support as wide a range of versions of Python and its Python dependencies as possible. That makes it easier for our users bases to do what they want, and not be constrained by ARMI.

Does that make sense?
