### ISSUE TITLE
Vertical symmetry domain type

### ISSUE THREAD

**Issue by AidanMcDonald** [terrapower/armi#1805]
I am running a case with a vertically symmetric core/reflective bottom plane (the C5G7 benchmark from the tutorial, see [reference](https://www.oecd-nea.org/science/docs/2003/nsc-doc2003-16.pdf) page 14). It appears that this is not supported by a `DomainType` or `BoundaryType` in ARMI. Implementing this is not as trivial as it seems - it may involve adding another attribute to `SymmetryType`, which I assume could confuse things downstream. This may not even be worth implementing for a case that apparently don't come up often (and isn't strictly necessary, the full vertical geometry could be specified), but I wanted to at least open it for discussion.

**Comment by keckler** [comment]
This is interesting. In "real" reactors, there is not often axial symmetry due to temperature differences. But certainly there are cases where axial symmetry does apply (as in many zero power reactors like your example).

I think supporting this would require quite a bit of work, but I'd say it is surely not impossible. I'm not sure there is a strong impetus to get this done anytime soon, though.

**Comment by john-science** [comment]
> In "real" reactors, there is not often axial symmetry due to temperature differences.

@AidanMcDonald After thinking about this some, and looking at the code, I think Chris here hit the nail on the head. It seems like this symmetry would only ever be got at the "Beginning of Life" state of the reactor. Certainly, I wouldn't know how to constrain downstream thermo-dynamics modeling to enforce such a truth.

It all seems a little non-physical.

**Comment by AidanMcDonald** [comment]
@john-science, @keckler, thanks for the insights. Everything you've said pretty much agrees with what I was thinking. Non-physical is a good way to put it: I'm only using vertical symmetry for a benchmark problem, and even then it's not strictly necessary. I'm only using it (rather than defining the full vertical geometry) to make the case look more like the problem definition. I currently have this option implemented as a custom setting in the OpenMC plugin (that I suspect will only be used in the C5G7 benchmark case) which works fine.

I think we're in agreement that the marginal usefulness of this feature doesn't justify the effort of including it in ARMI, so I'm happy closing the issue.
