### ISSUE TITLE
`report` entry point input arguments are broken

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#1816]
The `report` entry point is supposed to take specific `(cycle, node)` combinations as an input argument, or a `max_node` or `min_node`. However, all of these inputs are parsed as strings, and are then later an attempt is made to compare `(cycle, node)` as a `tuple` to these strings. The check of the form `(int, int) not in str` fails because the two types cannot be compared.

https://github.com/terrapower/armi/blob/d7028672d345aadada35815ecbce8f2fdb0761aa/armi/cli/reportsEntryPoint.py#L120-L134

This code is not unit-tested at all, and it has presumably been broken for a long time.

**Comment by john-science** [comment]
Are you saying this is a new bug since we added the EOC timestep to the DB?

https://github.com/terrapower/armi/pull/1090

**Comment by mgjarrett** [comment]
> Are you saying this is a new bug since we added the EOC timestep to the DB?
> 
> #1090

No, I think this has probably been broken for a long time but we haven't noticed it. I haven't ever used this feature, and I don't know of anybody else using it, but I just stumbled upon it recently and it seems like it could be a useful feature.
