### ISSUE TITLE
Document runLog single=True feature

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1829]
This should be added to the `runLog` section of the ARMI docs:

https://terrapower.github.io/armi/developer/tooling.html#logging-with-runlog

It goes here in the docs:

https://github.com/terrapower/armi/blob/main/doc/developer/tooling.rst#logging-with-runlog

**Comment by john-science** [comment]
@albeanth Just FYI.  I'll do it soon.

**Comment by partofthething** [comment]
Could also/in addition be expanded upon in the api docs, which list it but don't explain it https://terrapower.github.io/armi/.apidocs/armi.runLog.html
