### ISSUE TITLE
Add `--skip-inspection` flag to `compare-suites` CLI

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1840]
Most of the time we don't want this. So let's allow folks to skip the inspection

OR! Make that the default!!!! And make a `--do-inspection` flag 😀

**Comment by john-science** [comment]
@opotowsky I don't fully understand the request; I need a touch more information.

You want to add a flag to `compare-suites` that does what?

The `compare-suites` CLI just calls [CompareSuites](https://github.com/terrapower/armi/blob/ccd59500bcda7df230f9ab8db8044814434ab2eb/armi/cli/compareCases.py#L39), which calls yada yada yada, just runs [compareDatabases](https://github.com/terrapower/armi/blob/ccd59500bcda7df230f9ab8db8044814434ab2eb/armi/bookkeeping/db/compareDB3.py#L162).  The logic is super simple, just... compare to databases.

**Comment by opotowsky** [comment]
Oh! No when that happens the settings inspection happens, and it's really aggravating. If someone just wants to compare DBs, they definitely don't care about settings inspection.

**Comment by opotowsky** [comment]
You get a gazillion of these: 
![image](https://github.com/user-attachments/assets/09bb1f63-19b0-460f-89bc-5fcbacd26df2)

**Comment by opotowsky** [comment]
Haha I noticed the label switch. I think the labels are confusing:
![image](https://github.com/user-attachments/assets/bec0af77-731b-4d8d-be50-51acd130daab)

**Comment by john-science** [comment]
@opotowsky I don't see that in the code, so I will have to keep digging. I think it will be quite an annoying little change, having to touch a dozen intermediary methods.  But I'll look and see if I can find a more minimal pathway to do what you want.

I believe the _idea_ makes sense. If two DBs were created from runs with different settings, that brings into question the whole idea of them being comparable.

**Comment by opotowsky** [comment]
The `modify` CLI has a skip inspection flag:
![image](https://github.com/user-attachments/assets/99bfc66c-b4e0-4fbc-9c37-1d48a44c1400)

Oooh I think I see it! BRB

**Comment by opotowsky** [comment]
The CLI calls `suite.discover` x2 (for `ref` and `src`). Inside `discover` we have this:

https://github.com/terrapower/armi/blob/71992d89c316f10b495776adbcdd870b3203fd0a/armi/cases/suite.py#L116-L119

And `checkInputs` is what we want to skip. So an arg could be added to discover to skip that step (optionally), and then you backfill as needed into the CLI in `compareCases.py`!

**Comment by john-science** [comment]
@opotowsky Good find. I can do that.
