### ISSUE TITLE
Automatically close stale PRs?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1848]
There is a GitHub Action that would allow us to close PRs that have been open too long:

* https://github.com/actions/stale

I notice [the MOOSE team using it](https://github.com/idaholab/moose/blob/7c55923541c02ca9abfdef6b90b73e77eab77467/.github/workflows/stale.yml). Their plan, which I propose to emulate, is to warn people their PR is getting stale after 100 days, and then 7 days later close the PR.

**Comment by john-science** [comment]
@opotowsky @albeanth Thoughts?

**Comment by albeanth** [comment]
Makes sense to me. 

I wonder if something similar could be done for issues. Maybe not close, but ping the originator and/or you, John. See if it's still relevant or not.

**Comment by john-science** [comment]
> Makes sense to me.

Cool!

> I wonder if something similar could be done for issues...

Yup, I could do that. Some tickets are backlogged not because they are stale and should be closed but because they just lost the "cost-benefit" analysis for a couple releases. So I don't think closing them is exactly right.  Food for thought though, yeah.

**Comment by opotowsky** [comment]
YES FOR ISSUES! I make them then forget about them

Fine for PRs too.

**Comment by albeanth** [comment]
> YES FOR ISSUES! I make them then forget about them

Just to be clear, not close, but ping. Yeah?

**Comment by opotowsky** [comment]
Yes, pings are useful. Closing probably a bit too heavy handed
