### ISSUE TITLE
State policy on linking to GitHub issues in code in developer guide

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1864]
We don't link to PRs or Issues in the code.

The idea is that either that information is important enough to write in a docstring (or the docs), or it's not.

_Originally posted by @john-science in https://github.com/terrapower/armi/pull/1852#discussion_r1752260095_

I agree with the sentiment. It's just not something that exists in the developer guide so you don't know it's a rule until you break it.

**Comment by john-science** [comment]
ok
