### ISSUE TITLE
Move Core class to its own file

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1869]
The `reactors.py` file is like 2700 lines long, and it contains:

* `class Reactor` ~ 200 lines
* `class Core` ~ 2500 lines

There is a little cross-importing to handle, but we can sort that out easy enough.

**Comment by albeanth** [comment]
If the plan is to have the Reactor class also link to SFP and other ex-core structures, you could change `Reactor` to `Plant` or something. That's more accurate in the grand scheme of things. 

That would be a _much_ bigger headache of a change, but something to consider.

**Comment by john-science** [comment]
> If the plan is to have the Reactor class also link to SFP and other ex-core structures, you could change `Reactor` to `Plant` or something. That's more accurate in the grand scheme of things.

That's an idea. But, where do we draw the line at what is a "reactor"? Are the IVS and EVSTs part of the reactor?

**Comment by john-science** [comment]
I am holding off on this change until the current [ex-core PR](https://github.com/terrapower/armi/pull/1891) is merged, so we don't have a merge conflict nightmare.
