### ISSUE TITLE
Reactor.moveList is a dictionary

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1873]
Okay, so, the attribute `Reactor.moveList` is a dictionary:

https://github.com/terrapower/armi/blob/5a41b25fe9f262acb03347923443c4a2808837db/armi/reactor/reactors.py#L296

So, that is a terrible variable name, actually. This is a good example of "don't put the type in the variable name", which is an important rule in software.

We even have a comment to this affect:

https://github.com/terrapower/armi/blob/5a41b25fe9f262acb03347923443c4a2808837db/armi/reactor/reactors.py#L1889-L1890

1. Rename this variable to `moves`.
2. There is only one repo downstream that directly references this variable (janus).

**Comment by opotowsky** [comment]
hahaha but the list is a dict oh no!
