### ISSUE TITLE
Building docs spits out many sphinx-needs warnings

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1876]
I was working through building docs locally and I kept seeing this error
```
/home/runner/work/armi/armi/armi/__init__.py:docstring of armi:1: ERROR: Unknown directive type "impl".

.. impl:: Settings are used to define an ARMI run.
    :id: I_ARMI_SETTING1
    :implements: R_ARMI_SETTING

    This method initializes an ARMI run, and if successful returns an Operator.
    That operator is designed to drive the reactor simulation through time steps to
    simulate its operation. This method takes in a settings file or object to
    initialize the operator. Whether a settings file or object is supplied, the
    operator will be built based on the those settings. Because the total
    collection of settings can be modified by developers of ARMI applications,
    providing these settings allow ARMI end-users to define their simulation as
    granularly as they need.
```
Turns out, this also appears in our [deployment builds](https://github.com/terrapower/armi/actions/runs/10840758667/job/30083661628#step:8:1832)

I've tracked down the source of that error to not including `sphinx_needs` extension in the sphinx extension configuration

https://github.com/terrapower/armi/blob/abd1db4adfa0c536f9bf9f08f0f1e8b74b1cd0d7/doc/conf.py#L256-L279

But, curiously, if I add that line to our `conf.py` with
```diff
$ git diff
diff --git a/doc/conf.py b/doc/conf.py
index d2135cfa..2990671a 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -276,6 +276,7 @@ extensions = [
     "sphinxcontrib.plantuml",
     "sphinx_rtd_theme",  # needed here for loading jquery in sphinx 6
     "sphinxcontrib.jquery",  # see https://github.com/readthedocs/sphinx_rtd_theme/issues/1452
+    "sphinx_needs",
 ]

 # Our API should make sense without documenting private/special members.
```
I get this error
```shell
$ make html
Running Sphinx v5.3.0

Extension error:
Could not import extension sphinx_needs (exception: cannot import name '__version__' from 'pygls' (/anfhome/anjohnson/codes/armi/.venv/armi/lib64/python3.9/site-packages/pygls/__init__.py))
```
Building straight from main with `pip install ".[docs]"` 

Notable packages on windows and linux
```
esbonio                           0.16.1
pygls                             1.2.1
Sphinx                            5.3.0
sphinx-data-viewer                0.1.4
sphinx-gallery                    0.13.0
sphinx-needs                      1.2.2
sphinx-rtd-theme                  1.2.2
sphinxcontrib-apidoc              0.3.0
sphinxcontrib-applehelp           1.0.8
sphinxcontrib-devhelp             1.0.6
sphinxcontrib-htmlhelp            2.0.5
sphinxcontrib-jquery              4.1
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-plantuml            0.25
sphinxcontrib-qthelp              1.0.7
sphinxcontrib-serializinghtml     1.1.10
sphinxext-opengraph               0.8.2
```

**Comment by drewj-tp** [comment]
The pygls problem might be related to how it gets built / installed by pip?

https://github.com/openlawlibrary/pygls/issues/189

**Comment by john-science** [comment]
`sphinx-needs` is not an ARMI dependency.

This error shouldn't occur if you are building the ARMI docs.

**Comment by drewj-tp** [comment]
Okay, update. Not a bug because I have some weird internal dependency problems.

But, the fact that building docs produces tons of warnings from sphinx that the `impl` directives aren't recognized isn't great. These directives are declared by `sphinx_needs` so if we add that to our `conf.py`, those might go away.

Or they might turn into actual errors since the requirements for those directives don't exist in public armi. 

If we wanted to make it such that building armi docs locally doesn't make all those warnings, we could hijack those directives with a custom [`directive`](https://www.sphinx-doc.org/en/master/development/tutorials/extending_syntax.html). That way when sphinx sees those directives, it uses something shipped in armi not `sphinx_needs` (which we may keep out of the extensions list for this reason)

**Comment by john-science** [comment]
I'm going to take this over for a hot minute. I just tried, and writing a new directive from scratch to fix this problem was dead easy. NBD.
