### ISSUE TITLE
Provide a way to query parameters with a category

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1884]
In order to do better rotation of assembly / block parameters, we need a way to find out what parameters are rotatable. The plan proposed in #1860 // #1877, I propose a new category `rotatable` for parameters.

We don't have a _simple_ way to check if a parameter has a given category. Something like `Parameter.atLocation`

https://github.com/terrapower/armi/blob/abd1db4adfa0c536f9bf9f08f0f1e8b74b1cd0d7/armi/reactor/parameters/parameterDefinitions.py#L420-L422

A corollary would be something like `Parameter.hasCategory`? Uses could check `Parameter.categories` but let's make something a little simpler

**Comment by john-science** [comment]
Drew and I talked about this, and I think it seems like a fine feature.

I'm on board.

**Comment by drewj-tp** [comment]
This was added in #1899
