### ISSUE TITLE
Allow a way to efficiently iterate over some parameters

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1898]
(Pulling a discussion out of https://github.com/terrapower/armi/pull/1877#discussion_r1769233599)

We have a lot of parameters. Not all of them are used in every location. For example, in working on `HexBlock.rotate`, lots of things needs to be rotated. Two cases are
1. Parameters defined on the midpoints and vertices of a hexagon (e.g., with `ParamLocation.CORNERS`)
2. Parameters defined on the children of the block (e.g., with `ParamLocation.CHILDREN`)

For parameters meeting condition 1, we have

https://github.com/terrapower/armi/blob/3dd2763535f0a5694215a0f1f876db49eea3a11c/armi/reactor/blocks.py#L2041-L2042

`ParameterDefinitions.atLocation` involves iterating over all parameters, making an intermediate `ParameterDefinitionCollection`, [extending](https://github.com/terrapower/armi/blob/3dd2763535f0a5694215a0f1f876db49eea3a11c/armi/reactor/parameters/parameterDefinitions.py#L492-L506) to it, twice (once for corners, once for edges).
And then iterate again over the combined names.

In #1877, I added a helper onto `HexBlock` that allowed a pattern like
```python
for param in self._getParamsWhere(lambda pd: pd.atLocation(ParamLocation.CORNERS)):
    pass
```
This allowed for one iteration over all the parameters and used [`filter`](https://docs.python.org/3/library/functions.html#filter) to only produce parameters that met the condition.

This seems more generally useful so let's add it.

## Where?

I don't think it should be added to a composite. Those already have too many methods.

I'm thinking a `ParameterCollection` so you can do something like
```python
assem = r.core[0]
assem.p.where(lambda pd: pd.hasCategory("neutronics"))
```
There could be some confusion about `where` needing a condition for the **values** of the parameter collection, not so much their definitions. The same way [`numpy.where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where) and [`pandas.where`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.where.html#pandas.DataFrame.where) behave. 

So maybe a `ParameterDefinitionCollection`? Then you'd need to do
```python
assem.p.pDefs.where(pd: pd.atLocation(ParamLocation.EDGES))
```
that feels a bit better? Grabbing parameters where their *definition* meets a certain category. Yeah, I think I like that better

**Comment by john-science** [comment]
I like this idea!

I would be happy with:

```python
assem = r.core[0]
assem.p.where(lambda pd: pd.hasCategory("neutronics"))
```

The original idea I had something like:

```python
assem.p.where(categories, locations)

# or

assem.p.where(categories, locations, names)
```

where we just allow people to add (optional/empty) sets/lists of all three. Your idea is more flexible. If the ONLY things people ever used were categories and locations, I think the second version would be better.  Less flexible though.

(I'm just a chatting. I'm not planning on dying on any hills today.)
