### ISSUE TITLE
Clean up deprecated setting from `armiRun.yaml`

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1901]
This is the list I get when I try to run the case:

1. `maxRegionDensityIterations`
2. `eqRingSchedule`
3. `maxFlowZones`
4. `transientForSensitivity`
5. `BOL`
6. `percentNaReduction`
7. `nodeGroup`
8. `economics`
9. `clusterExclusive`
10. `max2SigmaCladIDT`

**Comment by john-science** [comment]
@opotowsky I see the following settings are used by some internal project, but should clearly not be in ARMI:

* `clusterExclusive` - cluster
* `nodeGroup` - cluster
* `maxRegionDensityIterations` - equil
* `eqRingSchedule` - equil
* `BOL` -rxcoeffs
* `percentNaReduction` -rxcoeffs
* `maxFlowZones` - th
* `max2SigmaCladIDT` - th

And these settings appear to have been entirely abandoned and I can't find them anywhere:

* `economics`
* `transientForSensitivity`

Also, I note with some interest, some of these settings appear in other ARMI unit test settings files as well. So, this clean up could happen all around ARMI.

**Comment by opotowsky** [comment]
Thanks for taking this on! I was like "maybe I'll do it when I'm bored in a meeting"

Ok this is interesting. I was running unit tests in a plugin and got these. but i agree this shouldn't be in armi. We should definitely run internal testing with this change before merging though. Some unit tests may rely on these settings (and can easily be added, but it could be tedious)
