### ISSUE TITLE
BU vs time plot prints useless/incorrect results

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1902]
One of the plots generated by default in ARMI is burnup vs time. The same plot also includes DPA vs time. In all of my runs, they contain all zeros:
![image](https://github.com/user-attachments/assets/2b9e92d6-0d60-4630-80f9-d6018389818d)

The plotting is done by this function:
https://github.com/terrapower/armi/blob/59c392c1a6aa98e19c9955c88ca1a6106d1bcc35/armi/utils/reportPlotting.py#L216-L265

That function is quite fickle and incorporates a number of assumptions that are not often met by any old reactor that somebody might build. In those cases, you end up with a useless plot like the one that I showed above. Besides being useless, the plot is just wrong/misleading.

I would advocate moving highly-specific plots like this into the application that actually might use it (if any).

**Comment by john-science** [comment]
@keckler Is this problem new?  For debugging purposes, it would be helpful to know if this worked 2 months ago.

> I would advocate moving highly-specific plots like this into the application that actually might use it (if any).

Yeah, I think this is the real solution. I am not actually a big fan of having a million hyper-specific plots in the repo. They are too hard to test and document, and it's hard to tell if anyone has used them in the past 3 years.

> Do you know where you would want to move this plot?

**Comment by keckler** [comment]
I am actually not sure if this problem is new or not. I would ask @mgjarrett if he's seen this same problem with any Natrium depletion calculations.

**Comment by drewj-tp** [comment]
Maybe related #267 ?

**Comment by drewj-tp** [comment]
> > I would advocate moving highly-specific plots like this into the application that actually might use it (if any).
> 
> Yeah, I think this is the real solution. I am not actually a big fan of having a million hyper-specific plots in ARMI. They are too hard to test and document, and surely no one outside TerraPower uses them. (@drewj-tp Am I right about that?)

I would file that into the "ARMI does too much" category and having ARMI native do fewer plots is better

**Comment by john-science** [comment]
@keckler @mgjarrett Who actually USES this?

Can I move this into someone's project?

Maybe your internal ARMI-based `Application` can subclass this `ReportInterface`, and add plots like this downstream, where people actually want them enough to support them?

**Comment by john-science** [comment]
@keckler Looking at the code here, it _really_ doesn't do much except `pyplot.plot()` some values.

So, perhaps the problem is upstream in `plotReactorPerformance()`. 

I guess I would need to see a working example of the error to debug further.

**Comment by keckler** [comment]
In the particular case of the plot of BU vs time, the problem is that ARMI assumes that the core parameter `maxBuI` will be set to something meaningful. That parameter is pulled within `plotReactorPerformance()`:
https://github.com/terrapower/armi/blob/59c392c1a6aa98e19c9955c88ca1a6106d1bcc35/armi/utils/reportPlotting.py#L47-L116

`maxBuI` is apparently supposed to be "Maximum burnup seen in any igniter assemblies":
https://github.com/terrapower/armi/blob/dad0117c9aeb118cf4418ab70154e28c761b871d/armi/reactor/reactorParameters.py#L444-L448

So now we're starting to get pretty specific, assuming that any old reactor will have "igniter" assemblies. That is certainly not true.

`maxBuI` is set here:
https://github.com/terrapower/armi/blob/dad0117c9aeb118cf4418ab70154e28c761b871d/armi/reactor/cores.py#L2202-L2214

So in essence, your reactor is assumed to have assemblies with one of those three specific combinations of flags. This is just not something that is guaranteed to be true for any generic reactor. This assumption is fundamentally why this plot is fragile, and in my case, misleading.

More broadly, I just don't see any reason for ARMI to be making plots like this for every run. That is a larger discussion, though.
