### ISSUE TITLE
Need to close plots after they are generated

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1904]
It looks like this PR missed the plots produced here:
https://github.com/terrapower/armi/blob/59c392c1a6aa98e19c9955c88ca1a6106d1bcc35/armi/reactor/converters/blockConverters.py#L458-L493

This function is called by our internal XS generation plugin, and I am seeing these plots clash with other plots during the run.

@john-science FYI

_Originally posted by @keckler in https://github.com/terrapower/armi/issues/1302#issuecomment-2374366932_

**Comment by john-science** [comment]
Ugh, I believe the tangled web of plots people have hap-hazardly thrown into ARMI actually means that someone downstream of this plot was adding to it, so if you put in a `plt.close()`, other plots would break in our internal runs.

So, I can test again, but my guess is this is still blocked by some intern project.  #deep-breaths
