### ISSUE TITLE
Parameters package documentation

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1916]
3 things that came to me from a user:

## First thing

There are a few pages on parameters in the UM, but there is no link to the extremely useful parameters package docstring: https://terrapower.github.io/armi/.apidocs/armi.reactor.parameters.html

The reactor data model (In the Dev Manual) does link to parameters. But I think it should also be linked in the UM when parameters are being discussed. Can we add this link there as well?

## Second thing

They also asked me how one could get a parameter with its units. Can we show `param.units` and a use case of https://github.com/terrapower/armi/blob/main/armi/reactor/parameters/parameterDefinitions.py#L308? 

## Third thing

The instructions here:

https://github.com/terrapower/armi/blob/34619dfa7991454d45d5d61e9002bea766a353a3/doc/user/manual_data_access.rst?plain=1#L28

Have `o.r`. But in the UM sec 3.2.2, `r - db.load(stuff)` is right before that. 

![image](https://github.com/user-attachments/assets/e41e1358-d5d1-4b87-af39-dff59207a1e9)

So a user following the docs has `r` and not `o.r`. Can we change to `r` (with an option to explain one may have one or the other?)

**Comment by opotowsky** [comment]
I can take this ticket, just wanted an OK on the UM changes.

**Comment by john-science** [comment]
Okay, so.

If you have a `ParameterDefinition`, it fully defines the units.  But if you just have a Parameter on a `Block`, or something, you can't get the units.

The situation here is simple.  We use units to DEFINE things, but when code is running putting a string that says "kg/cm^3" next to every variable for every parameter would make our `Reactor` object 10x larger. Likewise, we don't want to store those strings in the DB.

**Comment by john-science** [comment]
Okay, 1 at a time:

1. More Parameter information?

What exactly do you want here?  

2. Parameter Units:

If you have a `ParameterDefinition`, it fully defines the units.  But if you just have a Parameter on a `Block`, or something, you can't get the units.

The situation here is simple.  We use units to DEFINE things, but when code is running putting a string that says "kg/cm^3" next to every variable for every parameter would make our `Reactor` object 10x larger. Likewise, we don't want to store those strings in the DB.

3. `o.r.X`

Sure, that should just be `r.X`.

**Comment by opotowsky** [comment]
> 1. More Parameter information?
> 
> What exactly do you want here?

I just want to link to the parameter docstring in one additional place. It's natural to want to read about accessing parameters when you're given the parameters in the UM. 

> 2. Parameter Units:
> 
> If you have a `ParameterDefinition`, it fully defines the units. But if you just have a Parameter on a `Block`, or something, you can't get the units.
> 
> The situation here is simple. We use units to DEFINE things, but when code is running putting a string that says "kg/cm^3" next to every variable for every parameter would make our `Reactor` object 10x larger. Likewise, we don't want to store those strings in the DB.

Yep. Maybe we can just add an example of this into the docstring? I'll see where it's appropriate to add. 

> 3. `o.r.X`
> 
> Sure, that should just be `r.X`.

I think it would be fine here to discuss that you may have `o.r` or `r` depending on how one loaded the reactor. If you're following the UM, you have `r`. But there are just as many ways to get `o.r`.
