### ISSUE TITLE
Docstring for Block.getPinCoordinates incorrectly implies hex-only

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1922]
The docstring states

https://github.com/terrapower/armi/blob/f1f3dbea05c2564404a03d8e053f72c2af15daa9/armi/reactor/blocks.py#L1585-L1586

but the implementation is focused on the spatial locators attached to the children of the block

https://github.com/terrapower/armi/blob/f1f3dbea05c2564404a03d8e053f72c2af15daa9/armi/reactor/blocks.py#L1590-L1595

**Comment by john-science** [comment]
Good call.  It looks to me like the comment about need Clad is sufficient.

We can remove this `Notes` section.
