### ISSUE TITLE
Provide a method for a block to report its input height

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1924]
> Our team opinion here is we need a method that can go up to the blueprints and get the T=0 heights from a block.

This method would have other benefits outside this plot, e.g., axial thermal expansion between hot and as fabricated / neutral stress heights of blocks.

_Originally posted by @drewj-tp in https://github.com/terrapower/armi/issues/1158#issuecomment-2392102394_

**Comment by drewj-tp** [comment]
Feels kind of yucky, but
```python
reactor = b.parent.parent.parent
designs = reactor.blueprints.assemDesigns
heights = designs[b.parent.getType()].height
inputHeight = heights[b.parent.index(b)]
```
_should_ work

**Comment by john-science** [comment]
Perhaps something like:

```python
try:
    reactor = b.parent.parent.parent
except AttribuiteError:
    return None

if isinstance(reactor, Reactor):
    designs = reactor.blueprints.assemDesigns
    heights = designs[b.parent.getType()].height
    return heights[b.parent.index(b)]
else:
    return None
```

Just thinking aloud.
