### ISSUE TITLE
tabulate still included as dependency even though it's internalized

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1944]
Still picked up with `pip install .` because it's in the pyproject.toml

https://github.com/terrapower/armi/blob/c6f46e5d04dc265e7a8e470fdd1977c9a4e16e3e/pyproject.toml#L48

But we incorporated tabulate into `armi.utils.tabulate` in #1811 // #1749

**Comment by opotowsky** [comment]
Wow eagle eye!

We left it in while downstream plugins were being converted. It is finally ready for removal as of today!

**Comment by john-science** [comment]
Thanks Drew!

As Arrielle said, this was not a ticket because the purpose for leaving that dependency is internal and not to be discussed in this venue.  And it will be removed today.

**Comment by john-science** [comment]
This ticket was closed with the PR: https://github.com/terrapower/armi/pull/1948
