### ISSUE TITLE
Use or remove detailAssemLocationsBOL

### ISSUE THREAD

**Issue by drewj-tp** [terrapower/armi#1993]
The [ARMI docs](https://terrapower.github.io/armi/user/inputs.html#detail-assemblies
) indicate you can specify which assemblies you want to get the "detail" treatment with `detailAssemLocationsBOL`

>The detailAssemLocationsBOL setting is a list of assembly location strings (e.g. 004-003 for ring 4, position 3). Assemblies that are in these locations at the beginning-of-life will be activated as detail assemblies.

I can look at my blueprints file and more easily infer the location of the assembly. Seems helpful!

But this setting is not used anywhere in the codebase.

The alternative for specifying which assemblies you want the detail treatment is to provide the `detailAssemNums` setting, which requires you to know what number ARMI will assign to your assembly.

I believe the `detailAssemLocationsBOL` setting has value because it's easier (in my limited experience) to ID the assemblies I want by their location. Otherwise, I need to open up my reactor in memory and find the assemblies I want, grab their number parameter, and use those instead. 

Additionally, the `assemNum` parameter has no context around it. If I send the blueprint to someone for inspection, how do they know what assemblies got the detail treatment?

Finally, `assemNum` is less permanent. If I add more assemblies to my reactor, the assembly number might change. I guess this depends on how we assign the number (0 is center or 0 is on the outside) so maybe not?

---

P.S. coming in a little hot b/c I just tried to follow the docs to do a thing and the simulation did not do what the docs indicated they should do

**Comment by john-science** [comment]
Over in   @albeanth  is making a related change:

https://github.com/terrapower/armi/pull/1992

> History Tracker: "detail assemblies" are now fuel and control assemblies.

**Comment by albeanth** [comment]
We should talk about the whole history tracker module sometime soon... it's one of the more legacy modules in ARMI (and as such is questionably documented, tested, etc) and is making a resurgence in work that myself and @drewj-tp are doing.

**Comment by john-science** [comment]
@drewj-tp 

> But this setting is not used anywhere in the codebase.

That is not strictly true.  That setting is designed for the `HistoryTrackerInteraface`:

https://github.com/terrapower/armi/blob/dad0117c9aeb118cf4418ab70154e28c761b871d/armi/bookkeeping/historyTracker.py#L155-L171

But, because of the above, it is also used in the database migrations:

https://github.com/terrapower/armi/blob/dad0117c9aeb118cf4418ab70154e28c761b871d/armi/migration/m0_1_6.py#L60-L74

**Comment by john-science** [comment]
I also find this setting used quite heavily downstream.

**Comment by drewj-tp** [comment]
Tabling this for some more investigation. Signs indicate I jumped the gun too early and this is user error.
