### ISSUE TITLE
Can `mockRunLogs` support testing for errors strings?

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#2000]
I've seen stuff like this in ARMI and downstream:
![image](https://github.com/user-attachments/assets/f8003111-a6b2-48bc-8cae-77e38e6aeb0e)

People THINK they are testing an error but that line is actually never getting run. the `assertRaises` exits successfully once the error is hit. 

I think it would be cool to support this. 

I think it would look something like this:

```python
# current code
with self.assertRaises(Exception) as e:
    _diffSpecialData(refData4, srcData5, out, dr)
    self.assertIn("Unable to unpack special data for paramName", e)

# new code
with mockRunLogs.BufferLog() as mock:
    with self.assertRaises(Exception):
        _diffSpecialData(refData4, srcData5, out, dr)
    self.assertIn("Unable to unpack special data for paramName", mock.getStderr())
```

this might be a bad example since it's not loading a reactor or something but do you see what I'm getting after?

**Comment by john-science** [comment]
I'm not sure I understand the request. We have this all over ARMI:

```python
with mockRunLogs.BufferLog() as mock:
    self.assertEqual("", mock.getStdout())
    testName = "test_thing"
    runLog.LOG.startLog(testName)
    runLog.LOG.setVerbosity(logging.WARNING)

    # run your code that does SOMETHING with an error
    mockLog = mock.getStdout()
    self.assertIn("my special string", mockLog)
```

There are two situations I can imagine:

1. The error being raised does not have an associated `runLog.error("Whatever")` that comes before it. In which case, no we won't be supporting that. That tool only reads `runLog` statements.
2. The error being raised has a `runLog.error("my string")`.  In which case this is already supported:

```python
with mockRunLogs.BufferLog() as mock:
    self.assertEqual("", mock.getStdout())
    testName = "test_thing"
    runLog.LOG.startLog(testName)
    runLog.LOG.setVerbosity(logging.WARNING)

    with self.assertRaises(IOError):
        # run your code that does SOMETHING with an error
    mockLog = mock.getStdout()
    self.assertIn("my special string", mockLog)
```

So... the entire question comes down to "Is there a `runLog.error()` before the `raise Error` statement. If there is, great, we support that. If there isn't... I mean, `MockRunLog` is wildly the wrong tool. We would have to build something from scratch.

**Comment by opotowsky** [comment]
ahhhh gotcha
i think we should just close this ticket. i think you have it handled in the other ticket
