### ISSUE TITLE
Sort imports using ruff

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#2021]
I have tried the [ruff import tools](https://docs.astral.sh/ruff/rules/#isort-i), and I think they are going to work for us.

I tried it on a bunch of files, and it seems like it would work.

This solution was suggested by @drewj-tp , but I figure it would also have saved @mgjarrett some time in the past, too.

**Comment by john-science** [comment]
@opotowsky This is an easy PR, but I guess I am going to wait until the day after the release to make it happen.

**Comment by drewj-tp** [comment]
Locally, running `ruff check --select I --fix` on select files helps in a pinch

**Comment by john-science** [comment]
> Locally, running `ruff check --select I --fix` on select files helps in a pinch

After this PR, you will be able to do:

> ruff check . --fix

And that will include imports along with all the other stuff.
