### ISSUE TITLE
Make example showing how to make blueprints objects in a script

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#225]
To potentially help with #223, we should make a new example (in the gallery? in blueprints docs?) that shows how to build reactor inputs from a script by using Blueprints objects. This is likely a better option than writing out yaml code directly for script-generated ARMI inputs. 

For example, let's make a script that builds a few basic reactor parts and then either:
* Generates the input files
* Builds the ARMI objects

**Comment by ntouran** [comment]
@veeshy this is [live now online here.](https://terrapower.github.io/armi/gallery/framework/run_programmaticReactorDefinition.html#sphx-glr-gallery-framework-run-programmaticreactordefinition-py). hopefully it helps.

**Comment by veeshy** [comment]
Yup this looks great, thanks for the example!
