### ISSUE TITLE
Add SHEM-based neutron energy group structures

### ISSUE THREAD

**Issue by sombrereau** [terrapower/armi#237]
When using DRAGON to generate multigroup cross sections, one should use neutron energy group structures that snap to the SHEM361 energy structure because that's the "fine group structure" for open source nuclear data for DRAGON.

- There should be an energy spectrum that's analogous the ARMI33, but snapped to the SHEM361 rather than the ANL2081
- Having the SHEM361 structure will be good for modeling thermal spectrum reactors

**Comment by jakehader** [comment]
Closed with #238
