### ISSUE TITLE
How to override default settings in a plugin?

### ISSUE THREAD

**Issue by veeshy** [terrapower/armi#242]
I'd like to change the default `CONF_MATERIAL_NAMESPACE_ORDER` in my plugin to be `["usnc.materials", "armi.materials"]`, but I'm not sure where to do that. Trying to (re)add that entry in my plugin settings with `defineSettings()` gives an error that I can't redefine the name.

**Comment by sombrereau** [comment]
I'm assuming you guys have a USNC specific armi app.  Some where before you configure (e.g. armi.configure(app=UsncApp()?)), you can configure your materials name space order like this:
```
import armi
from armi import materials

materials.setMaterialNamespaceOrder([
    "usnc.materials",
    "armi.materials"
])
```

**Comment by veeshy** [comment]
Ah, not a setting override for this, thanks for that snippet, works as desired

**Comment by youngmit** [comment]
yeah, material namespace order is not really a proper `Setting`, since there's a little more magic to how material classes are discovered/imported. Sorry for the confusion!
