### ISSUE TITLE
Remove jagged numpy arrays

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#246]
The [latest release of NumPy]( https://github.com/numpy/numpy/releases/tag/v1.24.0) has deprecated the jagged array treatment that we are using in the database when writing parameter data.

https://github.com/terrapower/armi/blob/36fe1bced3b817d6d76e66cf99dd355219993e63/armi/bookkeeping/db/database3.py#L841-L887

Until now, we have detected jagged data (and some other strange cases) by converting to a numpy array first, then checking its data type to see if it is `object` and figure out what to do from there (handle `None` values, pack jagged arrays, etc).

Notes
-----
Also, ARMI cannot support Python 3.12 with the older versions of NumPy we are forced to use for Jagged arrays. So this ticket is what is keeping ARMI from supporting Python 3.12.

**Comment by theJollySin** [comment]
This seems like something I could handle.

And you're totally right, performance is my only real concern here.

**Comment by john-science** [comment]
I implemented a pure-Python solution for this.  It's fine, but slow.  I think the real solution might be we wait until NumPy makes the change and then just catch the error they throw. It only needs to be caught in a few places. 

I can give it another whack, but NumPy has a lot of built-in logic for how to convert lists-of-sets-of-dicts to arrays. And a lot of special-case handling that, while it makes good sense, is slow to replicate in pure Python, for instance: handling of `None`s.

**Comment by scottyak** [comment]
Perhaps [Awkward Array](https://github.com/scikit-hep/awkward-1.0) can help? From their README:

> Awkward Array is a library for nested, variable-sized data, including arbitrary-length lists, records, mixed types, and missing data, using NumPy-like idioms.
> 
> Arrays are dynamically typed, but operations on them are compiled and fast. Their behavior coincides with NumPy when array dimensions are regular and generalizes when they're not.

...

> Not only is the expression using Awkward Arrays more concise, using idioms familiar from NumPy, but it's much faster and uses less memory.
> 
> For a similar problem 10 million times larger than the one above (on a single-threaded 2.2 GHz processor),
> 
> the Awkward Array one-liner takes 4.6 seconds to run and uses 2.1 GB of memory,
> the equivalent using Python lists and dicts takes 138 seconds to run and uses 22 GB of memory.

`awkward` seems to be well-maintained with a strong community around it. If it's ok to include `awkward` as a dependency, I think the next step would be for someone to try porting the pure-Python logic over to `awkward`.

How does that sound?

**Comment by jakehader** [comment]
@john-science / @ntouran - Good video on `awkward` https://youtu.be/WlnUF3LRBj4

**Comment by john-science** [comment]
@scottyak  @jakehader  Thanks for the library idea! I'll check it out.  My primary concern is performance here, if it performs well against NumPy, than this is great.  My second question, of course, is how big a lift it will be to put in the code base; is it a drop-in replacement, or a huge change.  So I'll have to look at that.

Thanks for the info!

**Comment by scottyak** [comment]
Awesome! If you don't see any obvious problems, I might be able to get a
draft PR out next week.

**Comment by john-science** [comment]
@scottyak  Sure, go for it!

If this is more of a drop-in than some giant replacement, this could be a huge win.

My guess is that we would only need to use this library at the places where we are writing TO H5 files, but potentially we would also need to isolate all the reading FROM cases as well. 

Either way, we don't need to replace all NumPy math in the repo with such things, just those places where we deal with H5 files.

**Comment by john-science** [comment]
Okay, the version in `setup.py` has been bumped to 3.6+.  And everyone seems okay with it.

**Comment by scottyak** [comment]
I think you meant 3.7+, and yes, thank you!

**Comment by scottyak** [comment]
Unfortunately, I wasn't able to work on this issue this past week, and probably won't be able to for a foreseeable time :(

**Comment by john-science** [comment]
**WARNING**!

NumPy just dropped support for jagged arrays, so we are suddenly stuck with only relic versions of NumPy:

* [Ticket](https://github.com/terrapower/armi/issues/1036)
* [PR](https://github.com/terrapower/armi/pull/1035)

We NEED a long term solution that is something other than just being stuck with an old version of NumPy forever. The solution will have to be:

* This ticket.
* Not writing jagged arrays to the Database in Some way
* Making all Jagged arrays rectangular by filling them in with a special None/Null value, we can use elsewhere.

**Comment by ntouran** [comment]
We could consider thinking about "database4" if we wanted to, which would attempt to remove shape-based specializations from the database and support an arbitrarily nested tree, supporting #1008.

**Comment by john-science** [comment]
I looked into this back in the day.  Aside from not being super easy to do, any pure-python solution I tried immediately caused performance hits, when compared to the uber-fast C-NumPy library.

So, my gut reaction is there won't be an easy fix for this.  Perhaps Nick is right, though that makes supporting the lastest NumPy quite a bit lift for us.

Though, NumPy is so critical for us, I think this ticket is worth giving some real thought.

**Comment by drewj-usnctech** [comment]
So we've found after mixing armi and a lot of other python + conda packages, that this upper bound can be problematic in two ways

1. It can take package solvers like conda and mamba a long time to solve an environment looking for numpy >=1.21,<=1.23.5
2. Some environments, especially with more complex dependencies, can fail to resolve

We can get around these in the conda environment stage by not pinning the numpy upper bound. But because armi pins the upper version, and we install armi with `pip install /path/to/armi`, pip may install a totally new version of numpy, pandas, matplotlib, etc. This leads to two environments as the pip changes don't inform the conda environment, so it may think there is a different numpy version than actually used. [relevant xkcd is painfully relevant](https://xkcd.com/1987/)

Now this might not be urgent because numpy 1.23.5 came out in November 2022 and 1.24 in December. But wanted to keep this on people's radar

**Comment by jakehader** [comment]
Thanks @drewj-usnctech. This would be some refactor of the database and it just hasn't been an immediate priority, but I am sure that @ntouran and @john-science will be able to take a look soon. I agree that this pinning is most unfortunate and came pretty unexpected to us.
