### ISSUE TITLE
python segfaults unless h5py is imported with armi

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#257]
In the process of upgrading ARMI (thanks to all your fantastic PRs 😁) I found myself in a very strange predicament. This doesn't seem to impact any CLI calls like `armi run` which is great. Probably because `h5py` gets picked up when interacting with database files. But I felt like elevating this would hopefully help other people

Using Python 3.7.10 installed in a fresh conda environment, I keep getting segfaults when python (or ipython) exit. I can still work in an ipython or python environment, but the segfault appears at exit, possibly due to https://github.com/terrapower/armi/blob/259c91e200dc0f2a8ddf27258478d96de6412f78/armi/__init__.py#L344-L345 ?

Using `zsh 5.8 (x86_64-apple-darwin20.0)`
```zsh
% python -c "import armi"
zsh: segmentation fault  python -c "import armi"
```
and 
```bash
bash3.2$ bash --version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
bash-3.2$ python -c "import armi"
Segmentation fault: 11
```
```zsh
% python
>>> import armi
>>> print("hello world")
hello world
>>> exit()
zsh: segmentation fault  python
```

`python -c "import h5py; import armi"` and the reverse `python -c import armi; import h5py` work, discovered after digging through #249 https://github.com/terrapower/armi/blob/f702a89174cbe53a2a39343e680fd02ce65b9c60/armi/conftest.py#L38-L42 

## Steps

- Checkout f702a89 or later
- Install new h5py>3 with pip or conda: `conda install numpy\<1.19.4 h5py\>3`
- Upgrade ARMI
- Navigate to a new directory (not really necessary but forces python to use installed armi vs. local)
- `python -c "import armi"`

**Comment by youngmit** [comment]
Thanks for the report! I've actually been looking into this myself. The conftest import was there because i knew it was causing issues with out tests, and i sort of suspected pytest, but turns out it was causing issues everywhere, and on windows it's hard to tell unless you look at `%errorlevel%`.

In my previous explorations into this, I've turned up a handful of other GH issues and the like in other projects where certain versions of numpy and others seem to goof some reference counting, leading to what I imagine are double-frees when the python interpreter cleans up. I am just picking the thread back up on this, so will post things that look relevant as I go along.

Of course, importing h5py in armi.__init__.py will avoid this issue, but it's pretty unsatisfying, and I would prefer to chase this to the actual cause if possible.

**Comment by youngmit** [comment]
This was the most relevant thing that I found: https://github.com/stack-of-tasks/eigenpy/pull/58 I don't have a debug version of the python interpreter, so hard to investigate precisely. Perhaps i should take the time to build one...

**Comment by youngmit** [comment]
You might be onto something with the `atexit.retister()` call... It does do some GC stuff related to database things, where it imports the requisite modules __inside__ the registered function. It could be that the state of the interpreter when the registered atexit functions are called makes it unsafe to do certain imports....

**Comment by drewejohnson** [comment]
Thanks for the follow up @youngmit! And also glad(-ish) to see this is as perplexing as I felt 😅

Like you pointed out, dropping `import h5py` into a module `__init__.py` _just works_ but yeah doesn't feel too satisfying.

FWIW, I've seen `atexit`s in the wild, like in [`pytables`](https://github.com/PyTables/PyTables/blob/7b8633d35b703e608701f8527aad2a2ffa4c9979/tables/file.py#L2785-L2787). They don't do any imports there, just acting on a [registry of opened HDF files](https://github.com/PyTables/PyTables/blob/7b8633d35b703e608701f8527aad2a2ffa4c9979/tables/file.py#L109-L123)

**Comment by youngmit** [comment]
Honestly, looking at the `atexit` function, I'm not terribly surprised that there is an issue with performing an import of an extension module (in this case, `h5py` via `Database3`) in the `atexit` context. Especially in the context of issues like [this one](https://github.com/numpy/numpy/issues/11925), which itself references:
 - https://www.python.org/dev/peps/pep-0489/
 - https://www.python.org/dev/peps/pep-3121/
I wouldn't be surprised if `h5py` is doing something in its module init that is illegal when the interpreter is in whatever state it is when the callback is invoked. That I can reproduce the issue with:
```
import atexit

def boom():
    import h5py

atexit.register(boom)
```
I think it's safe to just plop an h5py import in context.py with a good explaination, remove the import from conftest.py and call it good. Thoughts @ntouran ?

**Comment by youngmit** [comment]
> FWIW, I've seen `atexit`s in the wild, like in [`pytables`](https://github.com/PyTables/PyTables/blob/7b8633d35b703e608701f8527aad2a2ffa4c9979/tables/file.py#L2785-L2787). They don't do any imports there, just acting on a [registry of opened HDF files](https://github.com/PyTables/PyTables/blob/7b8633d35b703e608701f8527aad2a2ffa4c9979/tables/file.py#L109-L123)

It's actually pretty encouraging to see someone else doing this kind of stuff with HDF5 files; makes me feel a little less crazy. Perhaps we should consider their approach of registering opened h5 files explicitly, so that we don't need to go picking through the trash.

**Comment by drewejohnson** [comment]
No more segfaults 😀 thanks!
