### ISSUE TITLE
Add advice on adding additional materials

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#263]
Working through the [tutorial](https://terrapower.github.io/armi/tutorials/making_your_first_app.html#adding-a-new-material) and glancing at some of the ARMI codebase, I find myself wondering what helper methods should be used or called. 

Here are some of the questions I've found

1. When, if ever, should `Material.clearCache` be used? https://github.com/terrapower/armi/blob/981459ca45cc3600c95c17db2dc14a698511ea09/armi/materials/b4c.py#L38 is the one place it shows up so maybe it's not that important?
2. When, if ever, should the `parent` attribute be modified? https://github.com/terrapower/armi/blob/981459ca45cc3600c95c17db2dc14a698511ea09/armi/materials/b4c.py#L92-L95 Again, this might be a `B4C` specific case. Or if there is a component that has `B4C` and another material, we need to update mass fractions on the material and the parent component?
3. How should https://github.com/terrapower/armi/blob/981459ca45cc3600c95c17db2dc14a698511ea09/armi/materials/material.py#L722 be leveraged? It doesn't seem to be applied to any of the shipped materials and the doc indicates that maybe it's for mixing two materials, like fresh and used fuel?

Maybe not worth an issue ticket, but there wasn't really a good way to post a generic question. [Discussion tab](https://docs.github.com/en/discussions/quickstart) might be a better place for these (my 😅) non-bug related "issues"

**Comment by jakehader** [comment]
Hey @drewejohnson, I am not sure if I can answer your questions but take a look at https://github.com/terrapower/armi/blob/981459ca45cc3600c95c17db2dc14a698511ea09/armi/materials/uraniumOxide.py#L42 to see if you can understand the use case for a `FuelMaterial`. 

Also, see the `clearCache` implementation within `composite.py` and `component.py`. 

When `clearCache` is called it sets an object's volume to `None` and its `derivedMustUpdate` attribute to True. Based on what I can see this means that the caches of volumes and areas of components are cleared and then recalculated the next time they are needed. This also clears the `ArmiObject.cached`, which appears to be used within the `getProperty` method on `materials`. 

https://github.com/terrapower/armi/blob/master/armi/reactor/composites.py#L460

https://github.com/terrapower/armi/blob/981459ca45cc3600c95c17db2dc14a698511ea09/armi/reactor/components/component.py#L423 

The only instance of `getProperty` that I see being used is in:

https://github.com/terrapower/armi/blob/master/armi/reactor/components/component.py#L318

It doesn't look like `clearCache` is being used by any other material, so this might just be extra.

**Comment by drewejohnson** [comment]
@jakehader thanks for the response. I think the cache makes sense. I also found https://github.com/terrapower/armi/blob/5a2ca101ef9fb940bf7c93ce58307a0374cb115d/armi/reactor/blocks.py#L659 where the area is computed and set onto the cache. 

In a similar situation, would I want to alter `self.parent`? Looking at some of the enrichment options I see `Material.applyInputParams` modifying `Material.parent` https://github.com/terrapower/armi/blob/3cc980eb55eae7b6f8bcfcaa1c248d11c1758ca3/armi/materials/uThZr.py#L35-L37 but the similar method for uo2 https://github.com/terrapower/armi/blob/3cc980eb55eae7b6f8bcfcaa1c248d11c1758ca3/armi/materials/uraniumOxide.py#L98-L99 calls back to the inherited method https://github.com/terrapower/armi/blob/3cc980eb55eae7b6f8bcfcaa1c248d11c1758ca3/armi/materials/material.py#L195-L203 which doesn't touch `self.parent`

Playing around with the FFTF model and my limited understanding of component tree, the parent of a material is the (armi) component in which the material is placed. Only B4C and UThZr seem to modify `self.parent` in this fashion so maybe the parent shouldn't be modified?

**Comment by ntouran** [comment]
Sorry for delay. So yeah there's some inconsistency and history here. We used to store actual compositional information at the material level, and it looks like the UThZr material is still doing that. Now, composition is stored at the Component level as the numberDensity param, and the material object itself is supposed to stay relatively constant. 

We actually were talking about having `Materials` become basically reactor-wide with parameterization for things that change as a function of burnup and composition, so that all components that are made of material x could share the same `MaterialX` object. In other words, Materials could become stateless (with possible exceptions of caching in performance critical places).

But of course it's complex. For materials that have continuous composition-related variables like the Zr-fraction in UZr, we have to be extra careful, as Zr is a fission product, but the actual detailed properties of it vs. Zr fraction and burnup are not well characterized by any experiment. There's really an overlap between fuel performance codes that compute the evolving nature of UZr vs. burnup and the material models. We basically thought through it to the point that we think the Material objects should be basically as-fabricated properties and then delegate any burnup dependent changes down to fuel performance codes. This is obviously "in flux" (ha ha). 

Any strong opinions on how this should evolve given your needs?

**Comment by drewejohnson** [comment]
@ntouran thank you for the response. 

I think the move to `Materials` as-built or as fabricated seems sensible. There's probably a thousand other things going on behind the scenes but from a user and fledgling developer, that "meshes".

> Now, composition is stored at the Component level as the numberDensity param, and the material object itself is supposed to stay relatively constant

This maybe explains some of the confusion I've been working through over the past few days. I found that, if I wanted to change the loading of a burnable absorber via `material modifications`, I could not rely on something like
```python
def applyInputParams(self, loading=None, *args, **kwargs):
    if loading is not None:
        newMassFracs = self.getNewMassFracs(loading)
        self.setMassFracs(newMassFracs)
```
but when the plugins processed these components w/ updated mass fractions based on loadings, nothing seems to have changed. Instead, if I updated `self.p.massFrac` directly, _then_ the changes were reflected in `component.getNumberDensities`

I guess if `Material`s do become stateless to reflect as-fabricated, would this require a new `Material` for each enrichment, loading, etc.? Or each component / block has information on how it's `MaterialX` has been modified?

No strong opinions as of yet but I do appreciate the request 💯

**Comment by drewejohnson** [comment]
FWIW, it looks like `Material.setMassFrac` (for a single isotope) modifies `self.p` directly https://github.com/terrapower/armi/blob/0939d9386f5ae6c7ed92b7c5e7a47fbfe2902629/armi/materials/material.py#L188-L189 but `Material.setMassFracs` falls back to https://github.com/terrapower/armi/blob/ba1402289a5c6857711374d4c700df518963cfde/armi/reactor/composites.py#L965 which, after some conversions, modifies the number densities https://github.com/terrapower/armi/blob/ba1402289a5c6857711374d4c700df518963cfde/armi/reactor/composites.py#L1010-L1019

The information passed to the number densities via `Material.setMassFracs` might be getting lost by the time `Component.getNumberDensities` is called

**Comment by drewejohnson** [comment]
Thank you all for your help on this one. I'll put other questions in the discussions tab in the future
