### ISSUE TITLE
Refactor: Remove specialization of ThRZAssembly and RZAssembly

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#303]
The current implementations of `ThRZAssembly` and `RZAssembly` implement methods like `radialOuter`, `radialInner`, etc., which reach down into their corresponding `ThRZBlock`'s to get the `outer_radius`  and `inner_radius` dimensions. 

This specialization seems outdated with respect to the implementation of grids and should be reassessed.  It seems that maintaining this separate set of assemblies that is different than just the base `Assembly` class introduces more framework complexities. #264 introduced changes where the specialization of `HexAssembly`  and `CarestianAssembly` were removed and the classes only exist now as placeholders for their "type".

**Comment by jakehader** [comment]
@john-science this might be something we can tackle pretty easily. @sombrereau - do you still use these class definitions?

**Comment by john-science** [comment]
So, @sombrereau points out that both `RZAssembly` and `ThRZAssembly` are still heavily used. So we can clean up the internal implementation of these things, but we need to keep the API and end results of these classes the same.

**Comment by john-science** [comment]
Actually, as @drewj-tp and I have been [talking lately](https://github.com/terrapower/armi/discussions/1896) about how to make ARMI more flexible, I think I want to go in the opposite direction this ticket suggests.

I think we want to make better use of our class heirarchies:


* Block
    * HexBlock(Block)
    * CartesianBlock(Block)
    * ThetaRZBlock(Block)
* PinnedBlock(Block)
    * PinnedHexBlock(PinnedBlock, HexBlock)
    * PinnedCartesianBlock(PinnedBlock, CartesianBlock)
* FastPinnedHexBlock(PinnedHexBlock)
* Etc

The idea being that right now ARMI's `HexBlock` is actually a "fast-reactor, pin-type, hex-shaped block". And ARMI forcing all this extra stuff on people without letting them just have a "PinnedHexBlock" to use for the thermal reactor is very limiting.

**Comment by jakehader** [comment]
> Actually, as @drewj-tp and I have been [talking lately](https://github.com/terrapower/armi/discussions/1896) about how to make ARMI more flexible, I think I want to go in the opposite direction this ticket suggests.
> 
> I think we want to make better use of our class heirarchies:
> 
> * Block
>   
>   * HexBlock(Block)
>   * CartesianBlock(Block)
>   * ThetaRZBlock(Block)
> * PinnedBlock(Block)
>   
>   * PinnedHexBlock(PinnedBlock, HexBlock)
>   * PinnedCartesianBlock(PinnedBlock, CartesianBlock)
> * FastPinnedHexBlock(PinnedHexBlock)
> * Etc
> 
> The idea being that right now ARMI's `HexBlock` is actually a "fast-reactor, pin-type, hex-shaped block". And ARMI forcing all this extra stuff on people without letting them just have a "PinnedHexBlock" to use for the thermal reactor is very limiting.

I'm not sure I like the multiple inheritance structure here. I think that if we want ARMI to be abstract we should make the minimum viable abstract type and then provide an open source plugin that extends the data model as an example for how one may create an application and build what is needed. Going down the path of pre making these inheritances will be messy quickly and implies that the framework knows or needs to know and handle a bunch of situations. I like the idea of the framework allowing for applications to extend the data model on initialization and just providing example documentation.

Thoughts?
