### ISSUE TITLE
Switch runLog system to use python logging module

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#304]
Long ago, we wrote a fairly customized logging system in the `runLog` package that is used throughout the code to provide console output. The motivation way back when was related to ugly printouts when running lots of cases in parallel via mpi. In retrospect, we should have just used python's [logging module](https://docs.python.org/3.8/library/logging.html?highlight=logging#module-logging) and configured it to work well with mpi runs in parallel. 

By implementing python's logging module we will be able to leverage better control over the debug level of particular parts of the code using the `LOG=getLogger(__name__)` mechanism common in other projects. Then we will be able to let the users specify verbosity levels on a module-by-module basis, thereby improving debugging and information during runs. 

For example:

```python
LOG = logging.getLogger(__name__)

def doThing():
   LOG.info('thing happening')
```

As is, the output in an ARMI run is pretty ugly and mixed up, so as a follow-up to this we could spend some time cleaning up the messages to be both prettier and more useful.

**Comment by theJollySin** [comment]
I can do this one, if you like.  I've used Python's `logging.getLogger(name)` before.

This won't be a tricky change to make. Though, it looks like `runLog` is used in 128 files, so it will be a "big PR".

**Comment by youngmit** [comment]
It might be good to still preserve the public interface of the `runLog` module, while implementing that on top of the python `logging` library. This way, we can refactor modules one at a time until `runLog` evaporates. That will also let us iterate on the general patter that we want to use before anyone goes on a massive refactor effort.

**Comment by theJollySin** [comment]
@youngmit Yeah, I was thinking that as I was looking through the 128 affected files. It *might* be that I have to change the API a bit (for things like log level or log name). But I think certainly the best goal is to *not* change the external-facing API. Definitely.
