### ISSUE TITLE
Relax Operator requirements for adding Interfaces with the same function

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#306]
As it it currently implemented, `Operator.addInterface()` is very strict about adding interfaces that advertise the same `klass.function`. In it's current state, it will just produce an exception as soon as you try to add an interface that has the same function as one that's already on the stack. While this is a good sanity check of the combined plugin implementations of the `exposeInterfaces()` API, it can make it pretty hard to do air-traffic control when multiple plugins can provide similar interfaces, but don't have a way to signal to each other which one will take precedence.

Take an abstract example:
`InterfaceA` and `InterfaceAPrime` (itself a subclass of `InterfaceA`) implement the same `function`. Some of the same settings that activate `InterfaceA` are used to activate `InterfaceAPrime`, but the plugin that provides `InterfaceA` has no knowledge of `InterfaceAPrime`'s existence, or the settings that control it. Therefore it doesn't know how to get out of the way when an `InterfaceAPrime` is desired. Right now, this would lead to a collision in the `Operator.addInterface()`.

I propose loosening the check in the `Operator` class and allow it to accept the new `Interface` if, and only if, the new Interface is a subclass of the `Interface` that exists in the stack. If there is a duplicate that is a base class of the existing class, it should be ignored. If no such inheritance exists, the exception should be raised.

**Comment by chris10mckenz** [comment]
#307

**Comment by youngmit** [comment]
Fixed in #307

**Comment by youngmit** [comment]
Thanks, @chris10mckenz !
