### ISSUE TITLE
Request: Don't perform temporary directory cleanup at exit

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#308]
When exiting a python environment that has imported ARMI, ARMI will do some cleanup: closing database files and removing old temporary directories. It looks like ARMI allows the temporary directories to reach two weeks old before removing them. This is nice because you don't have to worry about ARMI creating a backlog of temporary files and some recent files are still kept around.

Until you have a very long running case that exceeds two weeks (lots of burnup, slow compute node), and you use ARMI in a totally unrelated instance and all the in-progress files are summarily removed.

Yes, some of this can be attributed to issues on my own end and better safeguards could be put in place. And two weeks is a long time to have a single job running. But this feels like a side effect that could be avoided with changes to the ARMI experience.

I propose the following recommendations on how ARMI handles cleanup of the temporary directories

1. The `cleanup` function registered `atexit` should check the number of temporary directories, and report the number of directories to the user via a debug statement. Debug over info so that way the message isn't printed if you just want to open a python environment and process some data.
2. Support  a "dry run" switch with the `clean-temps` entry point. Here the files that _would_ be removed are printed, and maybe with their date next to them. 
3. Configurable expiry time (2 weeks, 60 days, etc.) in `clean-temps`
4. A way for the current ARMI run to know it's main temporary directory created, and only remove those

This is kind of related to some comments in #257, specifically https://github.com/terrapower/armi/issues/257#issuecomment-785302156 and https://github.com/terrapower/armi/issues/257#issuecomment-785376609

**Comment by youngmit** [comment]
First off, 😱

**Comment by ntouran** [comment]
Dang, I'm also sorry to hear that. We had troubles with runs filling up our HPC and this is a residue from that. We will make this kind of 'feature' opt-in rather than opt-out and leave its use up to the app developers rather than having it come with the framework.

**Comment by ntouran** [comment]
@drewejohnson is this quick solution acceptable from your perspective at this point? It basically just turns off the feature by default.

**Comment by drewejohnson** [comment]
@youngmit @ntouran thank you for the response and fast patch! I've looked over #309  and looks like it'll do the job. Won't know until I run another long sim.

I'm happy if you want to close this issue as it stands. The discussion wall might be a better place to hash out a longer term fix for how ARMI handles `atexit`.
