### ISSUE TITLE
Assembly add is being rather inefficient

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#310]
...I think. I was looking at test coverage stats and noticed something odd in the database3 code. This is never getting executed:

```python
# Re-assign names to assemblies and blocks based on the read-in assemnum. Should
# the name be a param?
for a in groupedComps[Assembly]:
    name = a.makeNameFromAssemNum(a.p.assemNum)
    a.name = name
    a.renameBlocksAccordingToAssemblyNum()
```

But the blocks have names. The right ones, to boot! Looking more closely, it turns out that their names are getting set in Assembly.reestablishBlockOrder(), which itself is getting called from:

```python
def add(self, obj):
    """
    Add an object to this assembly.

    The simple act of adding a block to an assembly fully defines the location of
    the block in 3-D.
    """
    composites.Composite.add(self, obj)
    obj.spatialLocator = self.spatialGrid[0, 0, len(self) - 1]
    # assemblies have bounds-based 1-D spatial grids. Adjust it to have the right
    # value.
    if len(self.spatialGrid._bounds[2]) < len(self):
        self.spatialGrid._bounds[2][len(self)] = (
            self.spatialGrid._bounds[2][len(self) - 1] + obj.getHeight()
        )
    else:
        # more work is needed, make a new mesh
        self.reestablishBlockOrder()
        self.calculateZCoords()
```

So it would appear that the "more work" is happening every time we add a Block to an Assembly when composing the reactor from the database. I'm sure we could speed this up if we were to peek ahead, build a mesh, then add all of the blocks, or add all of the blocks without worrying about the mesh and reconcile the axial mesh at the end. Would want to measure to see if this is actually an issue. At the very least, its N^2.

We've toyed around with the idea of addressing things like this with creative use of context managers to permit cheap, repeated mutation of something, then rejigger everything to make sure everything is consistent when we are done. Perhaps this is a good place to put that idea into practice.

**Comment by john-science** [comment]
We have changed some things in the past ~2 years, and this ticket is no longer relevant.
