### ISSUE TITLE
Helix diameter incorrect in tutorial documentation

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#311]
see: https://github.com/terrapower/armi/blob/master/armi/tests/tutorials/anl-afci-177-blueprints.yaml#L12-L23

The helix diameter for the ANL-AFCI-177 inputs should be 0.8888 cm based on the Table 4.4 of https://publications.anl.gov/anlpubs/2008/05/61507.pdf, but currently is set to 0.84825 cm in the blueprints file. The helix diameter should be equivalent to the pin pitch, which is also defined as the **Wire OD** + **Clad OD**. Currently, the 0.84825 cm is calculated incorrectly as **Wire OD / 2.0** + **Clad OD**.

![image](https://user-images.githubusercontent.com/26268658/121441199-32100c80-c93e-11eb-92af-89768ac92f83.png)

**Comment by ntouran** [comment]
Yeah I dunno if it'd be more clear in the helix component as helixdiameter = 2* helixradius = 2*(clad radius + wire radius) = 2*(cladOD/2 + wireOD/2) = cladOD + wireOD. Nice catch.

**Comment by jakehader** [comment]
@ntouran, is there even a reason to have `helixDiameter` as a parameter since it seems over specified? What is it physically mean to have a `helixDiameter` smaller or larger than the **Wire OD** + **Clad OD**? Does larger imply "slop" in the pin lattice?
