### ISSUE TITLE
Improve test coverage and implementation of the RIPL reader

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#316]
The RIPL reader is used to load in a larger set of radionuclide data. It contains half lives and branching ratios. The current reader is a bit clunky and could be improved for better understanding. This is related to #259.

**Comment by john-science** [comment]
A quick note on code coverage of `armi/nuclearDataIO/ripl.py`, it has 86% code coverage.  And it would be 100% code coverage, except the helper method `makeDecayConstantTable` is untested.

**Comment by jakehader** [comment]
This is now closed since the RIPL reader was removed and replaced in #998.
