### ISSUE TITLE
Remove all bare "import armi" statements.

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#349]
The idea is simple, remove all the bare "import armi" statements left in the repo after PR #347.

This will require some refactoring though, as all the low-hanging fruit has been picked.

There are still 23 instances left in ARMI with bare `import armi` statements:

| File        | What is used? |
| :----------------- | :------------ |
| `__main__.py`  | configure(), isConfigured(), MPI_RANK, MPI_NODENAME, MPI_COMM |
| bookkeeping/db/database3.py | MPI_RANK, __version__, USER, ROOT, START_TIME, getApp() |
| bookkeeping/memoryProfiler.py | MPI_NODENAME |
| bookkeeping/report/html.py | RES, USER |
| bookkeeping/report/reportingUtils.py | USER, ROOT, MPI_SIZE, START_TIME, MPI_NODENAME, MPI_RANK |
| cases/case.py  | getPluginManager(), RES, MPI_RANK, MPI_SIZE, MPI_COMM, CURRENT_MODE, Mode.INTERACTIVE, context.APP_NAME |
| `cli/__init__.py` | getPluginManager(), context.APP_NAME, __version__, getApp(), Mode.setMode(), context.MPI_RANK |
| cli/database.py | Mode.BATCH |
| `localization/__init__.py` | MPI_RANK |
| mpiActions.py | MPI_SIZE, MPI_RANK, MPI_COMM, MPI_DISTRIBUTABLE, MPI_NODENAMES |
| nucDirectory/nuclideBases.py | context.RES |
| `operators/__init__.py`  | MPI_SIZE, getPluginManagerOrFail() |
| operators/operator.py | MPI_RANK |
| operators/operatorMPI.py | MPI_COMM, MPI_RANK, MPI_SIZE, getPluginManager() |
| operators/settingsValidation.py | getPluginManagerOrFail(), MPI_RANK |
| physics/neutronics/crossSectionGroupManager.py | MPI_RANK |
| physics/neutronics/macroXSGenerationInterface.py | MPI_RANK, MPI_COMM, MPI_SIZE |
| reactor/blueprints/reactorBlueprint.py | MPI_RANK |
| reactor/composites.py | MPI_SIZE, MPI_COMM |
| settings/caseSettings.py | getApp(), MPI_RANK |
| `utils/__init__.py` | `__path__`, `__name__` |
| utils/directoryChangers.py | context.getFastPath(), MPI_SIZE |
| doc/conf.py | configure(), _ignoreConfigures, `__version__` |

We are also using bare `import armi` statements in unit test files.  While that _is_ less important, these tests are currently being packaged with ARMI and are importable at run time:

| Test File    | What is used? |
| :----------------- | :------------ |
| localization/tests/test_localization.py | MPI_RANK |
| operators/tests/test_operators.py | MPI_COMM, MPI_RANK, MPI_SIZE |
| reactor/tests/test_parameters.py | MPI_RANK, MPI_COMM, MPI_SIZE |
| settings/tests/test_settings.py  | _app, getPluginManagerOrFail() |
| settings/tests/test_settingsIO.py | Mode, CURRENT_MODE |
| `tests/__init__.py` | ROOT  |
| tests/test_apps.py | _app, getApp(), getDefaultPluginManager(), configure() |
| tests/test_mpiActions.py  | MPI_COMM, MPI_RANK, MPI_SIZE |

I am hopeful that some of the above can be fixed by using `getApp()` instead of just `_app`. Also, if `MPI_RANK` and `MPI_SIZE` never change during a run, several of the above cases could be greatly simplified. (At the very least we could import `context` here, right?)

**Comment by theJollySin** [comment]
I do not have permissions to add labels here, but I think "good first issue" might apply.

**Comment by john-science** [comment]
On reflection, this will be quite easy as most of these that are left were done out of laziness, as we could do:

```python
from armi import context
```

in place of the bare:

```python
import armi
```

**Comment by john-science** [comment]
Oh no.  These global configs are causing us some spaghetti code.  Things are being imported from `armi.context.py` to `armi.__init__.py`:

https://github.com/terrapower/armi/blob/907f2b49d4063cfd07068431698d22dab4c7d267/armi/__init__.py#L63-L71

But for things like `MPI_RANK`, these are being copied by-value, not by-reference. 

So we have places in the code where:

```python
armi.MPI_RANK !- armi.context.MPI_RANK
```

And that is obviously no-go. 

The best solution would be to remove all such things from `armi.__init__.py`, and just make everyone import them directly from `armi.context`.  Problem solved. BUT I'm not sure how many down-stream projects that would break.

This _does_ require fixing though.

**Comment by john-science** [comment]
Oof.  The more I work on these bare `import armi` statements, the more circular imports they are hiding.
