### ISSUE TITLE
Building Macro XS's without MPI parallelism

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#357]
If the import of `mpi4py` is unsuccessful, `armi.MPI_COMM` is set to `None` within context.py. This leads to issues with the current implementation of `invokeHook` within the `MacroXSGenerator` class, which assumes that `armi.MPI_COMM` is instantiated, and causes the code to fail with an AttributeError.

This means that machines which fail the `mpi4py` load will not be able to run a large class of ARMI inputs, even though `mpi4py` is not required to run the input in serial.

This could be fixed by adding logic to the `invokeHook` method to explicitly handle cases with `armi.MPI_SIZE=1` so that calls to `armi.MPI_COMM` are avoided. This solution has been preliminarily implemented successfully on my machine, but another set of eyes would be useful to determine if there is a better solution to the problem.

**Comment by jakehader** [comment]
@youngmit and I were just talking about this issue so thanks for making a ticket (and also discovering the issue too!). Mitch had some ideas of how to handle this more generically within the framework if a machine did not have MSMPI (or equivalent) installed.

**Comment by keckler** [comment]
I figured that someone might have a more sophisticated idea on how to fix this than me. I'll leave it to the experts.

**Comment by jakehader** [comment]
@keckler, can you just submit the changes that you made and we can review them? Your solution might be a good stop gap for now and we can think about future improvements if needed.

**Comment by theJollySin** [comment]
@youngmit   Is this your 'stub version of MPI' idea?  Or do you favor something more like keckler's idea above (which also sounds quite reasonable).

**Comment by jakehader** [comment]
@theJollySin, yeah the other idea that @youngmit had was the MPI stub, but maybe that's a longer term solution and @keckler's fix is a shorter term solution. We can keep this issue open even after the PR.

**Comment by keckler** [comment]
Sure, I'll put it up later tonight and let you know.

**Comment by keckler** [comment]
The fix that I implemented is up at #359 . @theJollySin @jakehader @youngmit
