### ISSUE TITLE
Somehow reduce the number of log files created by third party libraries

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#373]
@john-science Did some cool work to make our logging stuff implicitly rub off on TPLs, but an unfortunate side effect of this is that we get lots of _empty_ log files, which I assume are being created when the library instantiates its `logging` object. Would it be possible to either automagically clean these up, or perhaps even lazily create the file on first write? something like that. Not super high priority, but would be really nice.

**Comment by john-science** [comment]
@youngmit  Sure thing!

The obvious solution is:

> Delete the empty log file on the moment of creation. Easy.

If you prefer we act in a more lazy manner, I will look into it. As it happens, `logging.FileHandler` is exceptionally _not_ lazy. It pins the file itself to the I/O stream, so if the file doesn't exist at any point after the `FileHandler` is created, all logging will silently be lost. (I hate that it's silent.)  I think the solution would have to be creating a FileHandler the first time someone 'log()` is called. Which is maybe awkward, but probably also easy.

Any preference?

**Comment by jakehader** [comment]
@john-science - the main ones I am seeing are from `matplotlib`:

![image](https://user-images.githubusercontent.com/26268658/129934362-2b265a04-03c9-4120-b0a9-bca2ed278395.png)

**Comment by john-science** [comment]
@jakehader  That is super annoying.  Sorry, I wasn't seeing that in my usual in-use-test-case testing.  Though I was perhaps just not looking in the right folder?

In any case, there is a PR open to fix this: https://github.com/terrapower/armi/pull/376

**Comment by jakehader** [comment]
@john-science, I'll check it out and let you know if it works on the case I'm running! Thanks for the quick fix.

**Comment by john-science** [comment]
I believe PR #384 solved this issue. Can we close it?  @jakehader ?

**Comment by jakehader** [comment]
I believe so! I haven't seen as many log files around with the changes, but I can reopen if I see them again.
