### ISSUE TITLE
ARMI infinite loop in Interpreter

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#381]
This is a pretty usual way of spinning up ARMI in the interpreter:

```python
import armi
armi.configure(armi.apps.App())
o = armi.init()
```

Unfortunately, right now this causes an awful infinite loop for prompting:

```
[prmt] Continue? (YES, NO, CANCEL, Y, N):
[prmt] INSPECTOR: No blueprints file loaded. Run will probably fail.
[prmt] Continue? (YES, NO, CANCEL, Y, N):
[prmt] INSPECTOR: No blueprints file loaded. Run will probably fail.
[prmt] Continue? (YES, NO, CANCEL, Y, N):
[prmt] INSPECTOR: No blueprints file loaded. Run will probably fail.
[prmt] Continue? (YES, NO, CANCEL, Y, N):
...
```

**Comment by john-science** [comment]
@jakehader  @youngmit  I am working on it now.  I know this has happened super recently, and since it has to do with the interpreter, I imagine this is a side effect of trying to automate logging initialization in the interpreter (see the above PR).

**Comment by youngmit** [comment]
This is an interesting message, which I haven't seen before. It could be that you are running from a directory with no settings files or something? I think `armi.init()`, when not provided a path to a settings file will look at the cwd for .yaml files and prompt for which one to load. If there are none, maybe it leads to this? I suspect that the loop is from any prompt that the loading process or settings validator generates, so providing `fName` and a settings file with no issues for the validator to complain about might function just fine. Also running with the `--batch` argument is why a lot of tests pass, while users are running into issues.

**Comment by john-science** [comment]
> ...I think `armi.init()`, when not provided a path to a settings file...

Yeah, the actual error message is a prompt that a settings file wasn't provided. But that's a bit of a red herring.  Jake was also seeing this infinite loop of prompts in a different situation. 

The problem as I see it is not the prompt itself, but that we are now getting infinite loops of prompts instead of 1 for user input.  I am circling in on the root cause ATM.

**Comment by john-science** [comment]
@jakehader  Okay, I have a fix.  I am just trying to decide if there is a better way to test this CLI stuff before I make a PR.

**Comment by john-science** [comment]
@jakehader Okay, I have a fix. And the PR is in: #382

If you have any further trouble, feel free to re-open the ticket.
