### ISSUE TITLE
User docs error

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#393]
The section of the ARMI docs describing the Settings Input File is missing an excerpt that should be there. See the highlighted portion of the attached screen grab.

![image](https://user-images.githubusercontent.com/21959600/131525082-596de4a4-a6da-4f6c-bd1c-6bc627b1947a.png)

**Comment by john-science** [comment]
This issue has been resolved.  You can look at the live version of the docs here to see the example file:

https://terrapower.github.io/armi/user/inputs/settings.html#the-settings-input-file

This has come about as part of the initial work to revamp the docs in this PR: https://github.com/terrapower/armi/pull/404

Thanks for the find!
