### ISSUE TITLE
Update `Case` to allow manually adding dependencies

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#400]
When using the `Case` in `cases.py` the dependencies are auto-derived based on the plugins and some other settings like `explicitRepeatShuffles` in https://github.com/terrapower/armi/blob/b0c76656ec97c984272c1e9df0a7bb26db8045c9/armi/cases/case.py#L169-L180. There are a couple of challenges/problems with this that I think can be cleaned up:

1. The dependencies are auto-derived each time and there is no way to explicitly add your own dependency manually to the `Case` object. It would be great if there could be an `addDependency` method that a user could set explicitly. The use case for this is when I use the `copyFilesFrom` setting, I want to explicitly tell the case to wait until another case is completed in the suite before firing off.
2. The implementation of the `dependencies` method on `Case` relies on regular expressions to determine what the dependent cases are. This seems to work well for the scenarios that are implemented, but I had difficulties trying to extent this behavior within a neutronics plugin to using `copyFilesFrom` and an ISOTXS file. It _could_ be nice if this could use something like glob rather than regular expressions, but maybe this is just user/developer error because I am not good with regular expressions.
3. Finally, because of the above issues I ended up subclassing the `Case` to add dependencies manually. When doing this I noticed that the case objects stored on the `Suite` are private (i.e., `suite._cases`). Ideally there would be a way to access these through the `Suite` API with some `__getitem__` or other another method.

Just for completeness, here is the subclass I made, but I don't recommend this if we can fix/update this.

```
class CaseWithManualDependency(cases.Case):
    """
    Manually overwrite the dependency treatment in a general Case
    so that the dependencies can be set explicitly rather than implicitly
    based on the case settings.
    """
    
    def __init__(self, cs, caseSuite=None, bp=None, geom=None):
        cases.Case.__init__(self, cs, caseSuite, bp, geom)
        self._dependencies = []
        
    def setDependency(self, depCase):
        runLog.info(f"Setting dependency of {depCase} for {self}")
        self._dependencies = [depCase]
        
    @property
    def dependencies(self):
        return self._dependencies
 ```

This is outside the scope of this issue, but another thing to consider is updating the `Suite` to hold the dependencies for the cases rather than the `Case` objects themselves.

**Comment by jakehader** [comment]
@youngmit, could you make another PR that provides a mechanism to get a case from a suite? Right now the Suite's cases are in `_cases` without a clear way to get them without just manually printing them and figuring out what the index is and then using it.

It would be nice if a case could be retrieved by name or some other attribute.

**Comment by ntouran** [comment]
@jakehader  can you make a separate issue for that last request?
