### ISSUE TITLE
Warnings with YAML1.1 Mantissa 

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#401]
```
[info] Applying <Migration from 0.1.2: Update elemental nuclide flags....
c:\users\jhader\codes\venvs\nala\lib\site-packages\ruamel\yaml\constructor.py:522: MantissaNoDotYAML1_1Warning:

In YAML 1.1 floating point values should have a dot ('.') in their mantissa.
See the Floating-Point Language-Independent Type for YAML™ Version 1.1 specification
( http://yaml.org/type/float.html ). This dot is not required for JSON nor for YAML 1.2
Correct your float: "1e-10" on line: 510, column: 10
or alternatively include the following in your code:
  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.MantissaNoDotYAML1_1Warning)
  warnings.warn(MantissaNoDotYAML1_1Warning(node, value_so))
```

I am creating this issue just for other users/developers to be aware. It seems that the YAML updated their specification to write a warning if a float does not include a decimal (i.e., 1e-10 creates a warning rather than 1.e-10) - see: https://github.com/pycontribs/ruyaml/blob/8d846508e8386c7e34b77adce32fe78877bc025f/lib/ruyaml/error.py#L258. To fix this, it is suggested to add the following lines of code early on in your specific ARMI-based application if you would like ignore this warning:

```
import ruamel
import warnings
warnings.simplefilter('ignore', ruamel.yaml.error.MantissaNoDotYAML1_1Warning)
```

**Comment by john-science** [comment]
I note the we import ruamel in 8 separate modules in the repo.  And, of course, Yamlize imports it many, many times.

My preference is to block out this annoying warning, rather than enforce their lame standard on our YAML files. But that will mean some minor import re-org so we can filter all these warnings in one central location.

I have to admit, that's an annoying warning. Let me think about it.

**Comment by john-science** [comment]
Hello again.  I can not reproduce your warning.  I have tried the following in the `ruamel` versions `0.17.10` and `0.17.16`:

    >>> from ruamel.yaml import YAML
    >>> 
    >>> y = YAML()
    >>> 
    >>> x = y.load('''{"stuff": 1e4}''')
    >>> x
    ordereddict([('stuff', 10000.0)])

**Comment by jakehader** [comment]
I am using version `0.17.2`
