### ISSUE TITLE
Running CaseSuite.clone() deletes the repo and all adjacent directories

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#403]
When running the `CaseSuite.clone()` method, it can delete the entire repository, and all directories adjacent the repository.

I have reproduced this bug off master, and here are the exact steps you need to reproduce it yourself.

> Please be careful reproducing this bug on your own machine!

First, set up the env from scratch:

```bash
# make the temp directory and add a couple of files to it
mkdir -p ~/temp/safety/backup/be_careful/terrapower/
cd ~/temp/safety/backup/be_careful/terrapower/
touch things.txt
touch stuff.txt

# clone the repo and make the env
git clone https://github.com/terrapower/armi
cd armi/
python3 -m venv venv
source venv/bin/activate

# install the code
pip install -r requirements.txt 
pip install -r requirements-testing.txt 
pip install -e .
```

Then, just to prove everything is working, let's run some unit tests:

```bash
python -m pytest -n 4 armi/cases/tests/test_cases.py
```
That worked fine. Now add this text to `test_cases.py` unit test file:

https://github.com/terrapower/armi/blob/master/armi/cases/tests/test_cases.py#L131

```python
    def test_clone(self):
        clone = self.suite.test_clone("test_clone")
        print(clone)
        assert False
```

And run that test file again:

```bash
python -m pytest -n 4 armi/cases/tests/test_cases.py
```

That's it. The entire repo is now deleted, along with all the stuff adjacent to it:

```bash
cd ~/temp/safety/backup/be_careful/terrapower/
ls
# not only is `/armi/` gone, but so are `things.txt` and `stuff.txt`
```

**Comment by youngmit** [comment]
Quickest way to find this might be to make some file read-only and try to reproduce and see where it stubs it's toe. Looking through the code, it's not immediately obvious where this might be happening.

@john-science for completeness sake, what platform are you running on? Shouldn't matter too much, but lots of the os/file system stuff in Python is surprisingly different between linux and windows.

**Comment by john-science** [comment]
Update.

So, the problem is here:

https://github.com/terrapower/armi/blob/master/armi/cases/suite.py#L182

If the users specifies a non-existent directory as `oldRoot`, the variable `newDir` takes on the value `..`, and then everything gets wiped by the call to:

    directoryChangers.ForcedCreationDirectoryChanger(newDir, clean=True, dumpOnException=False)

So, I haven't decided the best way to fix it yet, but I think there are a couple things that need addressing:

1. `clean=True` in `directoryChangers` is a pretty scary idea. This does the deleting, so I would prefer if we "copy" code, but never "mv" it.
2. `newDir` above has no error handling on it at all, so that gives us this ability to set the directory to `..` and just let things go crazy from there.

**Comment by ntouran** [comment]
Sorry for the destruction. 

>  This does the deleting, why isn't a "copy" enough?

This stems from an issue we've had many times where people run hundreds and thousands of cases on the HPC and sometimes the jobs don't finish quite right (e.g. crash due to a bug, cancelled due to going where people don't want, etc.). We've struggled with the local cluster drives filling up from abandoned runs. Hence all the cleaning. The downside I guess is that in non-cluster runs on local computers, there are risks like this. 

For that directory changer, maybe we shouldn't allow `clean=True` unless the directory passed in was created. Or in other words, passing clean=True should fail if `newDir` didn't exist in the first place.

**Comment by ntouran** [comment]
Specificially, in `directoryChangers.ForcedCreationDirectoryChanger.__enter__` we chould move the `if self.clean` part so that it only runs if the makedirs command above was actually executed.

**Comment by john-science** [comment]
This bug was closed by PR https://github.com/terrapower/armi/pull/405

But I think there is probably still a little more work to be done to ensure that we are being maximally safe.
