### ISSUE TITLE
Request: More gracefully tell the user which isotopes are missing

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#455]
When ARMI detects that an isotope in the burn chain is missing from the nuclide flags, it prints a warning like:
```
ValueError: Missing active nuclides in loading file. Add the following nuclides:
 1 - PA233
 2 - PA231
```
However, often after the necessary isotopes have been added to the nuclide flags and the code is rerun, ARMI again complains that _other_ isotopes are missing. In this particular example, I added the Pa isotopes that were indicated as missing only to now get the following error:
```
ValueError: Missing active nuclides in loading file. Add the following nuclides:
 1 - U233
 2 - U232
```
If the code demands that an isotope be added as "active" (i.e. burnable), then it clearly can figure out that its daughters will need to be added as well.

Would it be possible for ARMI to hold off on issuing the first error until it also knows that the second error will crop up (and so on, recursively)? Then it can issue all errors at once and the user can fix them all at once.

Better yet, can we just make ARMI add the isotopes on its own? Possibly also issuing a warning to the user. But if the code forces the user to add the isotopes in order to continue, why not just make the code do the work internally, allowing the user to avoid the annoyance?

**Comment by keckler** [comment]
In relation to Barry's comment, Serpent has a similar feature. In Serpent, you specify a given cell as depletable, and all isotopes in the cell are depleted through the entire burn chain, with isotopes below certain thresholds omitted from the burn chain. In the case of Serpent, I think it is less clear what is going on under the hood, though, because clearly it is making some judgments on what products should be kept/ignored.

On the other side of things is REBUS, which from my recollection is much closer to what ARMI currently requires. I remember the REBUS depletion chain being very spartan and the user having to explicitly define the entire burn chain in every input. I could not think of anything less user-friendly.

**Comment by ntouran** [comment]
From the historical perspective, ARMI's depletion module was created as a direct drop-in replacement for REBUS with some additional capabilities. Thus, it definitely has all the limitations descended from REBUS as well. 

I agree that it is not user friendly for people who do not want to hand-craft their transmutation chains (everybody?). To be fair to it, on the plus side, it's explicit (no black boxes, no hard-coded assumptions), flexible (can and will model whatever the highly-trained and specialized user specifies), memory efficient, and fast. It is definitely not good for people who just want to get some depletion going without looking deep under the hood. 

The ARMI depletion stuff has served us well for a long time, as long as you don't want to change what is depleted. If you do want to change what's depleted, then there is a lot of training needed that so far has basically been done in person. More documentation on that would be a big benefit, in addition to other changes we're talking about. 

Anyway, under the hood, the ARMI depletion stuff is fine. We just may want to add some helpers that allow users to set up different decay chains. We could also put some carefully crafted off-the-shelf options that will work for most people and can be specified in the burn chain settings. We could have, e.g.:

* Normal U-Pu cycle with MA's up to Cm-247
* Extended U-Pu cycle with MA's up to Cf-252
* Th-U cycle with MA's up to Cm-247
* Extended Th-U cycle with MA's up to Cf-252
* Add explicit boron/lithium decay chain
* Add explicit xenon chain

And then of course people could choose any of those to start from and add specific fission products or whatever that they want to track explicitly. 

Notably, we have been talking a little with ANL about integrating with OpenMC's depletion (related to #11).

**Comment by ntouran** [comment]
I should mention that the REBUS method with lumped fission products is dramatically more memory and cpu efficient than the "track everything in every cell" approach. Yes you can run Serpent or origen and deplete every single pin in a core, but that requires a large supercomputer and lots of time. Our runs typically deplete every block in 3D and can run on one or two CPUs. So it's just a different scale of problem that we're typically interested in in reactor fuel cycle calcs. That said, obviously the framework should facilitate hero calcs or normal calcs depending on the analysts preferences.

**Comment by keckler** [comment]
I agree with everything you are saying, and knowing that the ARMI module descends from REBUS makes complete sense.

I think adding the "helpers" that you mention would be a huge benefit and would likely address my complaints for the majority of cases. My only additional hope would be the possibility that the user does not need to explicitly select _any_ of the burn chains when building inputs for "normal" cases, and that ARMI could be smart enough to turn on the chains that are needed based on the isotopes in the rest of the input.

**Comment by jakehader** [comment]
@keckler, I think that if we were to have a way to represent the Chart of Nuclides in memory better (see https://github.com/terrapower/armi/discussions/460) then there could be helpers that are built onto that to help generate both the `decay-chain` input file as well as a set of active/burnable nuclides you want to consider for any given analysis. 

It would be nice to be able to visualize and draw out decay chains to confirm them.

**Comment by ntouran** [comment]
Yeah I'm tempted to close this for now and let the discussion in #460 pan out. 

BTW @jakehader we can [visualize the active decay chain.](https://terrapower.github.io/armi/gallery/framework/run_transmutationMatrix.html#sphx-glr-gallery-framework-run-transmutationmatrix-py) Guess we would make that a convenient util or something in neutronics.

**Comment by jakehader** [comment]
Notice: #998 was a step in this direction that can be extended to decay/transmutation chains now. I think the next step is to implement the decay chains as they are in the chart of the nuclides (actually this isn't too bad with the IAEA Chart of the Nuclides API) and then we can discuss and/or implement several ways to reduce this down either manually or automatically.

**Comment by keckler** [comment]
Note that #1022 effectively does what this PR is asking for, in the case of using the complete explicit fission product chain.

I think this ticket is never gonna happen, so I'm just going to close it.
