### ISSUE TITLE
No warning on unused/bogus case settings

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#461]
A user is able to to put a setting into the case settings that is not used anywhere during a run without being warned. There are (at least) two situations where this could be important:
- Similar to #402 , this could allow typos to go unnoticed if the user simply made a mistake in typing the name of the setting, but the setting has a default behavior when it is actually called
- The user typed a valid setting but the setting is not actually used anywhere, indicating that the user has a misunderstanding of what the setting is supposed to do

It would be beneficial if the user was warned in such situations. I imagine this could become quite difficult to actually do, considering plugins and whatnot, unless plugins are required to register their settings with the framework? Regardless, I think it would be very valuable.

**Comment by jakehader** [comment]
Hi @keckler, are you seeing the issue where you put an invalid setting in the YAML input and it just allows this to exist without any warning or are you particularly interested in the plugins/framework reporting if the setting that is input never triggers any lines of code to execute?

If you are interested in the first part, that should be relatively straight-forward to check. I would assume that the case settings should defend against invalid settings, so a failing (or expected-to-fail) example would be really useful. 

The other case seems very challenging to implement generically. If there are specific settings that you are finding trouble with then it might be useful to implement a settings validator check on the framework or the plugin that implements the setting(s). Right now, all settings are registered to the global settings when plugins are registered, so if you get a new settings object after importing and configuring the application, then you should be able to access `cs['pluginSetting']`

**Comment by keckler** [comment]
I am definitely most interested in the first case that you list, where an invalid setting is unnoticed. 

Sorry, I should have put an example case up. An example using a standard case settings file is [attached here](https://github.com/terrapower/armi/files/7506017/tutorial.zip), where I added the setting `THIS_IS_A_FAKE_SETTING: True` to the case settings. I don't see any warning or mention of this invalid setting in the output of the run. I also confirmed that the same invalid setting will pass through a programmatic input unnoticed.

The second type of situation that you describe is almost definitely beyond what a typical user might expect a code to guard against, and so I wouldn't worry about trying to check for it. What I meant in my second bullet point is different than what you describe in a subtle way, I think, but likely just as hard to guard against. I wouldn't worry about that second point as much. Implementing a check for invalid settings in the first place would be a big improvement already.

**Comment by john-science** [comment]
@keckler  I really like your note about unused material modifications, but I'm not sure we want to support this, more general, unused settings.  There are numerous settings in the settings file that pertain to just individual plugins.  And while some of those could be moved INTO that plugin, that would be a rather big lift to make happen.  And what if someone wants to do a partial run through only _some_ of the plugins they usually run, but they want to just keep their giant settings file mostly intact?

I am not entirely convinced we _can_ do what you suggest here, without breaking a lot of people's workflows.

@ntouran  Any thoughts on how practical it would be to make this ticket happen?

**Comment by jakehader** [comment]
> Sorry, I should have put an example case up. An example using a standard case settings file is [attached here](https://github.com/terrapower/armi/files/7506017/tutorial.zip), where I added the setting `THIS_IS_A_FAKE_SETTING: True` to the case settings. I don't see any warning or mention of this invalid setting in the output of the run. I also confirmed that the same invalid setting will pass through a programmatic input unnoticed.

This seems like a bug to me. I don't think the case should necessarily fail, but warnings of extra settings being provided in the YAML file should be made. I'll look for where this is happening and see how the `cs` object is being constructed from the YAML data.

**Comment by john-science** [comment]
@jakehader The name of that method _is_ enticing. But that method is only being used when reading XML files, not YAMLs?  That's... odd. Also, the method has no docstring, so give me a bit to see if what it really does.

**Comment by john-science** [comment]
I am working on a PR for this.  It may not be a _complete_ solution, but it seems to be catching fake settings when I add them.

In fact, my major concern is not that my solution won't work, but that finishing this ticket will break someone's workflow.
