### ISSUE TITLE
Error in reading Geometry File

### ISSUE THREAD

**Issue by AI-Pranto** [terrapower/armi#47]
During running  ANL-AFCI-177, I get **Included blueprints**  file can't  read **anl-afci-177-coremap.yaml**. In anl-afci-177-blueprints.yaml , I see ` core: ! include anl-afci-177-coreMap.yaml` which I change by omitting `!` this.  But still now, **anl-afci-177-coremap.yaml** file can't execute.

>> `Case Settings    anl-afci-177.yaml                                         ec2553bc0b`
>> `Blueprints       /home/pranto/Desktop/armi/anl-afci-177-blueprints.yaml    ee43ed5bdf`
>> ` Geometry                                                                   MISSING'
>> `fuel management  /home/pranto/Desktop/armi/anl-afci-177-fuelManagement.py  622957b035`

**Comment by jakehader** [comment]
Hi @AI-Pranto,

The `!` in `!include` should remain in yaml blueprints loading file (https://terrapower.github.io/armi/user/tutorials/walkthrough_inputs.html):

```
systems:
    core:
      grid name: core
      origin:
          x: 0.0
          y: 0.0
          z: 0.0
grids:
    core: !include anl-afci-177-coreMap.yaml
```

This `!include anl-afci-177-coreMap.yaml` acts as a reference to the `anl-acfi-177-coreMap.yaml` file. This is beneficial if you want to have multiple blueprints files pointing to the same core map. 

Stackoverflow example: https://stackoverflow.com/a/9577670

**Comment by AI-Pranto** [comment]
Thanks for your help.
