### ISSUE TITLE
Fix coverage check

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#470]
Code coverage reporting to coveralls is busted. seems like it has something to do with incompatible versions of the coverage package and the coveralls package which does the posting to coveralls.io. We need to either fix the coveralls reporting somehow, or move to another system. @john-science pointed out codecov.io, which in his experience has been more stable. Worth investigating.

**Comment by john-science** [comment]
Just FYI.

Coveralls fixed the issue and it is working again.

I'm not 100% sure we won't hit problems with them again moving forward, so maybe we still need to try codecov.io.  I'm thinking about it.
