### ISSUE TITLE
Check on uniform mesh generator uses stale data

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#471]
[One of the checks to confirm that the uniform mesh generation has been done correctly](https://github.com/terrapower/armi/blob/master/armi/reactor/converters/uniformMesh.py#L351) uses stale data, and thus improperly fails.

In particular, when a reactor changes power between cycles using the `powerFractions` case setting, the check will improperly fail on the first node of the second cycle because it calculates `sourcePow` using stale block power data from the previous cycle, but `expectedPow` uses data from case settings of the current cycle.

Example case to come in a later comment...

**Comment by keckler** [comment]
Working on a fix.

**Comment by keckler** [comment]
[Here](https://github.com/terrapower/armi/files/7522734/example-case.zip) is an example input suite that will trigger this failure with the current code, but will run with the fix implemented in #472 .

**Comment by john-science** [comment]
> [Here](https://github.com/terrapower/armi/files/7522734/example-case.zip) is an example input suite that will trigger this failure with the current code, but will run with the fix implemented in #472 .

Well, it's not a lot of code for a test. But it _does_ require a lot of input data, which is a bit much.  Shucks.
