### ISSUE TITLE
Eliminate the 429 "duplicate object description" warnings in doc build

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#479]
If you build the documentation:

```
cd doc
make clean
make html >docbuild.log 2>docbuild-err.log
grep "WARNING: duplicate object description" docbuild-err.log  | wc -l
```
You'll see that this message shows up 429 times. (Once for each object in armi?)

This is likely related to https://github.com/sphinx-doc/sphinx/issues/8664 and https://github.com/sphinx-contrib/napoleon/issues/30 since we do use napolean and apidoc

If we get rid of these, the number of our doc warnings will be *dramatically* reduced from 542 to 113!

**Comment by ntouran** [comment]
I tried the trick from https://github.com/sphinx-doc/sphinx/issues/8664#issuecomment-757087741 and wiped out the `.apidocs` folder but still saw the warning. Not sure if I did it right or what, or if the env variable got passed appropriately down through the make file. Warrants more investigation for sure.

**Comment by john-science** [comment]
@ntouran I think I have resolved this ticket as part of my doc PR here:  https://github.com/terrapower/armi/pull/483
