### ISSUE TITLE
Missing parameters in `findAssembly` docs

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#487]
The [table](https://github.com/terrapower/armi/blob/master/doc/user/inputs/fuel_management.rst#choosing-assemblies-to-move) in the docs that outlines how to select specific assemblies using the `findAssembly` method is incomplete. It is missing parameters which are accepted by `findAssembly` (see [here](https://terrapower.github.io/armi/_modules/armi/physics/fuelCycle/fuelHandlers.html#FuelHandler.findAssembly)). 

Instead of just adding the missing parameters, it would probably be best to programmatically generate the table based on the docstring.

**Comment by ntouran** [comment]
Yeah we might want to just delete that table entirely and link to the auto-generated docs based on the docstring: https://terrapower.github.io/armi/.apidocs/armi.physics.fuelCycle.fuelHandlers.html#armi.physics.fuelCycle.fuelHandlers.FuelHandler.findAssembly
