### ISSUE TITLE
Bug Found in buildRingScheduler

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#498]
While trying to build some code coverage tests, I wrote this test of `FuelHandler.buildRingScheduler()`:

```python
schedule, widths = fh.buildRingSchedule(1, 17, jumpRingFrom=0)
self.assertEqual(schedule, [17, 16, 15, 14, 13, 12, 11, 10, 2, 3, 4, 5, 6, 7, 8, 9, 1])
```
Notice the strange jump from 10 to 2.

At a guess, perhaps the problem is here:

https://github.com/terrapower/armi/blob/b94744fdf12f247828dd07bf99e251651b494a13/armi/physics/fuelCycle/fuelHandlers.py#L1186-L1190

Perhaps this is meant to be: `elif jumpRingTo is None:`.

**Comment by ntouran** [comment]
Weird for sure but this may not be a bug. this comes from the fact that the `refSmallCoreGrid.yaml` has 9 rings in it, and so jumpRingTo is set to 9 from `core.getNumRings()`. 

Should the thing just fail if you put a charge or discharge ring number that's greater than getNumRings? Maybe. But that can be a pain e.g. if you are param sweeping on number of rings and want to use it as e.g. an overlay.

**Comment by john-science** [comment]
@ntouran I hadn't considered the parameter sweep issues.  At the very least, I would like us to catch such edge cases and fail with a more descriptive message. But I think there is a possibility here for more error catching than we currently have.
