### ISSUE TITLE
git describe in repo with no tags produces fatal error message

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#509]
https://github.com/terrapower/armi/blob/72dd0724278a31fe7b843a1e56db1c7f8ac04f60/armi/bookkeeping/db/database3.py#L638
can produce an ominous message if running in a repository that doesn't have any tags
```
fatal: No names found, cannot describe anything.
```

This can be demonstrated with
```shell
$ git init simple
$ cd simple
$ git describe
fatal: No names found, cannot describe anything.
```
Fix appears to be piping stderr to `/dev/null` like
https://github.com/terrapower/armi/blob/72dd0724278a31fe7b843a1e56db1c7f8ac04f60/armi/bookkeeping/db/database3.py#L631-L632

**Comment by john-science** [comment]
We have 8 tags in the repo, currently:  https://github.com/terrapower/armi/tags

**Comment by drewj-usnctech** [comment]
Oh my apologies. Tags in the repo are not the issue. If I am running an ARMI run in another repository that doesn't not have tags, then this issue appears

**Comment by john-science** [comment]
I have a fix for this. Incoming.
