### ISSUE TITLE
ARMI Application Sphinx Build Error with ARMI Logger

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#518]
The ARMI framework documents can be built using the `make html` command within the `doc` directory. When building the documentation using Sphinx, it imports the ARMI `RunLogger` during the process. Once ARMI's logger is imported and configured then the logging is performed from then on with this logger rather than with Python's standard logger.

A problem arises if any errors are generated from Sphinx, as it expects the logger that is configured to have certain keywords defined in the logger's `log` method. Currently, we can see that we implement `single` and `label` kwargs that we use internally to catalog the message types as well as to perform some duplication filtering. 

https://github.com/terrapower/armi/blob/04526a658dcf59ba1e29c4613374fe23624d33f2/armi/runLog.py#L478-L519

The following table provides the kwargs that are implemented in Python's standard `Logger` (see: https://github.com/python/cpython/blob/576e38f9db61ca09ca6dc57ad13b02a7bf9d370a/Lib/logging/__init__.py#L1591-L1615):

| **Python Version** | `Logger` kwargs |
| -------------------- | ------------------ |
| 3.4 | `exc_info`, `extra`, `stack_info` |
| 3.5 | `exc_info`, `extra`, `stack_info` |
| 3.6 | `exc_info`, `extra`, `stack_info` |
| 3.7 | `exc_info`, `extra`, `stack_info` |
| 3.8 | `exc_info`, `extra`, `stack_info`, `stacklevel` |
| 3.9 | `exc_info`, `extra`, `stack_info`, `stacklevel` |
| 3.10 | `exc_info`, `extra`, `stack_info`, `stacklevel` |

Within Python's `Logger` implementation, the `log` method calls the `_log` method where it uses the `exc_info`, `extra`, `stack_info`, and `stacklevel` in Python 3.8+. The ARMI framework `log` method mirrors this implementation by implementing a `_log` method and calling it, but the main difference is that the Python's standard `log` method accepts `*args` and `**kwargs` to handle future changes.

To fix this issue with the Sphinx logging, I recommend that we at a minimum implement the `extra` kwarg to the ARMI framework's logger. Without this being implemented, I get the following error message when building my ARMI applications documentation:

```
Exception occurred:
  File "C:\tools\python379\lib\logging\__init__.py", line 1783, in log
    self.logger.log(level, msg, *args, **kwargs)
TypeError: log() got an unexpected keyword argument 'extra'
The full traceback has been saved in C:\Users\jhader\AppData\Local\Temp\sphinx-err-d34y_xg6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This is a pretty simple change, so I will put in a PR for it.

**Comment by ntouran** [comment]
I believe the sphinx logging API is designed to help alleviate these issues and decouple logging from things like ARMI's logging. https://www.sphinx-doc.org/en/master/extdev/logging.html

**Comment by ntouran** [comment]
That said, the addition of `extra` as done in #519 does seem reasonable

**Comment by jakehader** [comment]
> I believe the sphinx logging API is designed to help alleviate these issues and decouple logging from things like ARMI's logging. Sphinx logging always uses the `sphinx` namespace when getting its logger so we can decouple it through that mechanism. https://www.sphinx-doc.org/en/master/extdev/logging.html

That is true up until our logger gets configured and then it takes over has the base logger that gets initialized on the Sphinx Adapter after the `getLogger` method is called. I'm trying to figure out why out logger is being configured in my application, but no luck so far. I am think it could be from building the API docs.

**Comment by ntouran** [comment]
Is there an easy way to replicate this using the framework docs? Like if I just raise an exception in a docstring or something will I run into this issue?

**Comment by jakehader** [comment]
Hi @ntouran / @john-science - I figured out my issue with the logger for my ARMI application. The issue was that in the `conf.py` file for building the docs I configured the application erroneously, resulting in ARMI's `RunLogger` being setup and configured within Sphinx when building the documentation. Can you comment on whether or not you think adding the `extra` keyword is useful still? I couldn't reproduce this issue with the ARMI framework so I went back into my `conf.py` and found this.

**Comment by jakehader** [comment]
Closing this issue with resolution of opening a "Lessons Learned" Wiki page on https://github.com/terrapower/armi/wiki/Lessons-Learned to hopefully prevent future users from this same issue. I will close out the corresponding PR.

**Comment by john-science** [comment]
@jakehader I am of two minds when it comes to the `extra` change to the logger. On the one hand, maybe we should add all four of these two our logger, for future-proofing:  `exc_info`, `extra`, `stack_info`, and `stacklevel`.  Generally, that seems like a sound idea.  The (potential) down side is having to update all the downstream plugins for another logging feature that doesn't really help them.

Maybe the next time we need to make a breaking change to `runLog` anyway, we throw all of those in. That would be a good middle-ground. Of course, that may be a long time from now, which isn't helpful.

I like that "lessons learned" section you added to the Wiki, by the way.

**Comment by jakehader** [comment]
That's unfortunate. I assume this is because your demo app here is configuring the RunLog for ARMI. Is there a way to get around this or should we reopen this issue?

**Comment by drewj-usnctech** [comment]
The app doesn't do any configuring on import. The error is also produced by directly importing ARMI instead of the demo package.

I tried doing some `MagicMock` magic, like
```python
sys.modules.update(("armi", MagicMock()))
```
but that kicked some errors to `armi.bookkeeping` not existing. I imagine it's not a great plan to magic mock the entire armi package structure :/

**Comment by drewj-usnctech** [comment]
@jakehader would it be beneficial to re-open this issue? Or create a new one with these doc build issues?

**Comment by john-science** [comment]
I'm not sure I've ever seen the `mock.MagicMock` before:

https://pypi.org/project/mock/

My gut here is that I'm not sure we can support mocking the entire ARMI package structure.  The problem is when you import ARMI, code gets run. For instance, in `armi.context.py`.  And while I"m not 100% sure I love that idea, it has been a part of ARMI for like 8 years before I got on the project. And it would be a huge, systemic thing to try and change. Maybe one day, but not today.

The long-and-short of it is: I never expected anyone to import `doc/conf.py` directly.  That's just a file we use as part of building the docs.  So, a couple of things:

1. Sure, there might be a bug there (that _might_ be fixable with `logging.setLoggerClass(logging.Logger)`).
2. Out of curiosity, why are you importing `conf.py` manually?  What's the use-case?

**Comment by drewj-usnctech** [comment]
After some digging, I found these lines in the armi doc `conf.py`
https://github.com/terrapower/armi/blob/fd5d2dd31051206ce62696027f05a9304b499677/doc/conf.py#L187-L188

This is done after import armi, doing any `App.config`, etc. So it seems this line "undoes" the overloading of the standard library logger.

It was not clear that this line is important for building docs but adding this after any `import armi`, regardless if there were any configured apps, resolved sphinx building. I'm not sure where it needs to be added in the `conf.py` but it appears to need to go after armi does _something_ to the default logger class

**Comment by john-science** [comment]
Sorry, @drewj-usnctech  I'm not sure I follow.

That line is already in `armi/doc/conf.py`.  So... does the build still break, even with that line?

Sorry if I was not clear, I tried to point out the importance of that line to our Sphinx build in my comment above:
 
> The long-and-short of it is: I never expected anyone to import `doc/conf.py` directly. That's just a file we use as part of building the docs. So, a couple of things:
>     1. Sure, there might be a bug there (that _might_ be fixable with `logging.setLoggerClass(logging.Logger)`).

Do your Sphinx docs still not build?

**Comment by drewj-usnctech** [comment]
> The long-and-short of it is: I never expected anyone to import doc/conf.py directly

Absolutely correct. It's a file used by sphinx and should not be directly import by users.

The problem appears if I have a separate package that uses it's own `doc/conf.py` file that does not rely on the ARMI `doc/conf.py`.  Instead, a very minimal version might contain *only*
```python
import demo  # imports armi

release = demo.__version__
```

- Not attempting to build the armi docs, but the docs for an application that uses armi
- No reliance on `armi/doc/conf.py`
- No configuring of any applications
- Just an armi import so sphinx knows how to find classes, functions, etc.

Then, without the line `logging.setLoggerClass(logging.Logger)`, the sphinx logging error that started this thread is raised.

(and an addendeum) the `mock` library is great and it's part of the python standard library too! as `unittest.mock`

**Comment by john-science** [comment]
Hello again!

The design goal we have is to support logging in ARMI, and we use subclasses of the Python standard library `import logging` library.  

Now that I understand your workflow, let me explain what is happening.  When you create your `conf.py` for Sphinx build, you are calling code that calls ARMI logging methods.  Which would be fine if you configured an ARMI app of some kind. But without any configuration, the logging is not defined, thus the errors you see.

In any situation I've seen where people want to use the code in ARMI, this has been fine. People will init or config some sort of ARMI thing before they use some sort of ARMI thing.

I could try to rewrite our logging tools so they can be run without any configuration. But... conceptually, that is hard for me to envision. After all, in order to call the logging method, the log files are going to needs names and a directory to be written to, etc.

I suppose there might be some way around the bug you're seeing that doesn't involve much change to our logging. I can try to look at it today.

**Comment by drewj-usnctech** [comment]
Thanks @john-science 

I think it is still worth adding a statement to the docs and/or the [Lessons Learned wiki page](https://github.com/terrapower/armi/wiki/Lessons-Learned) documenting this workaround. 

I sympathize with bugs in dependencies causing problems. Thankfully the ~hack~workaround isn't too difficult. Just needed to be found

**Comment by ntouran** [comment]
Just had this exact same problem in another external app with barebones sphinx. Thanks for pushing through and listing the solution @drewj-tp!

Sadly the Lessons Learned Wiki is gone now!
