### ISSUE TITLE
Checking app version from command line reports ARMI version

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#522]
If I have an ARMI app with it's own name and version, say `demoapp`, and I run `demoapp --version` from the command line, the entry point prints the ARMI version, not the app version due to

https://github.com/terrapower/armi/blob/52edeb31ef44bddb77753beda7486491bf691081/armi/cli/__init__.py#L126-L136

`armi.context.APP_NAME` is modified with something like `armi.configure(DemoApp())`
https://github.com/terrapower/armi/blob/04526a658dcf59ba1e29c4613374fe23624d33f2/armi/__init__.py#L331

A further confusing part happens if the application has it's own splash logo that prints the version, e.g.,
```python
from armi.apps import App

from demo import __version__  # version for this package, e.g., A.B.C

class DemoApp(App):
    name = "demoapp"
 
    @property
    def splashText(self):
        return f"{self.name} :: {__version__}\n"
```

running `demoapp --verison` would print
```
demoapp :: A.B.C
demoapp 0.1.6
```
where the last line comes from the entry point reporting app name and ARMI version.

A proposed fix would be to expect armi app subclasses to have a version attribute, defaulting to the version of ARMI, but potentially overwritten by "concrete" applications like
```python
class App:
    name = "armi"
    version = armi.__version__
...
class DemoApp(App):
    name = "demoapp"
    version = demo.__version__
```
then `armi.configure` could update some other context variable, `context.APP_VERSION` to be used in this entry point

Kind of related to #191 and #392

**Comment by john-science** [comment]
My first thought is you can fix this by subclasses `ArmiCLI`, by simply leaving the entire `ArmiCLI` class (as in your first code snippet above) but changing the one line in the `__init__` method to include your `DemoApp.__version__`. That would solve your problem.

But. More importantly. Even if you _could_ do the above, I'm not sure you _should_.  Here me out.  I think no matter how awesome your `App` is, you will still want to report the version of `ARMI` you are using. The reason being that if you do a run today and then 2 years later look back at the logs from your run, you will want to be able to find the version of your app AND the version of ARMI used. Both are critical to understanding the run.

So my preference is that we find a way to help you report the version of your app, without changing that we are reporting the version of `ARMI` being used. Does that makes sense?

**Comment by john-science** [comment]
Hey @drewj-usnctech ,

The way we handle this in-house is to print two different versions at the start of our internal runs:

```bash
DemoApp Version: v7.0.1
ARMI Framework Version: 2.0.0
```

The idea here is that, at the very least, we want to know the version of ARMI, but _also_ the version of our `App()`. Does that make sense?

I just looked around for what different people in-house are doing, and they are all printing both versions at the top of their run. Some with beautiful ASCII art, and some like above, with just the simple strings.

Thoughts?

**Comment by drewj-usnctech** [comment]
> The idea here is that, at the very least, we want to know the version of ARMI, but also the version of our App(). Does that make sense?

Fully agree. This is super important for revisiting older runs and aligns well with some of the `App.describe` behavior in #392.

I apologize if I haven't been able to well communicate this; it's probably best seen through an example. For some of the internal apps, can you look at the output of the command line call `app --version`? If you neglect any splash screen message that shows up, the printed version should reflect the ARMI version, not the app version. Using the `DemoApp` from your comment, I believe you'll see
```
$ demoapp --version
demoapp 2.0.0
```
where `2.0.0` is not the version of `DemoApp`, but the ARMI framework version

**Comment by john-science** [comment]
Digging into this a bit more to try and build some solutions, I have some thoughts.

I have the usual concern: other `App`s are using the current functionality, so if I change the default behavior, it will break people's current workflow.

We would need to change the `App` class to get the exact functionality you want. Right now, people can put any kind of `version`, `__version__`, or `VErsI0N` string they want anyWHERE they want in their app. In order for the `ArmiCLI` to grab the version of the `App`, we would need to narrowly constrain WHERE the version for each app lives.

I've been playing around with this, and I am trying to decide what we could do to not break everyone else's current apps, but get what you want as well.  Here are my ideas:

1. I could add an optional `--app-version` flag, that would try and return a valid version string for the current `App()`.  In that case, you can still access the `App` version, but other code that currently depends on getting the ARMI version wouldn't break.
2. I could just make you a CLI class like `ArmiCLI` that has the versioning they way you need it. (That would go in your code, but not ARMI.)
3. I could add an optional input to the `ArmiCLI` constructor: `def __init__(self, version=None):` that would allow you to pass in the version string you want to over-ride the usual ARMI one. (I'm not certain I love this.)

Thoughts?

**Comment by ntouran** [comment]
This is a fair point. your application's `--version` entry point should be controllable by your application. Drew's suggestions are good. 

I think we should probably:
* Define a new method or property on  `App` alongside `getSplash` called `getVersion` that by default returns `armi.__version__. 
* Change the default entry point config to use this new `getVersion` rather than the `armi.__version__` full path

That way app devs can define their getVersion to go get `myapp.__version__`  or whatever.
