### ISSUE TITLE
Missing thermal expansion data in `ThoriumOxide` material class

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#537]
The [`ThoriumOxide`](https://terrapower.github.io/armi/_modules/armi/materials/thoriumOxide.html#ThoriumOxide) material class is missing the `linearExpansionPercent` method necessary for calculating thermal expansion of the material. Without it, the code fails if thermal expansion is attempted.

I can add it in using public sources and submit a PR shortly.

**Comment by ntouran** [comment]
Truth. That was just a "didn't have a public source on hand" issue during the open source effort, though surely some exist. If you can find some and add that'd be wonderful.

**Comment by john-science** [comment]
It appears that Chris _did_ find the public source, which he documents briefly in PR #548
