### ISSUE TITLE
Missing picture in the `nuclideBases` description

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#550]
If you're looking at the [Sphinx documentation for the `nuclideBases` module](https://terrapower.github.io/armi/.apidocs/armi.nucDirectory.nuclideBases.html), you might notice that there is a link to a figure in the docstring:

![image](https://user-images.githubusercontent.com/21959600/151247244-5822e1e5-2fe5-4e8a-87f9-cb5400519e1e.png)

This link goes nowhere for me, I think because the figure doesn't exist.

**Comment by john-science** [comment]
I can confirm this has been broken since the `0.2.0` release on Nov 19, 2021: https://terrapower.github.io/releases/armi/v0.2.0/.apidocs/armi.nucDirectory.nuclideBases.html

@ntouran How long has it been since these class diagrams displayed?

**Comment by john-science** [comment]
Okay, it is my guess here that our docs used to have some automagical class diagrams, but only a couple relics of this remain.

Probably, these diagrams were just fragile and hard to maintain. (Such things always are.)

I am thinking that removing these defunct links and this dependency is the right solution:

https://github.com/terrapower/armi/blob/2ae923ee7a0f088b893bd5aa4592ac3f9c2803de/doc/conf.py#L115

**Comment by john-science** [comment]
Okay, @keckler , there is a PR open for this:  https://github.com/terrapower/armi/pull/556

**Comment by keckler** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/21959600/153024126-29c960b0-5e47-4ece-ba12-31118410b16a.png)
