### ISSUE TITLE
Can we integrate Sphinx Needs into ARMI?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#564]
It would be GREAT to:

1. Make a good set of requirements for ARMI.
2. Use Sphinx Needs to auto-validate them using unit tests.
3. Add the requirements and their proof to our docs.

This Issue won't focus on (1) or (3) above, but more just (2); testing the tooling and putting it in place with some connection to the docs.

References:

* [Sphinx Needs](https://sphinxcontrib-needs.readthedocs.io/en/latest/index.html)
* [Requirements definition in armicontrib-dif3d](https://terrapower.github.io/armicontrib-dif3d/design.html)

**Comment by ntouran** [comment]
Yeah I really like sphinx needs for this purpose and fully support using it to document requirements and their linkages to implementation docs and tests.

**Comment by jakehader** [comment]
Yes I think we can. There were a couple of quirks about it that I ran into on my testing but the developers were pretty responsive.

**Comment by john-science** [comment]
It turns out we can!

A full implementation of the technology was pushed into ARMI in this PR: https://github.com/terrapower/armi/pull/590

We have not fully implemented all our Requirements yet. That comes next. But we have Requirements in Documentation, that are tied to Implementations and Tests, and use `sphinx-needs` to make all that happen.
