### ISSUE TITLE
Allow buGroups to be defined in other units

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#570]
Yes you're right that it is %FIMA. This has pretty much been the standard use case at TerraPower, but given that there is a burnup parameter for MWdkg on the blocks (maybe composites too?) then this could be an easy enough extension. I think that there is some interplay with the cross section / lattice physics interface with which parameter is being compared to so maybe we could need to configure an application for which "burnup" is the standard to use.

Consider opening another issue / feature request on this if it is important for your work. Burnup in MWd/kg is clearly a standard in the industry though. Also, if you have time to help with this type of PR it would be appreciated of course! 🙂

_Originally posted by @jakehader in https://github.com/terrapower/armi/discussions/562#discussioncomment-2137565_

**Comment by john-science** [comment]
@jakehader Surely ARMI contains enough information about the reactor to convert between the two units?  I mean, we are supposed to have a full-and-complete model of the reactor.

**Comment by john-science** [comment]
@jakehader  Sorry, let me be clear.  My idea above (about converting the units as earlier as possible) is not an ideological one.  It is not my "preference".

I suggested it because I believe it will save us time. In the short run, it will be faster to finish this ticket this way.

That was my suggestion for how to implement this task to make it as easy as possible.

If it turns out that my idea is infeasible, that's fine. I won't argue against the impossible.

**Comment by jakehader** [comment]
@drewj-usnctech, do you have the capability to calculate MWd/kg in your depletion code that is being used? If so, I think that on exit of that plugin/interface you can just populate the %FIMA. In that way you get your MWd/kg on the block to track and then there is a mapping back to %FIMA that can be used for XS generation and other types of things within the ARMIA framework. 

For now I think the best we can do for you is to document these units in the buGroups and then provide a basis for why this a standard we chose for the system. What do you think?

**Comment by drewj-usnctech** [comment]
@john-science @jakehader thanks for the feedback and suggestions. We do use MWd/kg far more heavily in our depletion routines, letting %FIMA be more like a secondary result, typically at EOL.

I think it's not unreasonable for a depletion plugin to be expected to provide not just isotopics but a %FIMA calculation on a given block. Likely non-trivial but if that's the thing that makes more of ARMI happy without substantial changes, then it might be the way forward

**Comment by jakehader** [comment]
@drewj-usnctech you might make use of the getNumbersOfAtoms on a composite/block and there should be a parameter on the blocks for the initial heavy metal mass/atoms already when the model gets loaded. It might be pretty easy to do, but feel free to reach out to me if you need help with your specific application. I am going to close the issue now.
