### ISSUE TITLE
Add validation to case settings where appropriate

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#580]
I have noticed a handful of case settings that have implied bounds on their ranges, but no check is ever done to confirm the user input a valid value. For instance, `burnSteps`, `nCycles`, and `power` should all be non-negative but nothing stops the user from entering negative numbers.

In all of these instances, the code crashes somewhere where it is not necessarily clear what caused the crash. And in all instances, we could easily set a bound on the possible input values using the `schema` attribute when each of the `Setting`s are defined and using some of the built-ins of `Voluptuous` (which we are already using). The schema for these cases would look something like `voluptuous.Range(min=0)`. Very easy to add in.

I think it would be worthwhile to go through the case settings and add simple validators where they are not currently in place.

Does anybody have any objections to me doing this?

**Comment by john-science** [comment]
I think this is a good catch, and I'm all for someone fixing it. You can do it if you like. If not, provide as full a list as you can in the ticket, so someone else has a good starting place to take a stab at it.

**Comment by jakehader** [comment]
I think a settings overhaul using voluptuous would be great.

**Comment by keckler** [comment]
I will do some work on this.

**Comment by keckler** [comment]
Checklist of settings to add validation:

From [globalSettings](https://github.com/terrapower/armi/blob/master/armi/settings/fwSettings/globalSettings.py): 
| Setting | Range | Complete |
| --- | --- | --- |
| numProcessors | >= 1 | |
| axialMeshRefinementFactor | >= 1 | |
| minMeshSizeRatio | > 0 | |
| cycleLength | >= 0 | |
| availabilityFactor | >= 0 | |
| burnSteps | >= 0 | |
| beta | 0 < f_i <= 1 | |
| decayConstants | lambda_i > 0 | |
| buGroups | 0 < p_i <= 100 | |
| burnupPeakingFactor | >= 0 | |
| startCycle | >= 0 | |
| startNode | >= 0 | |
| lowPowerRegionFraction | 0 <= F <= 1 | |
| mpiTasksPerNode | >= 0 | |
| nCycles | >= 1 | |
| numCoupledIterations | >= 0 | |
| power | >= 0 | |
| skipCycles | >= 0 | |
| targetK | >= 0 | |
| acceptableBlockAreaError | > 0 | |
| independentVariables | list of tuples | |
| Tin | > -273 | |
| Tout | > -273 | |

From [databaseSettings](https://github.com/terrapower/armi/blob/master/armi/settings/fwSettings/databaseSettings.py):
| Setting | Range | Complete |
| --- | --- | --- |
| dbStorageAfterCycle | >= 0 | |

From [reportSettings](https://github.com/terrapower/armi/blob/master/armi/settings/fwSettings/reportSettings.py):
| Setting | Range | Complete |
| --- | --- | --- |
| timelineInclusionCutoff | 0 <= f <= 100 | |
