### ISSUE TITLE
Clarify deprecation of select `HistoryTrackerInterface` methods

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#583]
Within the `HistoryTrackerInterface` class, the `getTimeIndices` method's docstring says that the method is no longer functional:
https://github.com/terrapower/armi/blob/a3d78a9330ec549bf2fe586230dd3a0044aaf66d/armi/bookkeeping/historyTracker.py#L307-L312

I noticed that some other methods in the class call to that method, however, and do not have similar warnings. For instance [`getBOCEOCTimeIndices`](https://github.com/terrapower/armi/blob/a3d78a9330ec549bf2fe586230dd3a0044aaf66d/armi/bookkeeping/historyTracker.py#L350) and [`getAssemParamHistory`](https://github.com/terrapower/armi/blob/a3d78a9330ec549bf2fe586230dd3a0044aaf66d/armi/bookkeeping/historyTracker.py#L370).

The status of these methods should probably be clarified. Assuming they are not working as a result of `getTimeIndices` being deprecated, we should make that clear. 

Or alternatively, is there any reason not to get rid of them entirely? I grep'd through the codebase and can't find anywhere that they are used.

**Comment by jakehader** [comment]
Hi @keckler, if I recall I believe the goal was to remove the history tracker going forward in favor of the getHistories implementation on database3, which is pretty quick doesn't blow up the RAM for a case (trading hard drive space in the hdf5 database for storage of assembly objects on the interface instance).  

@john-science / @ntouran, I am curious as well where we are at with removing the history tracker and if there are still fundamental things that need to be implemented in database3 so that it covers the use cases.

**Comment by john-science** [comment]
> This is no longer functional

Sigh.  No, I hadn't seen that.  The best policy is certainly to remove all broken code from the repo ASAP.

I note that it is only used in two places in ARMI:

In `getBOCEOCTimeIndices`:
https://github.com/terrapower/armi/blob/a3f23ed01538aaaeb1dc58b5bf158def918901ef/armi/bookkeeping/historyTracker.py#L350-L352

And `getAssemParamHistory`:
https://github.com/terrapower/armi/blob/a3f23ed01538aaaeb1dc58b5bf158def918901ef/armi/bookkeeping/historyTracker.py#L384

Neither of those two methods are used elsewhere in ARMI. They are not covered in unit tests. And I can not find anyone in the ARMI ecosystem who is using them.

So. I wonder if any of the three of these methods would even be missed if they were removed entirely:

* `getTimeIndices`
* `getBOCEOCTimeIndices`
* `getAssemParamHistory`

@jakehader  You seem to know the history here. Are these methods still used anywhere? Or desirable?

**Comment by jakehader** [comment]
I think the intent was to migrate all history tracker code to the db3 code. There may some instances in our plugins, but I tend agree that we should assess and remove stale code as soon as we can because I believe the direction now is to use db3 going forward.

**Comment by john-science** [comment]
I've opened a branch. 

I'm just going to try removing these and see if anyone complains.  Seems easier than keeping on talking about it.
