### ISSUE TITLE
Its unclear how to set symmetry correctly

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#589]
I converted a 1/3 core reactor to full core using `ThirdCoreHexToFullCoreChanger.convert`

After expanding the symmtry is set using

```python
r.core.symmetry = geometry.SymmetryType(
    geometry.DomainType.FULL_CORE, geometry.BoundaryType.NO_SYMMETRY
)
```

My code also tests weather its full core using 

`if self.r.core.isFullCore`

which checks

```python
return self.symmetry.domain == geometry.DomainType.FULL_CORE
```

Since `core.symmetry` was set, but `self.symmetry.domain` is checked for symmetry, it still believes it is not full core

Please advise why both  `core.symmetry` and `self.symmetry.domain`  exist, and how to communicate to ARMI that it is now full core.

**Comment by john-science** [comment]
> why both core.symmetry and self.symmetry.domain exist...

If you do a quick `type()` on those variables, you will find that `r.core.symmetry` is of type `SymmetryType`:

https://github.com/terrapower/armi/blob/035711afd1514ec5914c59c3cf898dfb3213c5a4/armi/reactor/geometry.py#L280-L282

And `r.core.symmetry.domain` is of type `DomainType`:

https://github.com/terrapower/armi/blob/035711afd1514ec5914c59c3cf898dfb3213c5a4/armi/reactor/geometry.py#L125-L127

So, to answer your question "why both core.symmetry and self.symmetry.domain exist", that is because the `SymmetryType` has one more important piece of information than just `DomainType`, it also contains `BoundaryType` information.  So, is the boundary periodic or reflective? That's really the question `SymmetryType` answers.

**Comment by john-science** [comment]
@onufer As to your second question, it sounds like you are experiencing, `ThirdCoreHexToFullCoreChanger.convert()` isn't properly creating a full core for you. Or, more probably, it IS, but it's not setting something that recognizes it's a full core.

I will check now to see if I can reproduce that as a bug.

If I can't, I might need to talk to you about getting your working data so I can reproduce it there. 

Let me test to see if I can reproduce the bug first though.

**Comment by john-science** [comment]
For the second half of your question:

> how to communicate to ARMI that it is now full core.

Perhaps this unit test will be a good example of how that geometry changer is supposed to work:

https://github.com/terrapower/armi/blob/035711afd1514ec5914c59c3cf898dfb3213c5a4/armi/reactor/converters/tests/test_geometryConverters.py#L317-L333

I ran this unit test locally, and on line 332 there, I added in this line:

```python
self.assertTrue(self.r.core.isFullCore) 
```

and the test still passed. It looks to me like this `ThirdCoreHexToFullCoreChanger.convert()` works as I'd expect. There isn't a bug (at least not an obvious one).  So, are you seeing something different here? Did you perhaps uncover some bug using very specific inputs?

**Comment by onufer** [comment]
at the end of your unit test, can you test
 self.r.core.isFullCore is true. that would be where a possible bug would live

**Comment by john-science** [comment]
@onufer I have ammended the unit test as follows, and it still passes:

```python
    def test_growToFullCoreFromThirdCore(self):
        """Test that a hex core can be converted from a third core to a full core geometry.""" 
        # Check the initialization of the third core model  
        self.assertFalse(self.r.core.isFullCore)  
        self.assertEqual( 
            self.r.core.symmetry,   
            geometry.SymmetryType( 
                geometry.DomainType.THIRD_CORE, geometry.BoundaryType.PERIODIC 
            ), 
        ) 
        initialNumBlocks = len(self.r.core.getBlocks()) 
        # Perform reactor conversion 
        changer = geometryConverters.ThirdCoreHexToFullCoreChanger(self.o.cs) 
        changer.convert(self.r) 
        # Check the full core conversion is successful 
        self.assertTrue(self.r.core.isFullCore)    # NOTE: This is new.
        self.assertGreater(len(self.r.core.getBlocks()), initialNumBlocks)  
        self.assertEqual(self.r.core.symmetry.domain, geometry.DomainType.FULL_CORE) 
        # Check that the geometry can be restored to a third core  
        changer.restorePreviousGeometry(self.o.cs, self.r) 
        self.assertEqual(initialNumBlocks, len(self.r.core.getBlocks())) 
        self.assertEqual(  
            self.r.core.symmetry,  
            geometry.SymmetryType( 
                geometry.DomainType.THIRD_CORE, geometry.BoundaryType.PERIODIC 
            ),  
        ) 
        self.asserFalse(self.r.core.isFullCore)  # NOTE: This is new.
```

So the basic unit test checks out. Is this not what you expected? OR do you see something different with your data?

**Comment by onufer** [comment]
Thanks for explanation, issues is probably on my end
