### ISSUE TITLE
Add settings options to the Settings Report docs page

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#596]
Right now in the docs we have a ["Settings Report"](https://terrapower.github.io/armi/user/inputs/settings_report.html) page which lists all of the settings in the framework. It looks like this:
![image](https://user-images.githubusercontent.com/21959600/157955171-648acf9c-3ebc-4f23-aee8-280be3306e24.png)

It would be nice if the table on this page would also include the settings options, for those settings which have discrete choices.

For instance, `genXS` has two real possibilities:
https://github.com/terrapower/armi/blob/b5ddc61fb74f4cd97d3e9de4d087402b1eaf57e8/armi/physics/neutronics/settings.py#L111-L120

It would be nice if these options were listed in the report, instead of the user having to look into the source code to figure that out.

I think this would be easy to do just by adding another line into the loop [here](https://github.com/terrapower/armi/blob/master/doc/user/inputs/settings_report.rst).

**Comment by john-science** [comment]
That seems doable.

Things to watch out for, implementing this:

* make sure the table is still readable with the extra column
* make the options readable
