### ISSUE TITLE
Misleading docstring in `IsotxsLibrary.getNuclide()`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#599]
The docstring says that it will either return the value or `None`, but this method will never return `None` (unless the dict value itself is actually `None`) because it raises an error in the case that the key does not exist. Either the docstring is wrong, or the method is supposed to do something else.
https://github.com/terrapower/armi/blob/7d9ef5f8c0db459da167e3330fc6aa932d0255ce/armi/nuclearDataIO/xsLibraries.py#L407-L429

**Comment by john-science** [comment]
The docstring is just out-of-date.  

I'm a sure there are many out-of-date docstrings in the repo.

**Comment by keckler** [comment]
Probably. Just pointing it out.
