### ISSUE TITLE
`tox.ini` contains reference to nonexistent `mpicov` test environment in its `envlist`

### ISSUE THREAD

**Issue by joshuavictorchen** [terrapower/armi#603]
`mpicov` is provided as an argument to `envlist` in `tox.ini`, but is not defined as a test environment. This results in an extraneous run of the default `[testenv]` commands at the end of the call stack if an empty `tox` command is executed.

https://github.com/terrapower/armi/blob/ba08a30ec0142d509e7533bc8d83479ab84d0bbf/tox.ini#L2

I believe this is an artifact from #521. The `mpicov` argument was first introduced along with a corresponding `[testenv:mpicov]` environment definition here:

https://github.com/terrapower/armi/pull/521/commits/2c4cc12f57e79b10a2e2d8ef49084f9be589e9fd#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449

But it was not updated when that environment definition was changed to `[testenv:mpitest]` here:

https://github.com/terrapower/armi/pull/521/commits/6c35012b18f2ec0679525537db456e77752deae2#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449

`envlist`'s `mpicov` argument should be updated to `mpitest` to reflect this change, or removed altogether. I suggest the latter, since the `mpitest` environment only works on POSIX/BASH Linux and would cause the empty `tox` command to fail for Windows users, if included.

**Comment by john-science** [comment]
Just to note: `mpitest` IS used on GitHub:

https://github.com/terrapower/armi/blob/498472b2b5255b7da9985b758faba2f6b2e34581/.github/workflows/unittests.yaml#L26

It is an important test line that we need to preserve.
