### ISSUE TITLE
Can we remove XML Settings file Support?

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#608]
To the best of my knowledge, no one is using our XML settings files.  (I could be very wrong.)

And if no one is using them, I would really like to remove the functionality. There is a LOT of code and cruft in our codebase, and it would be a significant reduction in complexity to remove the functionality.

If no one is using them.

**Comment by john-science** [comment]
@jakehader @keckler @ntouran Does anyone use XML settings files in ARMI?

**Comment by jakehader** [comment]
Not anymore. I use the xml geometry, but not settings.

**Comment by john-science** [comment]
> Not anymore. I use the xml geometry, but not settings.

@jakehader 

OH! Damn. I am most of the way through removing XML Geometry from the code base. I take it you missed this discussion earlier in the week?

https://github.com/terrapower/armi/issues/450#issuecomment-1069654528

Okay, well, I'll switch to removing XML settings.

**Comment by jakehader** [comment]
Nah remove the xml geom and I'll just update the code that uses it! It's not that bad to switch to yaml.

**Comment by john-science** [comment]
> Nah remove the xml geom and I'll just update the code that uses it! It's not that bad to switch to yaml.

Well, it sounds like I should remove the XML Settings first. If no one is using it, that's better to remove first. NBD

Also, if you have code that supports XML Geom, that'll be a bigger change than what I thought it would be.

No worries. Thanks for the info!

**Comment by ntouran** [comment]
I agree that we can deprecate xml settings support.
