### ISSUE TITLE
No rotations in growToFullCore()

### ISSUE THREAD

**Issue by alexhjames** [terrapower/armi#616]
When a third core with applied spatial properties (ie assembly corner temperature) is grown to a full core, the spatial properties are not rotated when the assembly is copied. For example, if an assembly in the first third is bowing outward from a mismatch in corner temperatures, the mirror assembly in the other two thirds should also be bowing outward from corner temperature mismatch. This requires that the corner temperatures get rotated when the assembly is copied in the growToFullCore().

**Comment by john-science** [comment]
@ntouran Happily, Alex has already opened a PR for this:  https://github.com/terrapower/armi/pull/614

I was curious if you thought the solution to the bug belongs in `growToFullCore()`, or if maybe it's more widespread in how we read databases?  I'm having trouble telling.
