### ISSUE TITLE
y-axis label in `plotAssemblyTypes`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#623]
In [`plotAssemblyTypes`](https://github.com/terrapower/armi/blob/907f2b49d4063cfd07068431698d22dab4c7d267/armi/utils/plotting.py#L694), the plots are always generated with a y-axis that says "Thermally Expanded Axial Heights (cm)", as shown in the attached figure.

![image](https://user-images.githubusercontent.com/21959600/163065165-bc8ca1af-be94-470d-aca4-10b8c1b16cfd.png)

This can't be changed by the user, even though that description may not be accurate for whatever the user is wanting to plot. For instance, maybe the user didn't thermally-expand their assembiles. Or, whenever @albeanth 's changes to allow thermal expansion of blocks is complete, the state of the assemblies at time of plotting could vary. Or a user can just plot whatever they want at any point!

So I am proposing that either the default y-axis title be changed to something more generic (would be done [here](https://github.com/terrapower/armi/blob/907f2b49d4063cfd07068431698d22dab4c7d267/armi/utils/plotting.py#L785)), or that the function's API be changed to allow for an optional y-axis label that will be applied.

Anybody have any objections to this? Seems like a harmless change.

**Comment by keckler** [comment]
Also, in general, it would be nice to make this plotting capability more flexible for different plot titles, widths, etc.

**Comment by john-science** [comment]
This seems like a fair request. Though the original purpose of the plotting function is very specific:

https://github.com/terrapower/armi/blob/907f2b49d4063cfd07068431698d22dab4c7d267/armi/utils/plotting.py#L702

So, the original purpose of this method isn't as general as this:

> Or a user can just plot whatever they want at any point!

BUT if you like, you could change the method to take two more inputs: 

1. a Y-axis label
2. a title

As long as the defaults remain, that seems like a minor change to me.
