### ISSUE TITLE
Dummy Assignments in gamiso.addDummyNuclidestoLibrary() Are Backwards

### ISSUE THREAD

**Issue by Nebbychadnezzar** [terrapower/armi#630]
I noticed the following warning while using a downstream project.

`[removed]\armi\nuclearDataIO\cccc\gamiso.py:96: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if vv in ["jj", "jband"]:`

This is a numpy warning, which seemed odd to me. In looking at the code block it was complaining about, it seems like it is not doing what it is supposed to.

```python
# Copy gamiso metadata from the isotxs metadata of the given dummy nuclide
for kk, vv in dummyNuclide.isotxsMetadata.items():
    if vv in ["jj", "jband"]:
        newDummy.gamisoMetadata[vv] = {}
       for mm in dummyNuclide.isotxsMetadata[vv]:
           newDummy.gamisoMetadata[vv][mm] = 1
    newDummy.gamisoMetadata[kk] = dummyNuclide.isotxsMetadata[kk]
```

`jj` and `jband` are keys in the `isotxsMetadata` dictionary, but the if-block is checking the values instead and then using the values as keys for the new dictionary. That doesn't make sense to me.

**Comment by Nebbychadnezzar** [comment]
Is what was meant the following?

```
# Copy gamiso metadata from the isotxs metadata of the given dummy nuclide
for kk, vv in dummyNuclide.isotxsMetadata.items():
    if kk in ["jj", "jband"]:
        newDummy.gamisoMetadata[kk] = {}
            for mm in vv:
                newDummy.gamisoMetadata[kk][mm] = 1
    else:
        newDummy.gamisoMetadata[kk] = dummyNuclide.isotxsMetadata[kk]
```

**Comment by john-science** [comment]
I would love to see the error first-hand.

Can you give me some code that will reproduce it, that just uses ARMI (and no proprietary software)?

**Comment by john-science** [comment]
Sadly, I note that the method in questions: `addDummyNuclidesToLibrary()` is not covered by unit tests.

And, at least in ARMI, that method is only called in one place: `mergeXSLibrariesInWorkingDirectory()`, which is only like half tested.

Is that what you're using? `mergeXSLibrariesInWorkingDirectory`?

**Comment by Nebbychadnezzar** [comment]
You're asking for a lot here, John...it would require me to know what I'm talking about...which I don't.

**Comment by Nebbychadnezzar** [comment]
You're asking for a lot here, John...it would require me to know what I'm talking about...which I don't.

**Comment by john-science** [comment]
@Nebbychadnezzar  Maybe you can _show_ me this error happening, so I can see a little more context?

**Comment by Nebbychadnezzar** [comment]
This is coming from executing Nala. From what I can tell, the function is indirectly called during the execution of the MC2 interface for smashing cross sections together. That interface calls `mergeXSLibrariesInWorkingDirectory`, which in turn calls `addDummyNuclidesToLibrary`.

I don't have much to offer in terms of showing. I happened to look at the .stderr file written to the execution directory of a Nala run. The warning quoted above can be found in that file, and that's all I see. It is not something that I was "personally" executing...just part of the interface stack for the Nala run. Everything otherwise seems to run fine, so it doesn't seem like a harmful bug (if it is one...). I can show you the setup though, at your convenience; there's nothing urgent on this.

**Comment by john-science** [comment]
If I _had_ to guess, I would say that it's complaining about "element-wise" comparison here:

> vv in ["jj", "jband"]

So maybe `vv` is a NumPy array and not just a string?  So maybe it's supposed to be `kk` there and not `vv`?

Or it's a NumPy "char array", which is supposed to look like a string, but technically isn't.

**Comment by john-science** [comment]
Thanks @Nebbychadnezzar !

Okay, after reviewing the situation, this is clearly a bug, because the line should ready:

```python
if kk in ["jj", "jband"]:
```

For testing purposes, here is some (random/arbitrary) test data:

```python
for kk, vv in dummyNuclide.isotxsMetadata.items():
    print(f"kk: {type(kk)} {kk} // vv: {type(vv)} {vv}")

kk: <class 'str'> nuclideId // vv: <class 'str'> DUMMY
kk: <class 'str'> libName // vv: <class 'str'> 
kk: <class 'str'> isoIdent // vv: <class 'str'> 
kk: <class 'str'> amass // vv: <class 'float'> 0.0
kk: <class 'str'> efiss // vv: <class 'float'> 0.0
kk: <class 'str'> ecapt // vv: <class 'float'> 0.0
kk: <class 'str'> temp // vv: <class 'float'> 863.1
kk: <class 'str'> sigPot // vv: <class 'float'> 0.0
kk: <class 'str'> adens // vv: <class 'float'> 1.1e-15
kk: <class 'str'> classif // vv: <class 'int'> 0
kk: <class 'str'> chiFlag // vv: <class 'int'> 0
kk: <class 'str'> fisFlag // vv: <class 'int'> 0
kk: <class 'str'> nalph // vv: <class 'int'> 0
kk: <class 'str'> np // vv: <class 'int'> 0
kk: <class 'str'> n2n // vv: <class 'int'> 0
kk: <class 'str'> nd // vv: <class 'int'> 0
kk: <class 'str'> nt // vv: <class 'int'> 0
kk: <class 'str'> ltot // vv: <class 'int'> 4
kk: <class 'str'> ltrn // vv: <class 'int'> 3
kk: <class 'str'> strpd // vv: <class 'int'> 0
kk: <class 'str'> scatFlag // vv: <class 'numpy.ndarray'> [100 101 102]
kk: <class 'str'> ords // vv: <class 'numpy.ndarray'> [1 1 1]
kk: <class 'str'> jband // vv: <class 'dict'> {(0, 0): 1, (1, 0): 1, (2, 0): 1}
kk: <class 'str'> jj // vv: <class 'dict'> {(0, 0): 1, (1, 0): 1, (2, 0): 1}
```

**Comment by john-science** [comment]
Please Note, I have a PR up for this here:  https://github.com/terrapower/armi/pull/647
