### ISSUE TITLE
getWettedPerimeter assumes a ducted hex assembly

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#642]
https://github.com/terrapower/armi/blob/b1f78b2aae73d5dc8a7a41e041c01378378080fc/armi/reactor/blocks.py#L513-L526

The routine assumes a wire-wrapped, ducted, hex assembly, but it's implemented on the base `Block` class. It should probably only be implemented for the `HexBlock` class, because it makes hex-specific assumptions (like duct perimeter = 6 * pitch / sqrt(3)).

**Comment by keckler** [comment]
Also, what happens when `wore = self.getComponent(Flags.WIRE)` returns `None`? Can you then `getDimension` on `None`? Seems like that should cause a failure.

**Comment by john-science** [comment]
It looks like someone was playing a bit fast-and-loose, yeah.

Seems to me it would be easy enough to fix though. I'll take it.
