### ISSUE TITLE
Settings validation resolution when user can't be prompted

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#651]
Within the [`settingsValidation`](https://terrapower.github.io/armi/.apidocs/armi.operators.settingsValidation.html) module, there is the ability for a case settings object to be inspected using an `Inspector`. The `Inspector` will go through all valid queries and check the user's case settings to see that a bunch of common-sense criteria are met. All of those queries in the framework are located here:
https://github.com/terrapower/armi/blob/bbec775f770743826f87dcb975518e9113eb6693/armi/operators/settingsValidation.py#L311-L622

When the user submits a job locally and one or more of the queries fails inspection, a prompt will be sent to the user asking how to resolve the issue. For instance
![image](https://user-images.githubusercontent.com/21959600/166306227-a839980e-2f10-47a8-8114-0de9891ad372.png)

Each of the queries is also associated with a potential resolution (or sometimes only the option to do nothing), and if the user opts to use that resolution, then ARMI will make the necessary change to the case settings object, re-inspect the settings, and keep prompting the user until everything looks kosher. 

However, in cases where the user cannot be prompted for whatever reason (perhaps they are running on a remote machine), the question is instead printed in the log file, but the user cannot make any decisions, nothing is changed in the case settings, and the run continues even though ostensibly something is wrong.

I think that this system of just continuing the run when a setting-clash is known to exist is probably bad practice, because it gives the user the impression that their run is valid when in fact something is known to be wrong.

I think there are two alternatives that we might consider for cases when the user cannot be prompted to make a decision about clashing settings:
1. When a query fails, the run should fail, forcing the user to actually update their case settings to be compatible with the queries and resubmit. This is annoying to the user and might break some existing workflows, but feels more in line with the intent of the settings validation system in the first place.
2. When a query fails, the default action is auto-implemented and a note is printed in the log that some case setting has been changed. This is nicer to the user, but may somewhat hide from them that they did something wrong in the first place. Also, this option would need to handle the possibility that an infinite loop may be created through the resolution of one query breaking another.

Any thoughts?

@ntouran @jakehader @onufer @john-science

**Comment by ntouran** [comment]
We have fought with the settings validation system a lot and gone back and forth. Lots of times the questions are just to guide you through things that *might* be wrong. When the system just crashes in a validation error, lots of power users complain that they can't get their jobs to run even though they know what they're doing. This can be really frustrating. 

Running remotely must be automatically triggering the ``--batch`` argument, right (https://terrapower.github.io/armi/.apidocs/armi.context.html#armi.context.Mode)? That's why they're not crashing?

Maybe we could have it crash automatically in ``INTERACTIVE`` mode but run no matter what in ``BATCH`` mode.

**Comment by keckler** [comment]
I sympathize with the frustration of the power users. 

But I also see the other side of things, where a developer (such as myself) might try to use the settings validation to force a user to make decisions about certain case settings that don't have clear defaults. So if I, as a developer, need a value to exist in the case settings under certain conditions but can't pick a reasonable default for that value, the settings validation system looks like a pretty good way to force the user to pick something. But if they just submit their job in `BATCH` mode and it effectively bypasses the settings validation, then that won't work.

> Maybe we could have it crash automatically in INTERACTIVE mode but run no matter what in BATCH mode.

I think with this suggestion you are effectively saying that we no longer even prompt the user for a response at all? From my understanding, `INTERACTIVE` mode is currently the scenario in which a user can answer the prompt and fix the issue. So I don't think understand your suggestion, but that could be a misunderstanding on my part.

Another option I could think of is to add a new case setting to ARMI that let's the user decide how to proceed when the settings validation has questions. Something like `settingsValidationDefaultBehavior` with the following options:
- `askOrFail` : The default case. Prompt the user, if possible, or kill the job if not
- `askOrAutoCorrect` : Prompt the user, if possible, or just accept the suggested answer to the query if not
- `autoCorrect` : Don't even bother prompting the user, just accept the suggested answer to all queries
- `ignore` : Don't even bother prompting the user and do not take any action on all queries. Continue running the case as-is

This should satisfy power users, and makes it very explicitly clear that they are overriding behavior that a developer believes is incorrect. It's like SUDO capabilities to override the settings validator.

**Comment by Nebbychadnezzar** [comment]
> I think that this system of just continuing the run when a setting-clash is known to exist is probably bad practice, because it gives the user the impression that their run is valid when in fact something is known to be wrong.

I'd like to log here that I didn't know this was an issue and ended up making this assumption, and so was burned by it. 😢

**Comment by keckler** [comment]
Ultimately it is on the user to check their output and justify any warnings. On this note, I will close this ticket because otherwise we would have to make an API-breaking change. 

I still don't like it, but that's okay 😄
