### ISSUE TITLE
Can't easily use `voluptuous.Range` schema to validate settings because we allow settings from the command line

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#669]
I noticed this in the course of executing #595 .

We have a test in settingsIO that tests the ability to parse settings from the command line:
https://github.com/terrapower/armi/blob/a3327a44c34bdce7a16cc57ba6bce0f01d1d5fd9/armi/settings/tests/test_settingsIO.py#L154-L161

Apparently settings that come in like this from the command line are always strings. If you try to put an `int` in there, for instance, the parser can't handle it.

So then when the setting is read in, the setting schema is applied. If the setting has a custom schema assigned to it, then that is applied. If not, the schema defaults to just coercing the value to the same type as the setting's default. The logic for this is here:
https://github.com/terrapower/armi/blob/a3327a44c34bdce7a16cc57ba6bce0f01d1d5fd9/armi/settings/setting.py#L153-L168

The issue with values from the command line being an `str` is that `str`s can't be compared against numeric types. So if I wanted to, for instance, assign a custom schema to a setting just to test the range on that value, instead of using `voluptuous.Range(min=1)`, I would have to instead use `voluptuous.Range(voluptuous.Coerce(type(self.default), min=1)`.

So really, anytime somebody wants to validate a user setting, they should first be coercing the type, which is pretty cumbersome. This obviously isn't really a capital-p Problem, but it feels like something that could be more efficiently rectified if it were done higher up in the process, instead of writing out that longer coercion every time that a new setting is added. Plus, it is just kinda confusing to have to have to do that coercion on effectively every custom schema.

Any thoughts?

**Comment by john-science** [comment]
Well, I have a couple thoughts of the hot-takes variety:

1. I am _not_ very happy with the idea of relying more and more on entering settings from the command line. There are numerous reasons for this:
  a. Most ARMI users are merely doing `import armi`, and they are not running a command line program.
  b. Most ARMI users who _are_ executing an `ARMI.apps.App()`, do so on a computing cluster, where they are not present to type anything on the command line.
  c. The command line portion of hand-editing during `SettingsValidation` is meant to be a niche-case, nice-to-have, fun little thing that might be useful sometimes. It is _not_ ever to be considered the default work flow. This is _very_ important.
2. Type coercion will have to be done somewhere.  Command line text is, by definition, strings. That can not, ever change. 

I'm not sure I see this is a bug. The command line will always be string input; we can't change that.

To make this ticket more actionable, what do you want to change? You have correctly noted that type coercion is the answer, I'm not sure I understand the problem.

**Comment by keckler** [comment]
I am not advocating for more reliance on command line inputs, by any means. But we do support them, and it is above my paygrade to get rid of that. 

I don't think this is a bug either. I just think that someone adding a new setting will not anticipate that their comparison schema must first anticipate that a valid value could be passed in as an `str` and coerce the user input. And then if they don't have a proper schema that first does the coercion, this will probably not be caught by any existing unit test.

I just think this is something that we could probably handle better at a deeper level, if we were to rethink the settings class a little bit. Or something that we could add a unit test to catch. Perhaps a short test that loops over all the settings definitions to get their defaults, and then passes a string version of the default to the setting constructor to test that it is accepted.

But, perhaps not. Feel free to close this if you think its not worth spending any time.

**Comment by john-science** [comment]
I have seen this situation arise in Fortran and Python, Windows and Linux, etcetera.  The commandline is a string by definition.  It is just the universal situation of handling command line arguments.

Is it sufficient to have the developer type something like: `voluptuous.Range(voluptuous.Coerce(type(self.default), min=1)`?

Or (a) does that not solve the problem or (b) are you asking for us to make it easier?

**Comment by keckler** [comment]
> Is it sufficient to have the developer type something like: `voluptuous.Range(voluptuous.Coerce(type(self.default), min=1)`?

Yes, if the developer typed out that whole thing, then it would be sufficient.

My problem is that the developer probably won't know that they need to include the `Coerce(type(self.default))` portion, because we have no testing that acknowledges the possibility of command line (string) inputs. 

So the danger is very high that a developer will not include the coercion when they are adding validation to a new setting, thus breaking the code when people use command-line input.

I'm just wondering if there is some way to future-proof the validation of settings.

**Comment by keckler** [comment]
Okay, I'll close it.
