### ISSUE TITLE
Need to `open` db before `loadState`'ing from a file

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#679]
If one wants to load from an existing database file, they can do so by passing the file name to `loadState`:
https://github.com/terrapower/armi/blob/0f142cd6adfb86dd67618303eb1118ce40cdd4a3/armi/bookkeeping/db/database3.py#L398-L445

In that method, there is a call to `_getLoadDB`:
https://github.com/terrapower/armi/blob/0f142cd6adfb86dd67618303eb1118ce40cdd4a3/armi/bookkeeping/db/database3.py#L377-L396

For me, this `loadState` from a file doesn't work because the underlying `self.h5db` attribute is never set unless the database is first "opened" using `myDatabase.open()`. And because all of it takes place within a `with` clause, the error is hidden from the user and you ultimately end up with a `RuntimeError` that is not descriptive of the actual problem.

I _think_ that the `loadState` method should be modified to something like this:

```python
        for potentialDatabase in self._getLoadDB(fileName):
            with potentialDatabase as loadDB:

                ###### new block
                if loadDB._openCount == 0:
                    loadDB.open()
                ##### end new block

                if loadDB.hasTimeStep(cycle, timeNode, statePointName=timeStepName):
                    newR = loadDB.load(
                        cycle,
                        timeNode,
                        statePointName=timeStepName,
                        cs=self.cs,
                        bp=self.r.blueprints,
                        allowMissing=True,
                    )
                    break
        else:
            # reactor was never set so fail
            if fileName:
                raise RuntimeError(
                    "Cannot load state from specified file {} @ {}".format(
                        fileName, getH5GroupName(cycle, timeNode, timeStepName)
                    )
                )
            raise RuntimeError(
                "Cannot load state from <unspecified file> @ {}".format(
                    getH5GroupName(cycle, timeNode, timeStepName)
                )
            )

        if updateGlobalAssemNum:
            updateGlobalAssemblyNum(newR)

        self.o.reattach(newR, self.cs)

**Comment by john-science** [comment]
There was a bug ticket about something real similar a few months ago. Let me see if I can find it, and see what the overlap is.

**Comment by john-science** [comment]
This is 100% definitely a question that can only arise because we do not have a unit tests for `loadState()`. If we had one, we would see for certain whether or not this is occurring, and if it was, why it might be on purpose.

I can't find the previous discussion on the matter, which is a bit annoying.  

But I'll take a whack at fixing the bug, or at least adding a couple tests that show how the method can be used.

**Comment by john-science** [comment]
Okay, I can reproduce this bug with the following unit test that fails:

```python
class TestDatabase3(unittest.TestCase):
    def test_loadState(self):
        # fill a DB with data and close it
        self.makeHistory()
        self.db.close()

        # call loadState() on that DB, from a new operator
        dbi = database3.DatabaseInterface(self.r, self.o.cs)
        dbi.loadState(0, 1, fileName=self.db.fileName)
```

where this one passes:

```python
    def test_loadState(self):
        # fill a DB with data and close it
        self.makeHistory()
        self.db.close()

        # call loadState() on that DB, from a new operator
        dbi = database3.DatabaseInterface(self.r, self.o.cs)
        dbi._getLoadDB(self.db.fileName)    # NOTE: THIS LINE WAS NEEDED
        dbi.loadState(0, 1, fileName=self.db.fileName)
```

So, yeah, I think that's a pretty solid proof of the problem.  (My guess is the usual workflow for using `loadState()` happens to include a call to `_getLoadDB()`, so this isn't a bug for most people. Still, easy to fix.)

**Comment by keckler** [comment]
Hmm, I actually can't seem to recreate this bug anymore. I'm not sure if I was wrong before or not, because I lost the workflow that I was using at the time that I wrote this.

Gonna close this for now.
