### ISSUE TITLE
NHFLUX reader is broken for DIF3D-VARIANT

### ISSUE THREAD

**Issue by Nebbychadnezzar** [terrapower/armi#680]
The `nhflux` module is advertised to be able to read/write the DIF3D-VARIANT NHFLUX output file. However, both testing (using the `variant` flag) and inspection of the file specification demonstrate this this is not true. I do not know the full history of VARIANT's NHFLUX file format, so the cause of this issue is not clear to me. However, what is definitely true is that DIF3D-Nodal and DIF3D-VARIANT currently have different NHFLUX file formats, and the `nhflux` module can only process Nodal.

There are several issues that are causing this to occur. In no particular order:

1. The 2D block for VARIANT contains additional datasets for what it calls "symmetric" and "sector" boundaries. Nodal does not have these boundaries.
2. VARIANT stores both even and odd flux moments to the 3D block. Nodal has no concept of even and odd flux moments. The number of flux moments that Nodal thinks are present is controlled by the "nMom" parameter. The number of even and odd flux moments that VARIANT thinks are present is controlled by the "nMom" and "nMoms" parameters; both parameters need to be processed.
3. Somewhat related, when running VARIANT and using the VARPOW postprocessor (which stores power moments instead of flux moments), the NHFLUX file produced by VARPOW does not contain any currents (since the idea of a power current doesn't make any sense). The lack of currents is noted in the file using the "iwnhfl" parameter, but the `nhflux` is not prepared for addressing this parameter; it assumes that "iwnhfl"=0 (both fluxes and currents are present), but in the case of using VARPOW, "iwnhfl"=1 (only fluxes are present). In this case, the 4D and 5D blocks need to be ignored.

The best way to address this issue is not clear to me. I have developed short-term fixes that address the problem, but it means that some VARIANT data is ignored by the module. This is fine for my purposes, and probably fine for other people as well. The module currently ignores some Nodal data too, so clearly reading and not storing the entire NHFLUX file was previously acceptable...so, that makes me believe that my short-term fixes may be acceptable too.

**Comment by ntouran** [comment]
There's some long and relevant discussion and conversations with Mike Smith of ANL on this topic somewhere. I'll see if I can find it.

**Comment by Nebbychadnezzar** [comment]
That is what I thought as well, especially another unnamed plugin also appeared to make the same assumption and used the `nhflux` module to read and process VARIANT output. However, at some point, something in the VARIANT NHFLUX specification changed. Based on what I can see so far, it seems like something changed between v10 and v11? For example, there is a variable in the module called `FILE_SPEC_1D_KEYS_VARIANT10`...it has the right names, but then when `_rwBasicFileData1D()` runs, it doesn't realize that there are additional dummy entries that need to be processed too. Perhaps that is something that has changed between v10 and v11? At any rate, my pull request has renamed this variable to `FILE_SPEC_1D_KEYS_VARIANT11`.
