### ISSUE TITLE
YAML Setting in test uses dead setting

### ISSUE THREAD

**Issue by Nebbychadnezzar** [terrapower/armi#703]
The `outputCOBRAPinPeakingFactors` setting is no longer used by the framework (technically it is a setting defined in an ARMI plugin, but that plugin no longer uses it), but it is still being set in the `refTestCartesian.yaml` file in armi\tests. It should be removed.

https://github.com/terrapower/armi/blob/ff93ecb2753e6ccc279b8fc19a23a107181645ce/armi/tests/refTestCartesian.yaml#L27

**Comment by john-science** [comment]
I can fix that.

But you should feel empowered to open a simple PR when you identify a need for one.

**Comment by john-science** [comment]
Since this is just a one-line cleanup, I have added it to this PR:  https://github.com/terrapower/armi/pull/704
