### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#711]
I want to do some thorough testing, in particular about:

* the exact versions of the third-party libraries we are using
* our install process (as `distutils` was removed in Python 3.10)

I am hopeful this won't be a big deal. But the Python team broken backwards compatibility AGAIN with this release (as a smaller version of the Python 2 vs 3 breakage). So, that is intensely annoying.

**Comment by ntouran** [comment]
Just for the backlinking, PRs #708, #709, and #710 got me up and running on Python 3.10 on Ubuntu 22.04 at least as far as the docs (including gallery and tutorials), unit tests, and grid editor go.

**Comment by john-science** [comment]
GitHub closed this in error.  Reopening.
