### ISSUE TITLE
Linked components cannot have a period in their name

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#720]
I recently stumbled upon the fact that components which have links to other components cannot have a period in the component name. If it does, an error is thrown. 

In my case, I have the pellet-clad gap outer diameter defined as being linked to the cladding inner diameter (clad is named `clad_4.2`):
```
KeyError: 'Bad component link `od` defined as `clad_4.2.id`'
```

I guess its not totally necessary that we allow this, but if we don't allow it, we could probably do a couple things:
1. Make a note of it in the user docs, as well as other naming constraints: https://terrapower.github.io/armi/user/inputs/blueprints.html#component-links
2. Make the error message more informative

**Comment by john-science** [comment]
Seems like a class problem I've seen 100 places before. Two thoughts:

1. It might be solvable, if we first check if the string has multiple periods in it.
2. At the very least, perhaps we could stop people from putting periods in their names in the first place.

My first thought is if we can just reproduce this error via unit test, we can find some solution for it.

**Comment by john-science** [comment]
Okay, I fixed `Component.resolveLinkedDims()` so it could handle names with periods in them.  And... a few other things broke downstream. 

So, the options appear to be: make this a huge, wide-sweeping change that touches large portions of the code base, or just tell people they can't put periods in the name.

Sorry man, but I think we're just going to add another restriction to the naming convention.  I would have preferred fixing it.

**Comment by keckler** [comment]
No problem, I understand that tradeoff.

I'd ask only to make sure such restrictions are documented.
