### ISSUE TITLE
Incorrect call to `db.load()`

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#726]
https://github.com/terrapower/armi/blob/97ba5ee3ab80517bc230a938616bc3ae8b092fc8/armi/bookkeeping/mainInterface.py#L134-L144
In the call in there to `db.load()`, it includes as an argument `self.r.geom`. I'm not even sure if `self.r.geom` exists as a thing, but regardless, if you look in the signature for `db.load()`, it does *not* include any `geom` parameter:
https://github.com/terrapower/armi/blob/97ba5ee3ab80517bc230a938616bc3ae8b092fc8/armi/bookkeeping/db/database3.py#L1079-L1120

**Comment by john-science** [comment]
I remember when `r.geom` was removed. It is certainly unused at best.

That line in `db.load()` hasn't changed in three years.

I'm scratching my head how you could possibly be the first person to see this bug. Unless (a) it's somehow not a bug, or (b) that code is unreachable.  But both (a) and (b) seem unlikely.

**Comment by john-science** [comment]
I can confirm that the offending line 142 in `mainInterface.py` is not being hit by any unit tests currently:

https://coveralls.io/builds/50296682/source?filename=armi%2Fbookkeeping%2FmainInterface.py#L142

So, that's why this hasn't been seen by a unit test.

**Comment by keckler** [comment]
It's because the messed up call is only made if you have `loadFromDBEveryNode: True` in your case settings. I'm not super sure what that setting actually does, but I've never seen anybody use it.
