### ISSUE TITLE
`returnNull` parameter of `getComponent()` never used in method

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#732]
Self explanatory.

I don't think the `returnNull` parameter is being used in any calls, but needs to be double checked.

https://github.com/terrapower/armi/blob/4894a56c4c5498272d47b6bc307765eb207f4801/armi/reactor/composites.py#L2451-L2493

**Comment by john-science** [comment]
Agreed.

I have looked around our ecosystem a bit and can't find anyone that is subclassing this and using `returnNull` either.

So, it seems like it should be quite safe to remove.
