### ISSUE TITLE
We need "what's a good PR" in the docs

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#741]
It should be short, sweet, and probably bullet points.

**Comment by john-science** [comment]
Maybe it would be helpful to also adjust the check boxes that people see when they open a PR.

**Comment by albeanth** [comment]
FWIW, I've been just deleting the bottom two check boxes when I make PRs. I think the first is outdated and the second seems to be quite rare. 

![image](https://user-images.githubusercontent.com/18561046/176786802-4197cc0f-5f9c-47ae-8e49-88535482bd16.png)

**Comment by keckler** [comment]
Eh, disagree on:
> I think the first is outdated

I check that box once in a while.

**Comment by john-science** [comment]
@albeanth  The first check box is not outdated.

For all non-trivial changes to ARMI, you should be adding something to:

https://github.com/terrapower/armi/blob/main/doc/release/0.2.rst

**Comment by albeanth** [comment]
> @albeanth The first check box is not outdated.
> 
> For all non-trivial changes to ARMI, you should be adding something to:
> 
> https://github.com/terrapower/armi/blob/main/doc/release/0.2.rst

That is interesting! I didn't realize that. There have probably been a few additions that could/should be added. 

Is there any official guidance on what PRs are deemed "sufficient" to get included to this?

**Comment by john-science** [comment]
@albeanth There is no "official" guidance.  Probably, more is better than less, because right before a release I can go through the release notes and clean them up, and remove anything not that important.

BUT, a good rule of thumb is: anything that changes the API should be documented. Particularly, anything that breaks backwards compatibility should be documented.

Other than that, major features should be documented. And bug fixes.

**Comment by albeanth** [comment]
Ok, so probably _most_ PRs should be updated with the exception of those that just touch docstrings/unit tests/etc. 

But if new public methods are added or the functionality of an existing method is changed, then an addition to the release notes is warranted. 

This is great to know. Looks like I'll be digging through my closed PRs and making some updates to the release notes!
