### ISSUE TITLE
`Holed` components need `getCircleInnerDiameter()` methods

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#755]
In order to be viable with the new axial expansion changer, the various `Holed` components need to have implementations of the `getCircleInnerDiameter()` method. ~Right now all of them inherit from the [base component method](https://terrapower.github.io/armi/_modules/armi/reactor/components/component.html#Component.getCircleInnerDiameter), which just returns a `NotImplementedError`.~ In this case, the axial expansion changer can't determine that the component is linked with anything above/below, and it is possible that the code will just bomb. But in reality, it is definitely possible that a holed component could be linked with an equivalent holed component in blocks above/below it.

The components that need this are:

- [ ] [`HoledSquare`](https://terrapower.github.io/armi/_modules/armi/reactor/components/complexShapes.html#HoledSquare)
- [ ] [`HoledRectangle`](https://terrapower.github.io/armi/_modules/armi/reactor/components/complexShapes.html#HoledRectangle)
- [ ] [`HoledHexagon`](https://terrapower.github.io/armi/_modules/armi/reactor/components/complexShapes.html#HoledHexagon)

Now... What should be returned by `getCircleInnerDiameter()` is up for debate...

I think if there is just 1 hole in the component, then it is clear what the "circle inner diameter" means. But if the component has multiple holes or if the multiplicity of the holes is not 1, this question starts to become less clear...

Any thoughts? @john-science @jakehader @onufer @albeanth 

-----

Edit: Actually all three shapes will fall back to their parent implementations of `getCircleInnerDiameter()`. 

In the case of the `HoledHexagon`, `getCircleInnerDiameter()` always returns 0.0 because `ip` of the hexagon defaults to 0.0 and so the `Hexagon.getCircleInnerDiameter()` can actually operate.

For the `HoledSquare` and `HoledHexagon`, the relevant component parameters don't exist and so `HoledSquare.getCircleInnerDiameter()` and `HoledHexagon.getCircleInnerDiameter()` both bomb.

**Comment by john-science** [comment]
I like the idea of consistency.  

I think "inner diameter" is a concept that seems suddenly useless for anything with multiple holes. So, I would agree with Tony on that one.

If there is only one hole, then I could see us making the argument that all of these need non-zero values returned.  That is, maybe tedious, but also seems reasonable, right?

**Comment by keckler** [comment]
I think it would be reasonable to return a real value when there is only 1 hole, definitely.

But I also wonder if it is a bit wonky/inconsistent to return real values sometimes, but then to default to 0.0 when there are multiple holes.

I don't particularly care which way we go with this, but just want to make sure we have the best solution.

**Comment by albeanth** [comment]
> But I also wonder if it is a bit wonky/inconsistent to return real values sometimes, but then to default to 0.0 when there are multiple holes.
I don't particularly care which way we go with this, but just want to make sure we have the best solution.

I think if it's clearly documented in the docstring of the method what it's doing and when it returns zero and non-zero we should be ok. You could add a `runLog.debug` statement for either or, but it may be overkill.

**Comment by keckler** [comment]
This is fixed iwht #757
