### ISSUE TITLE
test_comparedb3.py has very few unit tests

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#788]
It has a few small unit tests, and two integration tests that don't touch all possible cases. Unit tests for all the other functions are needed. 

This was discovered when the need for PR #786 was discovered.

**Comment by john-science** [comment]
We have raised the code coverage from 60% to 83%:

https://coveralls.io/builds/51061594/source?filename=armi%2Fbookkeeping%2Fdb%2FcompareDB3.py

I think most of what is left are exceptions and errors.  Which we have not done a lot of testing for yet in ARMI.  Sadly.

**Comment by john-science** [comment]
This file is at 85% now, and I think the tests look pretty good. (Obviously, I will want them above 90% one day soon.)

But I am just going to close this ticket.
