### ISSUE TITLE
Many `material` methods that return physical quantities are lacking units

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#801]
Taking a look at the docstrings for various `material` methods, the units of the returned physical quantity are not defined in the docstring and are thus not easy to infer (especially because many of the units are non-SI 😞).

On first glance, the following should have units that are missing:

- [ ] heatCapacity
- [ ] getTempChangeForDensityChange
- [ ] thermalConductivity
- [ ] getCorrosionRate
- [ ] density3
- [ ] density
- [ ] liquidPorosity
- [ ] gasPorosity
- [ ] getTemperatureAtDensity

Possibly others as well. These should have their docstrings updated.

**Comment by john-science** [comment]
Well, we can infer the units of `density3`:

https://github.com/terrapower/armi/blob/bc556fc5ce3f0445a4b1e841f00b8bdc3888f5a3/armi/materials/material.py#L413-L421

**Comment by john-science** [comment]
@ntouran  Can you fill in the blanks above, for what these units should be?

**Comment by john-science** [comment]
PR for this is open.
