### ISSUE TITLE
Either move valid settings check to specifyInputs, or address and close Issue #772

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#825]
In `case.py`'s `copyInterfaceInputs`, there is a check for a valid setting:

https://github.com/terrapower/armi/blob/9fcc89393d585d99cd8c99fbfed841844284bfe9/armi/cases/case.py#L803-L810

This check being in `copyInterfaceInputs` makes it untestable. It should either get removed (which addresses Issue #772) or be moved to `specifyInputs`.

**Comment by john-science** [comment]
What's the status of this, after your recent `copyInterfaceInputs()` PR?

**Comment by opotowsky** [comment]
It's kind of because of the PR (and the testing coverage). I just wanted to make sure that there's an issue to remove it no matter what, in case the other issue was too difficult to fix.

**Comment by opotowsky** [comment]
It's on my mind, just lower priority for the moment

**Comment by john-science** [comment]
@opotowsky This ticket is still assigned to you.  That's cool with me, but if you aren't planning on working on it, please un-assign it.

(You are not being singled out, I am going through all the ARMI tickets.)

**Comment by opotowsky** [comment]
Sure I'll unassign, since I can't prioritize it or the other ticket right now!
