### ISSUE TITLE
Reformat `runLog.extra` in `manageCoreMesh` to use "tabulate"

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#833]
Let's format this better. The output is pretty ugly. You could use tabulate.

_Originally posted by @jakehader in https://github.com/terrapower/armi/pull/823#discussion_r943819693_

**Comment by jakehader** [comment]
Is this still valid @albeanth?

**Comment by albeanth** [comment]
This got cleaned up on an internal subclass. We could probably move it to the public side.

**Comment by john-science** [comment]
Any movement here?

**Comment by albeanth** [comment]
Is there a desire to move this part of the internal subclass public? If not, we should close the issue.

We can chat offline about this too. I think it's fine to do so, it just hasn't taken priority over other things.

**Comment by john-science** [comment]
This ticket has had no movement in two years, so I believe the interest Tony asks for above is minimal.  We can re-open it if someone wants to do the lifting.
