### ISSUE TITLE
Discrepancy with source and density in armi/materials/ht9.py::HT9

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#840]
`self.p.refDens` for HT9 is inconsistent with the definition provided in the [open source Metal Fuels Handbook](https://www.osti.gov/biblio/1506477-metallic-fuels-handbook) (pg 194/210) source. 
https://github.com/terrapower/armi/blob/dbf33e0064fd1c84099b0a9c97a7fa4688358196/armi/materials/ht9.py#L60

The handbook provides a temperature dependent linear equation for density with the nominal density being 7.778 g/cc rather than 8.86 g/cc. 

Providing this discussion link for posterity. https://github.com/terrapower/armi/discussions/767

**Comment by john-science** [comment]
I'll double-check the references, but at least it's not a hard fix.

Hopefully, this doesn't impact any downstream analysis too hard.

**Comment by john-science** [comment]
Okay, I don't see any way to argue with you there; that is clearly what the reference says.

Let me open a PR for this right now.

Thanks!
