### ISSUE TITLE
Refactor the uniform mesh converter to operate on assemblies

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#851]
The goal here is that uniform mesher should be able to support mapping of parameters from one assembly to another without requiring a _complete_ reactor core to be initialized. This will improve the usability of this code in `uniformMesh.py` for other user-plugins that need to operate on only one assembly for a mesh conversion.

This has been started in https://github.com/terrapower/armi/tree/uniformMeshRefactor.

**Comment by john-science** [comment]
As long as the "entire reactor" workflow still works, AND is still the default, I'm happy.

My concern is that 2 of the 3 reactors (that I know of) that use ARMI don't have any Assemblies. So we don't want to break those people.

**Comment by jakehader** [comment]
This won't break anything. The uniform mesh converter works on assemblies already. See #854
