### ISSUE TITLE
Update NHFLUX reader/writer to process all VARIANT data

### ISSUE THREAD

**Issue by Nebbychadnezzar** [terrapower/armi#862]
In PR #681, it was identified that the NHFLUX reader/writer was not able to read DIF3D-VARIANT data at all. The DIF3D-VARIANT NHFLUX format is different than the DIF3D-Nodal format (at least as of v11.0 of DIF3D), and the existing reader (at the time of #681) was not capable of reading the VARIANT format.

#681 partially fixed this issue to allow for most of the data to be processed by the reader/writer. That update was sufficient to be able to make use of the ARC tool EvaluateFlux. However, some of the VARIANT data is thrown away by the reader/writer, which is not ideal. This shortcoming should be addressed.

The data that still needs to be stored by the reader/writer can be found throughout the `nhflux.py` module by searching for the use of the variable `dummy`. Here is a list of what I believe is still missing.

- Odd-parity flux moments. These are iterated over on the 3D record. The even-parity moments are stored on the `fluxMoments` attribute, so perhaps the odd-parity moments could be stored on a new attribute called `fluxMomentsEven`. This parameter would be empty when processing DIF3D-Nodal files.
- Outgoing partial radial currents beyond NSCOEFF == 1. These are iterated over on the 4D record. These would not exist for DIF3D-Nodal.
- Ingoing partial radial currents beyond NSCOEFF == 1. These are iterated over on the 4D record. These would not exist for DIF3D-Nodal.
- Z-directed partial currents beyond NSCOEFF == 1. These are iterated over on the 5D record. These would not exist for DIF3D-Nodal.

For the last three bullets, one way to potentially address the issue is by expanding the dimensionality of the arrays that store the NSCOEFF == 1 data by 1 (i.e., create a new axis for the NSCOEFF dimension). This allows one to keep the same variable names...but, it does break the use of these arrays for existing users (who expect the current number of dimensions to be present), which may not be desirable.

**Comment by Nebbychadnezzar** [comment]
@jakehader, I created an issue for this topic. This is straightforward to fix, I believe...I think it just comes down to what is the best way to fix it.

**Comment by jakehader** [comment]
> @jakehader, I created an issue for this topic. This is straightforward to fix, I believe...I think it just comes down to what is the best/cleanest way to fix it.

Thanks @Nebbychadnezzar!

**Comment by john-science** [comment]
Ah, that's a shame.

Are you... volunteering to fix it?  :)
