### ISSUE TITLE
 Remove the ability for users to load separate blueprints in snapshots run

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#871]
When doing a snapshots run, ARMI allows users to use both new settings and blueprints. 
https://github.com/terrapower/armi/blob/0716e80f3d03ce188a1859b73fe02e40a09747ea/armi/bookkeeping/db/database3.py#L1103-L1106
 
I can understand the utility in using new settings, but the option for different blueprints is a little strange to me. I would think that if one unintentionally loaded a blueprints file that didn't match the blueprints assemblies on the reactor database there would be unexpected issues. 
 
Looking at the docstring in `loadBlueprints` I can totally appreciate the danger of unexpected things happening if the database was written with a different ARMI version. But I think(?) it might be the lesser of two downsides compared to unintentionally loading a different blueprints file than what's on the database.
https://github.com/terrapower/armi/blob/0716e80f3d03ce188a1859b73fe02e40a09747ea/armi/bookkeeping/db/database3.py#L815-L823

To avoid having users unintentionally load blueprints that differ from what is on their reactor database, I propose that we require the reactor be loaded with the blueprints that live on the database. This would effectively remove the optional param, `bp`, from database3.py::Database3::load.

**Comment by john-science** [comment]
Hmmm... Well, you might want to load a database for reasons other than snapshots.

That's my only real concern here.  

Perhaps the snapshots argument still applies, but I'll have to consider other use cases for `Database3.load()`.

**Comment by albeanth** [comment]
Definitely. We'll have to be extra careful with any changes here to be sure we aren't breaking peoples projects. 

I'll look into callers of the method to see if there are any use cases on the framework and downstream projects I have and see if I can find any use cases.

**Comment by albeanth** [comment]
A feature branch to address this issue. Everything looks good on the framework front. Still testing downstream projects. 

https://github.com/terrapower/armi/compare/main...albeanth:armi:dbLoadUpdate

**Comment by onufer** [comment]
@albeanth, changing  method signatures should be avoided whenever possible. The solution here should be to have snapshot not send in the optional argument rather than deleting the optional argument from the signature (unless we are concerned about a potential bug). Other teams outside TerraPower use ARMI and you cannot see their code, so if it can be avoided, I would recommend keeping the method signature the same.
