### ISSUE TITLE
We need old-style databases to test Migration scripts

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#889]
We have two completely untested database migration scripts in ARMI:

* `crossSectionBlueprintsToSettings.py`
* `m0_1_0_newDbFormat.py`

Can we find (or manufacture) databases to test these scripts against? 

If anyone has such databases, maybe pass them to me and I will try to tweak them for the unit tests. Final databases would need to be:

* _very_ small, so we don't bloat our repo, just for a unit test
* free of proprietary data

**Comment by john-science** [comment]
Can we find or manufacture some old-style databases to test these scripts?  @jakehader @ntouran

**Comment by jakehader** [comment]
Hm I'm wondering if we can just say that for backwards compatibility users should rerun cases with the latest ARMI framework? It's difficult to maintain this functionality. Either way, yes I think an old database can be generated

**Comment by john-science** [comment]
@jakehader  You're not wrong.  I'm just feeling antsy. Because I'm sure these scripts are too important to delete. Which means they should be tested.

But for once, the barrier to testing isn't just "when does John have time to write a test". The barrier here is input data.

Cheers!

**Comment by john-science** [comment]
Okay, I'm coming back to this after the obvious recent break.

@ntouran @jakehader  Do you guys think you could help me find or generate old databases to match these migration scripts?

Cheers!
