### ISSUE TITLE
Unnecessary embedded class in interfaces.py

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#896]
I found myself in `interfaces.py::Interface` yesterday and saw that `class Distribute` is embedded within the `Interface` class. Embedding the class seemed unnecessary and hard(er) to test/maintain.

https://github.com/terrapower/armi/blob/908c92d86546d5c6e6e7df946cf1fdfa9515b964/armi/interfaces.py#L120-L125

A quick grep shows that the class does get used some, (e.g., [like so](https://github.com/terrapower/armi/blob/908c92d86546d5c6e6e7df946cf1fdfa9515b964/armi/bookkeeping/db/database3.py#L304-L305)) so we'll have to be careful with changes. But this feels like it could be cleaned up a bit. 

Just a thought.

**Comment by albeanth** [comment]
The method is fine. It's the embedding of `class Distribute` that I think is a little strange. So that return statement would become ` return Distribute.DUPLICATE`.

I may have missed something, but it seems strange to me why `class Distribute` is embedded within `Interface`. I think it would be clearer to move it outside of `Interface` and use composition to interact with it.

Or, and now I'm just spitballing, remove the `Distribute` class altogether with and make `DUPLICATE`, `NEW`, and `SKIP` class variables on `Interface`. 

This is low priority... Just saw something that was strange to me.

**Comment by keckler** [comment]
Ah. You have a typo in your original message (`distributable` instead of `distribute`). 
![image](https://user-images.githubusercontent.com/21959600/191995544-6700528b-9902-4615-a65a-155dffa9119d.png)

So I was confused there. Nevermind my comment!

**Comment by albeanth** [comment]
Ah! Whoops! Fixed.

**Comment by john-science** [comment]
Looking at it again, someone was just trying to make an Enum that was specific to an `Interface`, so they put it inside the `Interface`.  It's not really a full class, just the standard python hack for making an enum.

I hate this less than I did on a first pass, when I just saw an embedded class.
