### ISSUE TITLE
Add third style option to SettingsWriter

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#897]
Right now, `SettingsWriter` has two style options: `short` and `full`. 

https://github.com/terrapower/armi/blob/908c92d86546d5c6e6e7df946cf1fdfa9515b964/armi/settings/settingsIO.py#L275-L283

This former strips all settings that have default values, and the latter adds every possible setting to the settings file. It would be nice to have a file written that doesn't strip the pre-defined settings even if they are in fact the default value. Default settings are not always backwards compatible, and it can add clarity to users to understand what a particular case is doing to have some settings listed.

**Comment by john-science** [comment]
Sorry, can you clarify what you want that's different from `full`?
