### ISSUE TITLE
Issues with newer versions of python and wxpython :: attrdict module

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#907]
We had some users doing a fresh install get an error with `wxpython` through the grids requirements
```
Collecting wxpython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/64/jv4mfhbd2_x1_cjtgz_lv0z00000gn/T/pip-install-m9dtaqfn/wxpython_be9e764dd24e4871932935e5b5d1a760/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/64/jv4mfhbd2_x1_cjtgz_lv0z00000gn/T/pip-install-m9dtaqfn/wxpython_be9e764dd24e4871932935e5b5d1a760/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Some additional digging (https://github.com/wxWidgets/Phoenix/issues/2225) indicates this might be a problem with `wxpython=4.2`

Possible fix: change `wxpython` to be either less than or greater than 4.2

**Comment by john-science** [comment]
I can confirm that no one in TerraPower uses a version of `wxPython` greater than 4.1.1.

At least it's an easy fix.

**Comment by ntouran** [comment]
Thanks for the report Drew! Maybe try `pip install attrdict3` and re-run? It might work. Seems related to this: https://github.com/wxWidgets/Phoenix/issues/2225

**Comment by john-science** [comment]
@drewj-usnctech I see some traffic that people were working on this.  Has it been resolved for you?

It appears to be a very version-dependent problem, between Python and the `wxPython` library.

**Comment by drewj-usnctech** [comment]
@john-science sorry, I've been out on PTO for the last two weeks.

That traffic is not related to us and it hasn't been resolved. We've still been telling people to manually force a lower version of wxpython when installing armi grids

**Comment by john-science** [comment]
@drewj-usnctech Okay, I am going to change our `setup.py` and `requirements` files to enforce that version limit on `wxpython`. Assuming they use `pip`, it should automate that process.

We are hopefully replacing this GUI soon with a Jupyter-based one.  So, hopefully this is very temporary.

**Comment by drewj-usnctech** [comment]
thanks @john-science! Looking forward to it
