### ISSUE TITLE
Typo in Docs for Coupling

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#916]
Just noticed a typo in the docs for physics coupling. 

https://github.com/terrapower/armi/blob/main/doc/user/assorted_guide.rst

Should read:
"~Loose~ Tight coupled physics...."

https://github.com/terrapower/armi/blob/65574120048c7d6ee0d523d667e8d2f49c45015f/armi/settings/fwSettings/globalSettings.py#L581-L588

**Comment by keckler** [comment]
Probably one could argue forever if it is "loose" or "tight", but yes, I agree that there is inconsistency between the setting description and that linked page.
