### ISSUE TITLE
thermal expansion is slow on initialization

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#920]
`o=armi.init()` is now slower that `o=loadOperator(dbPath, cycle, node)`

This is because ARMI has to thermally expand all the assemblies in the core but load states come pre-expanded.

I suggest expanding the blueprints assemblies prior to copying them all so we don't need to do expansion on each assembly afterword which is slow.

**Comment by john-science** [comment]
I'm generally okay with this.

What we don't want is a bunch of logic specific to one reactor inside blueprint.py.  That's some pretty generic code used by the MCFR and the USNC pebble-bed reactor.  Let's keep that _file_ clear of custom logic need only for performance boost.

**Comment by onufer** [comment]
closed with #1047
