### ISSUE TITLE
Clean assorted algos out of FuelHandler class

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#949]
Over in [this PR](https://github.com/terrapower/armi/pull/843#issuecomment-1289361623), I was discussing with @keckler, and was able to confirm that (outside of ARMI itself), none of the downstream repos (that I have access to) use the methods:

* `buildRingSchedule()`
* `buildConvergentRingSchedule()`
* `getOptimalAssemblyOrientation()`
* `buReducingAssemblyRotation()`

And only one uses: `buildEqRingSchedule()`.

I also note that the above algorithms don't really make use of the FuelHandler object, except that they use the `self.r` object to get at the `Reactor` object.

They need to be move out of the `FuelHandler` class, and out of `FuelHandler.py` into their own file, so they can be more portably used by whoever wants them.

Or, we could move all of these algorithms out of ARMI.  And if they are unused, why not!  Is no one using these four algorithms? Are the important to keep?

**Comment by keckler** [comment]
Maybe we should just confirm with @drewj-usnctech ?

**Comment by john-science** [comment]
@drewj-usnctech  In this ticket I propose moving some methods out of the `FuelHandler` class. 

On my side of the ARMI world, this is a minor change. These methods are largely unused, and I think it would be cleaner and simpler for everyone to not confuse people thinking every `FuelHandler` needs to use and implement all of these.

Does that seem right to you, or are you using them in situ?   I just want to make sure I know how this change would affect you.

**Comment by john-science** [comment]
@drewj-usnctech Would the proposed changes here be annoying to you?  Just curious.

**Comment by john-science** [comment]
> I'm _guessing_ that that project doesn't even use shuffling, but I don't know that for sure.

That's a good guess, Chris.  Unless Drew says otherwise, I'll probably just move forward with this idea.

**Comment by drewj-usnctech** [comment]
Thanks for reaching out. But this is good with us 👍

**Comment by john-science** [comment]
Okay, the decision was made to move these to methods to functions in a new file.  

What should the new file be named?

* `assemblyFuelManagementTools.py`
* `assemblyFuelManagementUtils.py`
* `assemFuelMgmtUtils.py`
* `hexAssemblyFuelMgmtTools.py`
* `hexAssemblyFuelMgmtUtils.py`
