### ISSUE TITLE
Parameter description references internal document

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#966]
The following parameter definition refers to some internal document, which is not useful for non-TP users and not kosher regardless. We should have a description in the docs somewhere that describes this pin-ordering scheme.

https://github.com/terrapower/armi/blob/36fe1bced3b817d6d76e66cf99dd355219993e63/armi/physics/neutronics/parameters.py#L160-L167

**Comment by john-science** [comment]
I opened a PR for this [here](https://github.com/terrapower/armi/pull/968).  (I also found a second instance of the same problem.)

You could have opened the PR instead of the ticket, you know.

**Comment by keckler** [comment]
Well, my thought was that we might have wanted to put the referenced description into the public docs, which would have taken more time. 

I still think that'd be useful, honestly.

**Comment by john-science** [comment]
Do you know where to find that?  Honestly, I don't.

**Comment by keckler** [comment]
I don't lol. Lost to time!
