### ISSUE TITLE
TH Param Spring Cleaning: remove "TH" Prefix

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#971]
All of the TH parameters are prefixed with `TH`.

1. Is this necessary?
2. Can it be removed?

It would be nice to remove the character clutter if possible.

_Parent Issue_ #970

**Comment by john-science** [comment]
It would require a LOT of Parameter Renames to hang around forever.

I'm not sure the juice is worth the squeeze on this one, for me.

And, honestly, that TH clutter is kind of helpful.  It makes what they are clear.

**Comment by john-science** [comment]
Can this PR be closed after the recent [bulk move of TH parameters out of ARMI](https://github.com/terrapower/armi/pull/1001)?

**Comment by opotowsky** [comment]
Soft preference: 
I actually wish all parameters had a prefix of which physics module they belong to, and appreciate that all TH params are quickly visually identifiable by the prefix. 

But this isn't implemented across the board, so if you feel it's worth the lift I'll leave that decision to you. I do think this one could linger as a nice-to-have given the amount of work it would be.

**Comment by mgjarrett** [comment]
I like the `TH` prefix on the parameters. It helps identify where the values are calculated. We have a similar thing in other modules: Crucible prefixes most parameters with `CX`, and reactivity coefficients prefixes many parameters with `rx`.

**Comment by john-science** [comment]
> Soft preference: I actually wish all parameters had a prefix of which physics module they belong to,

Yeah, me too.  But making the switch would lead to hundreds of PR.  Not worth the time, IMO.

**Comment by sammiller11235** [comment]
I also like the `TH` prefix on the parameters

**Comment by andfranklin** [comment]
After further consideration, based on how the parameter system is designed it makes sense to include a prefix of the responsible domain in the parameter names. Moreover, the general consensus is that the `TH` prefix is useful and it would be a lot of work to remove it. Unless a strong counterargument is presented then it is likely that the prefix will remain.

**Comment by john-science** [comment]
These ticket has been open for 7 months.  Can we close them, or at least close them all but the umbrella ticket, and move this one variable name change into the umbrella?
