### ISSUE TITLE
TH Param Spring Cleaning: change "fuel" to "pin"

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#972]
The following parameters, defined in `physics/thermalHydraulics`, store values related to the pin temperatures:

- `THTfuelCL`
- `THTfuelOD`
- ~`TH0SigmaFuelCenterlineT`~
- ~`TH2SigmaFuelCenterlineT`~
- ~`TH3SigmaFuelCenterlineT`~
- `THhotChannelFuelODT`
- `THhotChannelFuelCenterlineT`
- `THlocalDToutFuel`

These names are misleading because values could be set on assemblies that are not fuel assemblies (e.g., shield or control assemblies). It would be preferred to replace "fuel" with "pin" in these parameter names to reflect their more general nature.

_Parent Issue_ #970

**Comment by john-science** [comment]
@dlangewisch @andfranklin @jakehader Opinions on naming?

**Comment by sammiller11235** [comment]
I like the change from `fuel` to `pin` for generality.

**Comment by john-science** [comment]
> I like the change from `fuel` to `pin` for generality.

If the TH parameters are only meant for pin-type fuel, and not... molten chloride or fuel pellet design, or whatever... I highly agree.

**Comment by andfranklin** [comment]
I agree with @sammiller11235. This issue was opened after a conversation with Tony Alberti, so I think he'd agree as well.

**Comment by andfranklin** [comment]
@john-science brings up a good point. I would like to make the counterargument that most of the temperatures are specific to some location on the pin (e.g. `CL` -> centerline, `OD` -> outer diameter, etc). The one temperature that does not (`THlocalDToutFuel`) is specifically for assembly-type reactors per the description: "Maximum delta-Ts for outlet temperatures of all assemblies".

Proposal
----------
- Rename "coolant" temperatures to "fluid" temperatures (e..g `THcoolantOutletT` -> `THfluidOutletT`).
- Rename "fuel" temperatures to "pin" temperatures
- Move "pin" temperature parameter definitions from ARMI to Nala's TH plugin

Rational
---------
- Renaming the "coolant" temps to be "fluid" temps generalizes them for usage with non-assembly-type reactors.
- Since ARMI is general purpose it doesn't make sense to keep parameter definitions specific to assembly-type reactors in the framework.
