### ISSUE TITLE
TH Param Spring Cleaning: inconsistent centerline temperature adjective

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#973]
The adjective for "centerline" in centerline temperature parameters do not have a consistent naming scheme. For example:

- `CL` in `THTfuelCL`, and
-  `Centerline` in `TH0SigmaFuelCenterlineT`

are not consistent.

The two obvious ways to resolve this are:

- change "CL" to "Centerline"
- change "`Centerline`" to "`CL`".

Additional options could also be considered. Another possibility is that both could be changed to some abbreviation of centerline (e.g. `cntrln`)?

Thoughts?

_Parent Issue_ #970

**Comment by john-science** [comment]
@dlangewisch @andfranklin @jakehader Opinions on naming?

**Comment by sammiller11235** [comment]
One vote for `CL`. I don't like `cntrln`

**Comment by andfranklin** [comment]
I think `CL` is acceptable. It's terse, unlikely to clash with anything else, and easy to remember. Count it as two votes for `CL`.

**Comment by john-science** [comment]
These ticket has been open for 7 months.  Can we close them, or at least close them all but the umbrella ticket, and move this one variable name change into the umbrella?
