### ISSUE TITLE
TH Param Spring Cleaning: inconsistent temperature grammar

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#974]
For instance, compare `THTfuelOD` and `TH0SigmaFuelCenterlineT`. The general patterns are `THT<adj 1><adj 2>...`, and `TH<adj 1><adj 2>...T`, respectively.

The second option (where the adjectives are listed before "`T`") seems to make the most sense. It's closest to how the parameter description is spoken.

_Parent Issue_ #970

**Comment by john-science** [comment]
@dlangewisch @andfranklin @jakehader Opinions on naming?

**Comment by sammiller11235** [comment]
I'm a fan of the `T` at the end of all other these for consistency and readability

**Comment by andfranklin** [comment]
I agree with @sammiller11235 

Although, I just thought of an interesting argument in favor of having `T` at the front. It might add some convenience to finding parameters in XTView because of how the parameters are alpha-numerically ordered.

I still think I would prefer to have `T` at the end.

**Comment by john-science** [comment]
These ticket has been open for 7 months.  Can we close them, or at least close them all but the umbrella ticket, and move this one variable name change into the umbrella?
