### ISSUE TITLE
TH Param Spring Cleaning: inconsistent camel case

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#976]
Take `THTfuelCL` and `THcornTemp`. To be consistent either:

1. `THTfuelCL` should be changed to `THTFuelCL`, or
2. `THcornTemp` should be changed to `THCornTemp`.

_Parent Issue_ #970

**Comment by john-science** [comment]
@dlangewisch @andfranklin @jakehader Opinions on naming?

A finer point, on this one.  The most important thing is the name is readable and helpful.

**Comment by john-science** [comment]
These ticket has been open for 7 months.  Can we close them, or at least close them all but the umbrella ticket, and move this one variable name change into the umbrella?
