### ISSUE TITLE
TH Param Spring Cleaning: rename THdeltaPBundle

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#977]
Assembly > Bundle.

_Parent Issue_ #970

**Comment by john-science** [comment]
@dlangewisch @andfranklin @jakehader Opinions on naming?

**Comment by john-science** [comment]
I am closing this PR as this variable was removed from ARMI during the recent [bulk move of TH parameters out of ARMI](https://github.com/terrapower/armi/pull/1001).
