### ISSUE TITLE
TH Param Spring Cleaning: dead parameters

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#978]
There are a few unused TH parameters that are no longer needed. Find all of the dead parameters and remove them from the code base. The following is a partial list of the dead parameters:

- `THdeltaPFric`
- `THdPfrict`
- `THassemPressDrop`
- `linPow`
- `powerGenerated`
- `CoreMdot`
- `THdeltaPAccel`
- `THdeltaPInlet`
- `THdeltaPOutlet`
- `THmaxLifeTimePower`
- `THinletCoolantVel`

_Parent Issue_ #970

**Comment by john-science** [comment]
My research into downstream repos:

* `THdeltaPFric` - I already removed these from ARMI.  **DONE**
* `THdPfrict` -  I already removed these from ARMI.  **DONE**
* `THassemPressDrop` - I already removed these from ARMI.  **DONE**
* `linPow` - Used in a few downstream repos/projects.  **KEEP**
* `powerGenerated` - Used in three downstream repos/projects.  **KEEP**
* `CoreMdot` -  Only found in ARMI, and unused.
* `THdeltaPAccel` - Only found in ARMI, and unused.
* `THdeltaPInlet` - Only found in ARMI, and unused.
* `THdeltaPOutlet` - Only found in ARMI, and unused.
* `THmaxLifeTimePower` - Only found in ARMI, and unused.
* `THinletCoolantVel` - Only found in ARMI, and unused.

So, there are 6 Parameters I will remove from ARMI:

1. `CoreMdot`
2. `THdeltaPAccel`
3. `THdeltaPInlet` 
4. `THdeltaPOutlet` 
5. `THmaxLifeTimePower` 
6. `THinletCoolantVel`
