### ISSUE TITLE
Remove MPI awareness requirements from Temporary Directory Changer and Output Cache

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#982]
#689 added some MPI awareness and barriers to a few commonly-used utility functions like the output cache and the directory changer. However, this has some unintended consequences when these utilities are being used by worker MPI nodes again and again in parallel. For example, if worker `X` has 10 tasks to do, all of which require tempdirs, and worker `Y` has 5 tasks, then there will be 10 `barrier` calls in `X` and 5 in Y`, which will unsync the whole MPI space-time continuum and cause confusing, difficult-to-debug lockups while things deadlock waiting for barriers that are never going to arrive.

Anyway, we want to remove those `waitAll` calls and their underlying `mpi.barrier` calls from those utilities.

If they are truly necessary to solve issues we were searching for, we will need to design and implement non-global MPI solutions, which should hopefully be possible.

**Comment by john-science** [comment]
@mgjarrett @onufer Just FYI.
