### ISSUE TITLE
Cumulative parameters as they relate to numerical diffusion during uniform mesh conversion

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#985]
During the uniform mesh conversion process, we know that there is some numerical diffusion going on when we map non-volume-integrated block parameters (a thermodynamicist would call these "intensive" properties) from the uniform mesh back to the non-uniform mesh. 

For parameters which are NOT time-integrated (i.e. reaction rates, power density, etc.), this numerical diffusion does exist, but it might not be blatant in the results, and further it does not compound with time because the parameter is recomputed at each time node.

But for parameters which are time-integrated, the numerical diffusion can sometimes be very obvious, for instance when a value that is physically monotonically increasing ends up decreasing. We have seen this sometimes happen with accumulated DPA, for example. The other reason it can be more important is because the time history matters for time-integrated parameters, meaning the numerical diffusion directly compounds.

We _sometimes_ designate these time-integrated parameters as "cumulative", as in here, but I find that to be inconsistent (for instance, number densities are time-integrated but not specified as such):
https://github.com/terrapower/armi/blob/36fe1bced3b817d6d76e66cf99dd355219993e63/armi/reactor/blockParameters.py#L128-L133

We really have nothing to guard against this numerical diffusion. I think that there are at least a few things that we can do:
1. For time-integrated parameters that are marked as "cumulative", we can skip mapping them to/from the uniform mesh. What we really are calculating on the uniform mesh are the _rates_ at which those time-integrated parameters change, and we can do the `rate * time` calculation after all the uniform mesh stuff is over with. This will require some restructuring, but will entirely avoid non-physical results for values that should be monotonic (obviously diffusion in the rates will still take place, but that is unavoidable).
2. If we don't want to do (1), then we can at least put a check in there that if a monotonically-increasing "cumulative" parameter _decreases_, we can warn the user that they are using too coarse of a mesh. This would require us to label "cumulative" parameters as either monotonically-increasing, decreasing, or neither.
3. We can give the user control over the uniform meshing averaging tolerance that is used. Right now we use the default tolerance in the [`average1DWithinTolerance()`](https://github.com/terrapower/armi/blob/8cc08e5e2f45ce442d31f0e83d6c13201e351480/armi/utils/mathematics.py#L27-L57) function, which is 20%. IMO, that is very large, although I suppose a smaller tolerance will directly lead to increased computation time? Perhaps that has been optimized in some way, but this could be problem-specific and giving the user control over this via the case settings would be a useful way to tamp down that numerical diffusion.
4. We can try to more-narrowly limit the scope of which parameters are actually remapped. Right now we limit that scope via the [`PARAM_MAPPING_CATEGORIES`](https://github.com/terrapower/armi/blob/main/armi/reactor/converters/uniformMesh.py#L796) list, but this list could include parameters that are not necessary to be converted for the physics calc that is taking place. For instance, if a FP plugin defines a parameter like `cladStress` and puts it in the very reasonable `pinQuantities` category, then it would be remapped during calls to the `NeutronicsUniformMeshGenerator` and numerical diffusion would result even though it was completely unnecessary to remap that parameter for a neutronics calculation.
5. For interface stacks where we'll have to do multiple uniform mesh conversions in a row (for instance, neutron flux followed by gamma flux), doing the conversion twice is unnecessary and will introduce double the diffusion. It would also save a lot of compute time. I think it should be possible to hold over the uniform reactor between interfaces, with some additional tooling in the interface classes. Maybe adding a `REQUIRES_UNIFORM_MESH` class variable or something that the current interface could check for in the next interface in the stack before converting back to the non-uniform mesh. I could see this applying to gamma, maybe critical rod iterations, some xs solves, maybe others?

The alternative is basically to just accept the diffusion and refine the mesh heavily, which I suppose is a valid option as well.

My opinion is that at least (1) would be worthwhile, since that is a concrete way to completely avoid numerical diffusion for certain parameters. I also think (5) would be beneficial from both a diffusion and a runtime perspective. But I am completely open to other opinions.

@jakehader Your input on how/if we want to proceed on something like this would be super valuable. Thoughts from others also welcome!

**Comment by mgjarrett** [comment]
We are addressing this issue, at least in part, with #992 . A few comments for posterity:

- At a high level, #992 implements (4) above. The implementation allows the mapping to be customized for individual use cases, which in part allows (1) to be realized as well.
- If the implementation of (1) and (4) is successful, (2) should not be necessary.
- (5) could still be implemented to reduce computation time, but #992 will at least address the numerical diffusion / correctness aspect called out there.
- (3) is definitely something worth considering for the future.
