### ISSUE TITLE
Request: Speed up the uniform mesh converter

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#991]
The uniform mesh converter can sometimes take a very long time. However the majority of what it does is loop over all the assemblies in the core and assign parameters back and forth between blocks. 

Calls to [`setAssemblyStateFromOverlaps`](https://github.com/terrapower/armi/blob/main/armi/reactor/converters/uniformMesh.py#L397) are all completely independent and could benefit from parallel execution. Based on looking at the uniform mesh generator, this should cover the majority of the work in that class and I think could speed up the conversion process a ton.

**Comment by ntouran** [comment]
Can we at least run the operation through the profiler first to see exactly what the slow bottlenecks are with precision instrumentation? Then we can see if there's any superlow hanging fruit before parallelizing.

**Comment by keckler** [comment]
Yes, a very good idea! This was just based on the keckler-profiler, aka my eyeballs looking at the exploding runtimes.

**Comment by jakehader** [comment]
> Can we at least run the operation through the profiler first to see exactly what the slow bottlenecks are with precision instrumentation? Then we can see if there's any superlow hanging fruit before parallelizing.

I did this months ago but didn't write seem to write it down. It is slow on getting and setting number densities for each block in the core. I feel like this suggest keeps getting made. @john-science did timing tests of this already a couple months ago too.

**Comment by john-science** [comment]
A good process for speeding up code goes something like:

1. Profile the code.
2. Review the code profile and see where the slow-downs are and what expensive operations are being called inside nested loops that can easily be improved.
3. See what data structures are being used.
4. See if we can lean more on NumPy versus pure Python
5. and on and on and on...
6. The very last act of desperation is deciding you have sped up the code as much as humanly possible and you need to parallelize it.

It is not appropriate to say "We need to parallelize this code" before you've done any work to improve it's performance.

**Comment by john-science** [comment]
Also, and not for nothing, you want to parallelize the uniform mesh converter?  Even though the ARMI model is already run in parallel?

You can't spawn parallel code INSIDE code that's already parallel.

Is the uniform mesh converter run outside the already parallel code in the ARMI interface loop?

**Comment by mgjarrett** [comment]
I'm still experimenting with the profiler, but here are some preliminary results. I ran a script that loads up a reactor, does a uniform mesh conversion and then de-conversion. 50% of the overall run time is spent in `makeAssemWithUniformMesh`, with most of that being spent in this [`block.deepcopy()`](https://github.com/terrapower/armi/blob/e47abd2690e3833bf8e3ed02225df2ddea6bc017/armi/reactor/converters/uniformMesh.py#L418):

![image](https://user-images.githubusercontent.com/11633797/208501943-7b1e22f1-01fd-4bbb-811f-84cb72b44a00.png)

I don't think we really need a `deepcopy` here. We just want a new block that has the same name and as the original. We're going to overwrite everything else (height, number densities, parameters, etc.) We could probably cut down a good chunk of this overhead if we avoid a `deepcopy`.

**Comment by mgjarrett** [comment]
I implemented a method for instantiating a new block that's much lighter than a `deepcopy`. This reduced the time spent on creating new blocks by an order of magnitude, and now the long pole in the tent is `parameterDefinitions.__getitem__`.

In a test case where `makeAssemWithUniformMesh` is called 155 times (for 155 assemblies), `parameterDefinitions.__getitem__` is called 2,523,029 times.

![image](https://user-images.githubusercontent.com/11633797/208568065-5f2dcbc8-26e6-4d6b-92a1-475254c3fc8e.png)

The expensive line is this one, which walks through all of the parameters defined in the collection and performs a string comparison to the `name` that was passed in to the function.

https://github.com/terrapower/armi/blob/59b0cad5da848f8dfd1fa65e6cb858f42f964061/armi/reactor/parameters/parameterDefinitions.py#L413

I think we can cut run time down by at least an order of magnitude if this can be converted to a hashed lookup. I opened #1039 to track developments on that front.

**Comment by john-science** [comment]
Great progress @mgjarrett !

Removing a `deepcopy()` is usually a win.  In _most_ languages, doing a "deep copy" of an object is an expensive operation.  So, that makes good sense.

My first though on `__getitem__()` was "that's a system library, you're not going to speed that up". But I'm glad to see that it all comes down to one line that couple be optimized.

You're burying the lead though.  I've always here it was the number densities that were the slowest part of ARMI, specifically the meshing.  So... you did an actual profile and found otherwise.  That's great!  Way to use analytical data, instead of just trusting the standard wisdom.  You rock.
