### ISSUE TITLE
Create a Plugin for the ADDER Depletion Code

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#996]
ANL has recently released a depletion solver that can manage transmutations and decays - https://github.com/anl-rtr/adder. It would be nice to incorporate this code as a plugin to the ARMI framework ecosystem so that end users can make use of the ARMI framework for physics analyses out of the box. This would be similar to the developments of:

- https://github.com/terrapower/armicontrib-dif3d
- https://github.com/terrapower/dragon-armi-plugin
- https://github.com/terrapower/armicontrib-openmc

**Comment by keckler** [comment]
OpenMC also supports depletion. So this might be overlapping if we're already going to implement a more-complete OpenMC plugin. But I don't know the roadmap for that, so maybe not.

**Comment by jakehader** [comment]
I am not sure but I believe the ADDER code may be an attempt to decouple depletion from OpenMC. I'll need to verify this though.
